# CE-clean-only full-scale baseline — crop1.5 (Seed 105)

Train **one** new binary MiniFASNetV2:  with **TRAIN_SEED=105**.
Total loss = CE_clean; no worst-view loss, spectral selection or auxiliary loss/forward. Historical C_FULL includes L_aux and is a different baseline.

Matched notebook18 full-scale controls: full eligible CelebA Train, full Test-as-Val selection/calibration, full LCC train/dev/eval/combined benchmarks, fixed architecture/crop factor 1.5, batch 256, 12 epochs (milestones [4,8], gamma 0.2), SGD lr=0.005, momentum=0.9, weight_decay=5e-4, data seed 43.

Tự động nhận diện đường dẫn Dataset trên **Kaggle** (hỗ trợ mọi slug phổ biến , , ). Tự động đánh giá đầy đủ **CelebA Test**, **4-split LCC FASD** và **CASIA-FASD** (Zero-shot + Calibrated), xuất file ZIP hoàn chỉnh để tải về chỉ với 1 click.

In [1]:
# Edit Kaggle paths here. Full official split manifests are in RESOURCE_ROOT.
import sys, os
from pathlib import Path

def find_path(candidates, default):
    for p in candidates:
        if Path(p).exists():
            return str(p)
    return str(default)

TRAIN_SEED = 105  # Seed 105; DATA_SEED remains 43.
DATA_SEED = 43
RUN_FILTER = None  # None or ["CE_CLEAN_FULL_crop15"].
RESUME = True
NUM_WORKERS = 4
AMP = True
BATCH_SIZE = 256
MAX_EPOCHS = 12
MILESTONES = [4, 8]
GAMMA = .2
PATIENCE_START_EPOCH = 9
EARLY_STOP_PATIENCE = 3
WARMUP_EPOCHS = 1
CSMR_PRESERVE_DC = True
SELECTION_CHUNK_SIZE = 32
CROP_SCALE = 1.5
TRAIN_CROP_FACTOR = 1.5
EVAL_CROP_FACTOR = 1.5
LOG_EVERY_BATCHES = 25
INPUT_SIZE = 80
METRIC_TIE_EPS = 1e-12

RESOURCE_ROOT = find_path([
    '/kaggle/input/datasets/locngodev/full-resources-pooled/minifasnet_binary_crossdomain_resources_v2_lcc_pooled',
    '/kaggle/input/datasets/maithanhphuong/full-resources-v3/minifasnet_binary_crossdomain_resources_v2_lcc_pooled',
    '/kaggle/input/datasets/quetv5/full-resources/minifasnet_binary_crossdomain_resources_v2_lcc_pooled',
    '/kaggle/input/full-resources-pooled/minifasnet_binary_crossdomain_resources_v2_lcc_pooled',
    '/kaggle/input/full-resources-v3/minifasnet_binary_crossdomain_resources_v2_lcc_pooled',
    '/kaggle/input/full-resources/minifasnet_binary_crossdomain_resources_v2_lcc_pooled',
    '/content/full_resources/minifasnet_binary_crossdomain_resources_v2_lcc_pooled',
    '/content/minifasnet_binary_crossdomain_resources_v2_lcc_pooled'
], '/kaggle/input/datasets/maithanhphuong/full-resources-v3/minifasnet_binary_crossdomain_resources_v2_lcc_pooled')

CELEBA_ROOT = find_path([
    '/kaggle/input/datasets/attentionlayer241/celeba-spoof-for-face-antispoofing/CelebA_Spoof_/CelebA_Spoof',
    '/kaggle/input/celeba-spoof-for-face-antispoofing/CelebA_Spoof_/CelebA_Spoof',
    '/kaggle/input/celeba-spoof/CelebA_Spoof_/CelebA_Spoof',
    '/content/celeba_spoof/CelebA_Spoof_/CelebA_Spoof'
], '/kaggle/input/datasets/attentionlayer241/celeba-spoof-for-face-antispoofing/CelebA_Spoof_/CelebA_Spoof')

LCC_ROOT = find_path([
    '/kaggle/input/datasets/faber24/lcc-fasd/LCC_FASD',
    '/kaggle/input/lcc-fasd/LCC_FASD',
    '/content/lcc_fasd/LCC_FASD',
    '/content/LCC_FASD'
], '/kaggle/input/datasets/faber24/lcc-fasd/LCC_FASD')

MINIFASNET_SOURCE_PATH = find_path([
    '/kaggle/input/datasets/locngodev/minifasnet/MiniFASNet.py',
    '/kaggle/input/datasets/maithanhphuong/minifasnet/MiniFASNet.py',
    '/kaggle/input/datasets/quetv5/minifasnet/MiniFASNet.py',
    '/kaggle/input/minifasnet/MiniFASNet.py',
    '/content/minifasnet/MiniFASNet.py',
    '/content/MiniFASNet.py'
], '/kaggle/input/datasets/maithanhphuong/minifasnet/MiniFASNet.py')

MINIFASNET_CHECKPOINT_PATH = find_path([
    '/kaggle/input/datasets/locngodev/minifasnet/2.7_80x80_MiniFASNetV2.pth',
    '/kaggle/input/datasets/maithanhphuong/minifasnet/2.7_80x80_MiniFASNetV2.pth',
    '/kaggle/input/datasets/quetv5/minifasnet/2.7_80x80_MiniFASNetV2.pth',
    '/kaggle/input/minifasnet/2.7_80x80_MiniFASNetV2.pth',
    '/content/minifasnet/2.7_80x80_MiniFASNetV2.pth',
    '/content/2.7_80x80_MiniFASNetV2.pth'
], '/kaggle/input/datasets/maithanhphuong/minifasnet/2.7_80x80_MiniFASNetV2.pth')

CASIA_ROOT = find_path([
    '/kaggle/input/datasets/minhnh2107/casiafasd',
    '/kaggle/input/casiafasd',
    '/kaggle/input/casia-fasd',
    '/content/casiafasd',
    '/content/casia_fasd'
], '/kaggle/input/datasets/minhnh2107/casiafasd')

SCRFD_MODEL_PATH = find_path([
    '/kaggle/input/datasets/quetv5/scrfd-models/det_500m.onnx',
    '/kaggle/input/scrfd-model/det_500m.onnx',
    '/content/scrfd/det_500m.onnx',
    '/content/det_500m.onnx'
], '/kaggle/input/datasets/locngodev/scrfd-model/det_500m.onnx')

OUTPUT_ROOT = f'/kaggle/working/21_fullscale_CE_clean_baseline_crop15_s{TRAIN_SEED}'

RUNS = {'CE_CLEAN_FULL_crop15': {'method': 'CLEAN', 'objective': 'CE_clean only', 'warmup_epochs': 0,
 'crop_factor': 1.5, 'centers': None, 'sigma': None, 'clean_ce_weight': 1., 'spectral_ce_weight': 0., 'aux_loss_weight': 0.}}

def select_runs(run_filter):
    if run_filter is not None and (not isinstance(run_filter, (list, tuple)) or not run_filter or len(set(run_filter)) != len(run_filter) or set(run_filter) - set(RUNS)):
        raise ValueError('RUN_FILTER must be None or ["CE_CLEAN_FULL_crop15"]')
    return [name for name in RUNS if run_filter is None or name in run_filter]

CALIBRATE_CASIA_THRESHOLD = True  # train-only fitting; source results retained
INSTALL_DETECTOR_DEPS = True
ONNXRUNTIME_GPU_SPEC = 'onnxruntime-gpu==1.26.0'
MIN_VALID_FRAMES = 4
DETECTION_LOG_EVERY = 100
DETECTOR_SIZES = [(640, 640), (480, 480), (320, 320)]
DETECTOR_CONFIDENCE = .5

In [2]:
from pathlib import Path
# SETUP — import PyTorch first to expose its CUDA/cuDNN libraries.
import os,sys,subprocess,random,time,gc,importlib.util
from importlib.metadata import version,PackageNotFoundError
import torch
print('PyTorch:',torch.__version__, 'CUDA:',torch.version.cuda, 'GPU:',torch.cuda.is_available(),flush=True)
if not torch.cuda.is_available():
    raise RuntimeError('Enable Kaggle Settings > Accelerator > GPU and restart the session.')
def installed(name):
    try:return version(name)
    except PackageNotFoundError:return None
if INSTALL_DETECTOR_DEPS:
    ready=(installed('insightface')=='2.0' and installed('onnxruntime-gpu')=='1.26.0' and installed('onnxruntime') is None)
    if not ready:
        if 'onnxruntime' in sys.modules or 'insightface' in sys.modules:
            raise RuntimeError('Restart the Kaggle session before changing detector dependencies.')
        subprocess.check_call([sys.executable,'-m','pip','install','-q','insightface==2.0'])
        subprocess.check_call([sys.executable,'-m','pip','uninstall','-y','onnxruntime','onnxruntime-gpu'])
        subprocess.check_call([sys.executable,'-m','pip','install','-q',ONNXRUNTIME_GPU_SPEC])
import cv2,numpy as np,pandas as pd,json,re,math,zipfile,types
from torch import nn
from sklearn.metrics import roc_curve,roc_auc_score
from IPython.display import display,FileLink
import matplotlib.pyplot as plt
import onnxruntime as ort
from insightface import model_zoo
if hasattr(ort,'preload_dlls'):ort.preload_dlls()
print('ONNX Runtime:',ort.__version__,'providers:',ort.get_available_providers(),flush=True)
if 'CUDAExecutionProvider' not in ort.get_available_providers():
    raise RuntimeError('CUDAExecutionProvider unavailable; restart and rerun the setup cell.')
random.seed(TRAIN_SEED);np.random.seed(TRAIN_SEED);torch.manual_seed(TRAIN_SEED);torch.cuda.manual_seed_all(TRAIN_SEED)
torch.backends.cudnn.benchmark=False
torch.backends.cudnn.deterministic=True
cv2.setNumThreads(1)
device=torch.device('cuda')
Path(OUTPUT_ROOT).mkdir(parents=True,exist_ok=True)
for path in [Path(SCRFD_MODEL_PATH),Path(CASIA_ROOT)/'train_img/train_img/color',Path(CASIA_ROOT)/'test_img/test_img/color']:
    if not path.exists():raise FileNotFoundError(path)

# Check the real detector session before spending time on full-scale training.
preflight_detector=model_zoo.get_model(str(SCRFD_MODEL_PATH),providers=['CUDAExecutionProvider','CPUExecutionProvider'])
if preflight_detector is None:raise RuntimeError('Could not load mounted SCRFD model')
preflight_detector.prepare(ctx_id=0,input_size=DETECTOR_SIZES[0],det_thresh=DETECTOR_CONFIDENCE)
if 'CUDAExecutionProvider' not in preflight_detector.session.get_providers():
    raise RuntimeError('SCRFD CUDA session failed; fix detector dependencies before training')
print('SCRFD preflight providers:',preflight_detector.session.get_providers(),flush=True)
del preflight_detector;gc.collect();torch.cuda.empty_cache()

PyTorch: 2.11.0+cu128 CUDA: 12.8 GPU: True
Found existing installation: onnxruntime 1.31.1
Uninstalling onnxruntime-1.31.1:
  Successfully uninstalled onnxruntime-1.31.1

WARNING: Skipping onnxruntime-gpu as it is not installed.

ONNX Runtime: 1.26.0 providers: ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider']
SCRFD preflight providers: ['CUDAExecutionProvider', 'CPUExecutionProvider']

In [3]:

import hashlib, time, shutil, importlib.util, inspect, json, math, os, random, zipfile
from collections import Counter, OrderedDict
from pathlib import Path
import albumentations as A
import cv2, numpy as np, pandas as pd, torch
import torch.nn as nn
import torch.nn.functional as F
from sklearn.metrics import roc_auc_score, roc_curve
from torch.utils.data import Dataset, DataLoader
from IPython.display import FileLink, display

_BBOX_RNG=random.Random(TRAIN_SEED+500000)
AUG_SEED=TRAIN_SEED
BBOX_SEED=TRAIN_SEED+500000
GAIN_SEED=TRAIN_SEED+11000
GAIN_RANGE=(.65,.90)
SPLITS=('training','development','evaluation')
EXPECTED_LCC={'training':8299,'development':2948,'evaluation':7580,'combined':18827}
if RUN_FILTER is not None and (not isinstance(RUN_FILTER,(list,tuple)) or not RUN_FILTER or len(set(RUN_FILTER))!=len(RUN_FILTER) or set(RUN_FILTER)-set(RUNS)):
    raise ValueError('RUN_FILTER contains an unknown or duplicate run ID')
if NUM_WORKERS<1:raise ValueError('NUM_WORKERS must be >= 1')
if (BATCH_SIZE,MAX_EPOCHS,MILESTONES,GAMMA)!=(256,12,[4,8],.2) or type(TRAIN_SEED) is not int or TRAIN_SEED not in (100,101,102,105):raise RuntimeError('Frozen fullscale recipe or approved seed changed')
root=Path(RESOURCE_ROOT);out=Path(OUTPUT_ROOT);source=Path(MINIFASNET_SOURCE_PATH);pretrained=Path(MINIFASNET_CHECKPOINT_PATH)
for path in (source,pretrained,root/'manifests/crossdomain_train_full.csv',
             root/'manifests/crossdomain_celeba_source_dev_full.csv',root/'bbox/celeba_bbox_cache_full.json',
             root/'labels/celeba_auxiliary_labels.csv'):
    if not path.is_file():raise FileNotFoundError(path)
def read_json(path):return json.loads(Path(path).read_text())
def write_json(path,value):
    path=Path(path);path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(json.dumps(value,indent=2,sort_keys=True,allow_nan=False)+'\n')
def save_torch(path,value):
    path=Path(path);tmp=path.with_suffix(path.suffix+'.tmp')
    torch.save(value,tmp);os.replace(tmp,path)
def seed_all(seed):
    random.seed(seed);np.random.seed(seed);torch.manual_seed(seed)
    if torch.cuda.is_available():torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic=True;torch.backends.cudnn.benchmark=False

def sha(path):
    h=hashlib.sha256()
    with Path(path).open('rb') as f:
        for block in iter(lambda:f.read(1048576),b''): h.update(block)
    return h.hexdigest()
def state_sha(state):
    h=hashlib.sha256()
    for k in sorted(state):
        v=state[k].detach().cpu().contiguous();h.update(k.encode());h.update(str(v.dtype).encode());h.update(str(tuple(v.shape)).encode());h.update(v.numpy().tobytes())
    return h.hexdigest()
def require_record(rec,key):
    if rec.get('status')!='VALID' or rec.get('usable_for_pad') is not True or rec.get('bbox_origin')!='SCRFD' or rec.get('source_key')!=key or not str(rec.get('bbox_source','')).startswith('SCRFD'):raise RuntimeError('Unscorable/non-SCRFD: '+key)
    box=rec.get('bbox_xyxy')
    if box is None or len(box)!=4 or 'crop_factor' in rec:raise RuntimeError('Not a raw bbox: '+key)
    x1,y1,x2,y2=map(float,box)
    if not np.isfinite(box).all() or x2<=x1 or y2<=y1:raise RuntimeError('Invalid bbox: '+key)
    return rec

def mini_crop_bgr(image,bbox_xyxy,scale=CROP_SCALE,size=INPUT_SIZE):
    # Exact 03b CropImage-compatible geometry.
    src_h,src_w=image.shape[:2];x1,y1,x2,y2=map(float,bbox_xyxy);box_w,box_h=x2-x1,y2-y1
    if box_w<=0 or box_h<=0 or src_w<2 or src_h<2:raise ValueError('Invalid crop geometry')
    used=min((src_h-1)/box_h,(src_w-1)/box_w,float(scale));new_w,new_h=box_w*used,box_h*used
    cx,cy=box_w/2+x1,box_h/2+y1;left,top=cx-new_w/2,cy-new_h/2;right,bottom=cx+new_w/2,cy+new_h/2
    if left<0:right-=left;left=0
    if top<0:bottom-=top;top=0
    if right>src_w-1:left-=right-src_w+1;right=src_w-1
    if bottom>src_h-1:top-=bottom-src_h+1;bottom=src_h-1
    lx,ty,rx,by=map(int,(left,top,right,bottom))
    if lx<0 or ty<0 or rx>=src_w or by>=src_h or rx<lx or by<ty:raise RuntimeError('Crop escaped image')
    patch=image[ty:by+1,lx:rx+1]
    if patch.size==0:raise RuntimeError('Empty crop')
    return cv2.resize(patch,(size,size))

# The literature's augmentation ranges are fixed. Support both documented Albumentations APIs.
# ISONoise works in RGB/HSV; convert only within augmentation, then restore BGR for MiniFASNet.
iso_params=inspect.signature(A.ISONoise).parameters
brightness_params=inspect.signature(A.RandomBrightnessContrast).parameters
blur_params=inspect.signature(A.MotionBlur).parameters
if {'color_shift','intensity'}<=set(iso_params) and {'brightness_limit','contrast_limit'}<=set(brightness_params) and 'blur_limit' in blur_params:
    AUGMENTATION_API='legacy_limits'
    iso=A.ISONoise(color_shift=(.15,.35),intensity=(.2,.5),p=.2)
    bright=A.RandomBrightnessContrast(brightness_limit=.2,contrast_limit=.2,brightness_by_max=True,p=.3)
    motion=A.MotionBlur(blur_limit=5,p=.2)
elif {'color_shift_range','intensity_range'}<=set(iso_params) and {'brightness_range','contrast_range'}<=set(brightness_params) and 'blur_range' in blur_params:
    AUGMENTATION_API='range_parameters'
    iso=A.ISONoise(color_shift_range=(.15,.35),intensity_range=(.2,.5),p=.2)
    bright=A.RandomBrightnessContrast(brightness_range=(-.2,.2),contrast_range=(-.2,.2),brightness_by_max=True,p=.3)
    motion=A.MotionBlur(blur_range=(3,5),p=.2)
else:raise RuntimeError('Unsupported Albumentations augmentation API; freeze and audit a compatible version')
COPY_AUG=A.Compose([A.HorizontalFlip(p=.5),iso,bright,motion])
def copied_aug_bgr(patch):
    rgb=cv2.cvtColor(patch,cv2.COLOR_BGR2RGB)
    augmented=COPY_AUG(image=rgb)['image']
    return cv2.cvtColor(augmented,cv2.COLOR_RGB2BGR)
def tensor_of(patch):
    if patch.shape!=(80,80,3) or patch.dtype!=np.uint8:raise ValueError('Expected BGR uint8 80x80')
    return torch.from_numpy(np.ascontiguousarray(patch.transpose(2,0,1))).float().div_(255.)

class PADNet(nn.Module):
    def __init__(self,copied):
        super().__init__();self.copied=copied
        self.trunk=module.MiniFASNetV2(embedding_size=128,conv6_kernel=(5,5),drop_p=.2,num_classes=3,img_channel=3)
        if copied:
            self.trunk.prob=nn.Identity()
            self.pad_head=nn.Linear(128,2);self.spoof_type_head=nn.Linear(128,11)
            self.lighting_head=nn.Linear(128,5);self.attributes_head=nn.Linear(128,40)
    def features(self,x):
        t=self.trunk
        for layer in (t.conv1,t.conv2_dw,t.conv_23,t.conv_3,t.conv_34,t.conv_4,t.conv_45,t.conv_5,t.conv_6_sep,t.conv_6_dw,t.conv_6_flatten):x=layer(x)
        if t.embedding_size!=512:x=t.linear(x)
        x=t.drop(t.bn(x))
        if x.ndim!=2 or x.shape[1]!=128:raise RuntimeError('MiniFAS representation is not [B,128]')
        return x
    def forward(self,x,aux=False):
        z=self.features(x)
        if not self.copied:return self.trunk.prob(z)
        pad=self.pad_head(z)
        if aux:return pad,self.spoof_type_head(z),self.lighting_head(z),self.attributes_head(z)
        return pad

def pad_score(logits):
    z=torch.as_tensor(logits)
    if z.shape[1]==3:return (z[:,0]-torch.logsumexp(z[:,1:],dim=1)).float().cpu().numpy()
    if z.shape[1]==2:return (z[:,0]-z[:,1]).float().cpu().numpy()
    raise ValueError('Expected two or three PAD logits')
def threshold_from_val(y3,scores):
    y=np.asarray(y3,dtype=np.int64);s=np.asarray(scores,dtype=np.float64)
    if len(y)!=len(s) or not len(y) or not np.isfinite(s).all() or set(np.unique(y))!={0,1,2}:raise ValueError('Val needs all three classes')
    order=np.argsort(s,kind='mergesort');v=s[order];real=(y[order]==0);nr=int(real.sum());na=len(y)-nr
    bound=np.r_[0,np.flatnonzero(np.diff(v))+1,len(v)];rp=np.r_[0,np.cumsum(real)];ap=np.r_[0,np.cumsum(~real)];pairs=[]
    for j,k in enumerate(bound):
        t=float(np.nextafter(v[0],-np.inf)) if j==0 else (float(np.nextafter(v[-1],np.inf)) if j==len(bound)-1 else float(v[k-1]/2+v[k]/2))
        pairs.append((.5*(rp[k]/nr+(na-ap[k])/na),abs(t),t))
    return min(pairs)[2]
def metrics(y3,scores,threshold,candidate_n):
    y=np.asarray(y3,dtype=int);s=np.asarray(scores,dtype=float);real=y==0
    if len(y)!=len(s) or set(real)!={False,True} or not np.isfinite(s).all():raise ValueError('Invalid metric population')
    fpr,tpr,thr=roc_curve(real.astype(int),s);eer_idx=int(np.argmin(abs(fpr-(1-tpr))))
    pred=s>=threshold;apcer=float(pred[~real].mean());bpcer=float((~pred[real]).mean())
    return {'auc':float(roc_auc_score(real.astype(int),s)),'eer':float(.5*(fpr[eer_idx]+1-tpr[eer_idx])),
      'tpr_at_fpr_1pct':float(np.interp(.01,fpr,tpr)),'apcer':apcer,'bpcer':bpcer,'acer':.5*(apcer+bpcer),
      'hter':.5*(apcer+bpcer),'binary_accuracy':float((pred==real).mean()),'locked_source_threshold':float(threshold),
      'candidate_n':int(candidate_n),'scored_n':len(y),'detector_coverage':len(y)/candidate_n}



def aligned_margin(logits,binary):
    d=logits[:,0].float()-logits[:,1].float()
    return torch.where(binary==0,d,-d)


def restore_rng(state,gain_rng):
    random.setstate(state['python']);np.random.set_state(state['numpy']);torch.set_rng_state(state['torch'])
    torch.cuda.set_rng_state_all(state['cuda']);gain_rng.set_state(state['gain']);_BBOX_RNG.setstate(state['bbox'])
def bbox_jitter(rec):
    x1,y1,x2,y2=map(float,rec['bbox_xyxy']);w,h=x2-x1,y2-y1
    if _BBOX_RNG.random()<.20:
        base=max(w,h);cx,cy=(x1+x2)/2,(y1+y2)/2;scale=_BBOX_RNG.uniform(.95,1.05)
        cx+=_BBOX_RNG.uniform(-.05,.05)*base;cy+=_BBOX_RNG.uniform(-.05,.05)*base;w*=scale;h*=scale
        return [cx-w/2,cy-h/2,cx+w/2,cy+h/2]
    return [x1,y1,x2,y2]


def load_frame(name):return pd.read_csv(root/'manifests'/(name+'.csv'),keep_default_na=False)
train=load_frame('crossdomain_train_full')
test=load_frame('crossdomain_celeba_source_dev_full')
val=test.loc[test.usable_for_pad.astype(bool)].copy()  # Full official Test-as-Val selection set.
records=read_json(root/'bbox/celeba_bbox_cache_full.json')['records']
aux=pd.read_csv(root/'labels/celeba_auxiliary_labels.csv',keep_default_na=False).set_index('sample_key',verify_integrity=True)
if (len(train),len(test),len(val))!=(484561,67170,66379):raise RuntimeError('Unexpected full official populations')
if train.sample_key.duplicated().any() or test.sample_key.duplicated().any() or set(train.sample_key)&set(test.sample_key):raise RuntimeError('Train/Test sample overlap')
for frame in (train,val,test):
    if not set(frame.sample_key)<=set(records) or not set(frame.sample_key)<=set(aux.index):raise RuntimeError('Missing cache/aux entry')
for frame in (train,val):
    if not frame.usable_for_pad.astype(bool).all() or set(frame.bbox_origin)!={'SCRFD'} or set(frame.three_class_label)!={0,1,2}:raise RuntimeError('Unusable full split')
# Candidate accounting uses existing official metadata, with the unchanged 00c eligibility rule.
def train_exclusion_reason(key):
    rec=records[key]
    if rec['status'] in {'SUSPICIOUS','DET_FAIL','UNREADABLE'}:return rec['status']
    try:require_record(rec,key)
    except RuntimeError:return 'INVALID_BBOX'
    x1,y1,x2,y2=map(float,rec['bbox_xyxy'])
    return 'TOO_SMALL' if min(x2-x1,y2-y1)<48 else ''
train_candidates=aux.loc[aux.official_split=='train'].reset_index()
train_candidates['exclusion_reason']=[train_exclusion_reason(k) for k in train_candidates.sample_key]
if len(train_candidates)!=494405 or set(train_candidates.loc[train_candidates.exclusion_reason=='','sample_key'])!=set(train.sample_key):raise RuntimeError('Full train membership differs from official eligibility; no sampling allowed')
if set(aux.loc[aux.official_split=='test'].index)!=set(test.sample_key):raise RuntimeError('Test manifest is not the full official Test')
def population_counts(frame,three_col='three_class_label',attack_col='attack_code'):
    classes={str(k):int(v) for k,v in frame[three_col].value_counts().sort_index().items()}
    return {'n':len(frame),'three_class_counts':classes,'real_n':classes.get('0',0),'attack_n':len(frame)-classes.get('0',0),
            'spoof_type_counts':{str(k):int(v) for k,v in frame[attack_col].value_counts().sort_index().items()}}
DATA_COUNTS={'train_candidates':population_counts(train_candidates,attack_col='spoof_type'),
 'train_usable':population_counts(train),'train_excluded':len(train_candidates)-len(train),
 'train_exclusion_reasons':{str(k):int(v) for k,v in train_candidates.loc[train_candidates.exclusion_reason!='','exclusion_reason'].value_counts().items()},
 'test_candidates':population_counts(test),'test_usable':population_counts(val),'test_unscored':len(test)-len(val),
 'train_test_identity_overlap':sorted(set(train.subject_id.astype(str))&set(test.subject_id.astype(str))),
 'identity_overlap_policy':'Official membership retained; no subject removal or new split',
 'sampling':'None; full official eligible Train and full official Test-as-Val', 'data_seed':DATA_SEED}
lcc_frames={};lcc_records={}
for split in ('training','development','evaluation','combined'):
    name='lcc_official_evaluation_full' if split=='evaluation' else 'lcc_'+split+'_full'
    cache_name='lcc_official_evaluation_bbox_cache' if split=='evaluation' else 'lcc_'+split+'_bbox_cache'
    path=root/'manifests'/(name+'.csv');cache=root/'bbox'/(cache_name+'.json')
    if not path.is_file() or not cache.is_file():raise FileNotFoundError((path,cache))
    frame=pd.read_csv(path,keep_default_na=False)
    if len(frame)!=EXPECTED_LCC[split] or frame.path.duplicated().any():raise RuntimeError('Unexpected LCC population: '+split)
    recs=read_json(cache)['records'] if split!='combined' else None
    if recs is not None and set(frame.path)!=set(recs):raise RuntimeError('LCC manifest/cache keys differ: '+split)
    lcc_frames[split]=frame;lcc_records[split]=recs
ordered_pool=pd.concat([lcc_frames[s].assign(lcc_split=s) for s in SPLITS],ignore_index=True)
if not lcc_frames['combined'].equals(ordered_pool):raise RuntimeError('Combined LCC manifest differs from physical splits')
if not torch.cuda.is_available():raise RuntimeError('Kaggle CUDA GPU required for the frozen fullscale batch size')
source_spec=importlib.util.spec_from_file_location('local_minifasnet_v2',source)
module=importlib.util.module_from_spec(source_spec);source_spec.loader.exec_module(module)
device=torch.device('cuda');use_amp=bool(AMP)
out.mkdir(parents=True,exist_ok=True);(out/'runs').mkdir(exist_ok=True)
(out/'manifests').mkdir(exist_ok=True)
MANIFEST_SOURCES={'full_train.csv':root/'manifests/crossdomain_train_full.csv',
                  'full_test.csv':root/'manifests/crossdomain_celeba_source_dev_full.csv'}
MANIFEST_HASHES={f:sha(p) for f,p in MANIFEST_SOURCES.items()}
for filename,path in MANIFEST_SOURCES.items():shutil.copyfile(path,out/'manifests'/filename)
train_candidates.to_csv(out/'manifests'/'full_train_candidates.csv',index=False)
write_json(out/'manifest_sha256.json',MANIFEST_HASHES)
write_json(out/'dataset_counts.json',DATA_COUNTS)
print('GPU:',torch.cuda.get_device_name(0),'Full Train:',len(train),'Full Test-as-Val usable/candidate:',len(val),len(test),'LCC:',{s:len(f) for s,f in lcc_frames.items()},flush=True)

def init_model(spec):
    seed_all(TRAIN_SEED);model=PADNet(spec['copied']);audit={'initialization':spec['init'],'checkpoint_sha256':sha(pretrained),'source_sha256':sha(source)}
    if spec['init']=='pretrained':
        raw=torch.load(pretrained,map_location='cpu',weights_only=True)
        if not isinstance(raw,OrderedDict) or not raw or not all(k.startswith('module.') for k in raw):raise RuntimeError('Official checkpoint format mismatch')
        stripped=OrderedDict((k[7:],v) for k,v in raw.items())
        if tuple(stripped['prob.weight'].shape)!=(3,128) or tuple(stripped['conv_6_dw.conv.weight'].shape[-2:])!=(5,5):raise RuntimeError('Official checkpoint architecture mismatch')
        target=model.trunk.state_dict();compatible={k:v for k,v in stripped.items() if k!='prob.weight'}
        bad=[k for k,v in compatible.items() if k not in target or tuple(v.shape)!=tuple(target[k].shape)]
        absent=[k for k in target if k not in compatible and k!='prob.weight']
        if bad or absent:raise RuntimeError(f'Pretrained key mismatch: {bad[:5]} {absent[:5]}')
        missing,unexpected=model.trunk.load_state_dict(compatible,strict=False)
        if unexpected or (spec['copied'] and missing) or (not spec['copied'] and set(missing)!={'prob.weight'}):raise RuntimeError('Pretrained load mismatch')
        # Reinitialize historical classifier too; copied heads were initialized by seed 100.
        if not spec['copied']:model.trunk.prob.reset_parameters()
        audit.update({'loaded_keys':sorted(compatible),'skipped_keys':['prob.weight'],'missing_keys':list(missing),'unexpected_keys':list(unexpected)})
    else:audit.update({'loaded_keys':[],'skipped_keys':[],'missing_keys':[],'unexpected_keys':[]})
    for head in (model.spoof_type_head,model.lighting_head,model.attributes_head):
        head.requires_grad_(False)
    audit['objective']='CE_clean only; auxiliary modules frozen and never forwarded'
    audit['initial_state_sha256']=state_sha(model.state_dict())
    with torch.no_grad():
        model.eval();assert model(torch.zeros(2,3,80,80)).shape==(2,2 if spec['copied'] else 3)
    return model,audit

INITIAL_AUDITS={}
for name in RUNS:
    initial_model,initial_audit=init_model({'init':'pretrained','copied':True})
    INITIAL_AUDITS[name]=initial_audit
    del initial_model
INITIAL_HASHES={name:audit['initial_state_sha256'] for name,audit in INITIAL_AUDITS.items()}
if len(set(INITIAL_HASHES.values()))!=1:raise RuntimeError('Initial-state SHA differs')
INITIAL_STATE_SHA=next(iter(INITIAL_HASHES.values()))
write_json(out/'initialization_fairness.json',INITIAL_AUDITS)

class CelebaData(Dataset):
    def __init__(self,frame,training=False,copied=False):self.rows=frame.reset_index(drop=True);self.training=training;self.copied=copied
    def __len__(self):return len(self.rows)
    def __getitem__(self,i):
        row=self.rows.iloc[i];key=str(row.sample_key);rec=require_record(records[key],key)
        image=cv2.imread(str(Path(CELEBA_ROOT)/key),cv2.IMREAD_COLOR)
        if image is None:raise FileNotFoundError(key)
        patch=mini_crop_bgr(image,bbox_jitter(rec) if self.training else rec['bbox_xyxy'])
        if self.training:patch=copied_aug_bgr(patch) if self.copied else mild_aug(patch)
        # Legacy batch shape retained; auxiliary targets are not read or used.
        return tensor_of(patch),int(row.three_class_label),int(row.binary_label),0,0,torch.zeros(40),key

class LCCData(Dataset):
    def __init__(self,split):
        self.split=split;self.rows=lcc_frames[split].loc[lcc_frames[split].usable_for_pad.astype(bool)].reset_index(drop=True)
    def __len__(self):return len(self.rows)
    def __getitem__(self,i):
        row=self.rows.iloc[i];key=str(row.path);rec=require_record(lcc_records[self.split][key],key)
        path=(Path(LCC_ROOT)/'LCC_FASD_evaluation'/key) if self.split=='evaluation' else Path(LCC_ROOT)/key
        image=cv2.imread(str(path),cv2.IMREAD_COLOR)
        if image is None:raise FileNotFoundError(path)
        return tensor_of(mini_crop_bgr(image,rec['bbox_xyxy'])),int(row.label),key

def loader(ds,batch=BATCH_SIZE,shuffle=False,epoch=0):
    gen=torch.Generator().manual_seed(TRAIN_SEED+epoch)
    def worker_init(wid):
        global _BBOX_RNG
        s=TRAIN_SEED+epoch*1000+wid;random.seed(s);np.random.seed(s);torch.manual_seed(s)
        _BBOX_RNG=random.Random(s+500000)
        if hasattr(COPY_AUG,'set_random_seed'):COPY_AUG.set_random_seed(s)
    return DataLoader(ds,batch_size=batch,shuffle=shuffle,num_workers=NUM_WORKERS,pin_memory=True,drop_last=False,generator=gen,worker_init_fn=worker_init)

def infer(model,dl,lcc_mode=False):
    model.eval();keys=[];ys=[];zs=[];started=time.monotonic()
    print('[Inference] Starting',len(dl.dataset),'scored images',flush=True)
    with torch.no_grad():
        for step,batch in enumerate(dl,1):
            if lcc_mode:x,y,k=batch
            else:x,y,_,_,_,_,k=batch
            with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))
            keys.extend(k);ys.extend(y.numpy().tolist());zs.append(z.float().cpu().numpy())
            if step==1 or step%LOG_EVERY_BATCHES==0 or step==len(dl):print(f'[Inference] batch {step}/{len(dl)}, elapsed={time.monotonic()-started:.1f}s',flush=True)
    if not zs:raise RuntimeError('No scorable evaluation samples')
    return list(map(str,keys)),np.asarray(ys,dtype=int),np.concatenate(zs)




def training_terms(model,x,binary,spoof,lighting,attrs,spec,masks,gain_rng,active):
    # A single clean binary forward; no auxiliary outputs or spectral candidates.
    with torch.cuda.amp.autocast(enabled=use_amp):
        logits=model(x)
        loss=F.cross_entropy(logits,binary)
    clean_ce=float(loss.detach())
    return loss,{'train_total_loss':clean_ce,'total_loss':clean_ce,'clean_ce':clean_ce,
                 'spectral_ce':0.,'worst_ce':0.,'aux_loss':0.,'harmful_count':0.,
                 'harmful_fraction':0.,'harmful_ce':0.},Counter(),0.


def snapshot_rng(gain_rng):
    return {'python':random.getstate(),'numpy':np.random.get_state(),'torch':torch.get_rng_state(),
            'cuda':torch.cuda.get_rng_state_all(),'gain':gain_rng.get_state(),'bbox':_BBOX_RNG.getstate()}

def run_config(name,spec):
    return {'run_id':name,'spec':spec,'resource_root':str(root),'train_manifest':'full_train.csv',
      'val_manifest':'full_test.csv','selection_set':'Full official CelebA Test-as-Val; reused selection set, not untouched Test','manifest_sha256':MANIFEST_HASHES,
      'train_crop_factor':1.5,'val_crop_factor':1.5,'test_crop_factor':1.5,'lcc_crop_factor':1.5,'data_seed':DATA_SEED,
      'train_seed':TRAIN_SEED,'initial_state_sha256':INITIAL_STATE_SHA,
      'base_order':'torch Generator(TRAIN_SEED+epoch)','worker_seed':'TRAIN_SEED+epoch*1000+worker_id',
      'bbox_rng_seed':'worker_seed+500000','gain_rng_seed':GAIN_SEED,
      'pretrained_checkpoint':str(pretrained),'model_source':str(source),
      'celeba_root':CELEBA_ROOT,'lcc_root':LCC_ROOT,'num_workers':NUM_WORKERS,
      'batch_size':BATCH_SIZE,'max_epochs':MAX_EPOCHS,'milestones':MILESTONES,'gamma':GAMMA,
      'optimizer':{'name':'SGD','lr':.005,'momentum':.9,'weight_decay':5e-4},
      'warmup_epochs':spec['warmup_epochs'],'patience_start_epoch':PATIENCE_START_EPOCH,'early_stop_patience':EARLY_STOP_PATIENCE,
      'loss':{'CE_clean':1.,'CE_worst':0.,'L_aux':0.},'spectral':None,
      'auxiliary_heads':'state-dict compatibility only; frozen, excluded from optimizer, never forwarded',
      'casia_root':CASIA_ROOT,'scrfd_model_path':SCRFD_MODEL_PATH,'casia_train_threshold_calibration':CALIBRATE_CASIA_THRESHOLD,
      'input':'80x80 BGR float [0,1] crop1.5','augmentation_api':AUGMENTATION_API,
      'albumentations_version':A.__version__,'amp':use_amp}

def prediction_frame(frame,keys,y,z,threshold,keycol):
    scores=pad_score(z)
    scored=pd.DataFrame({keycol:keys,'pad_logit_score':scores,'pred_real':scores>=threshold,
                         'logit_0':z[:,0],'logit_1':z[:,1]})
    result=frame.merge(scored,on=keycol,how='left',validate='one_to_one',sort=False)
    valid=frame.usable_for_pad.astype(bool)
    if result.loc[valid,'pad_logit_score'].isna().any() or result.loc[~valid,'pad_logit_score'].notna().any():
        raise RuntimeError('Prediction accounting differs from frozen candidates')
    result['locked_threshold']=threshold
    return result

def evaluate_lcc(model,folder,locked):
    scored_predictions=[]
    for split in SPLITS:
        frame=lcc_frames[split]
        keys,y,z=infer(model,loader(LCCData(split)),True)
        expected=frame.loc[frame.usable_for_pad.astype(bool),'path'].astype(str).tolist()
        if keys!=expected:raise RuntimeError('LCC scored order differs: '+split)
        pred=prediction_frame(frame,keys,y,z,locked,'path').assign(lcc_split=split)
        mm=metrics(y,pad_score(z),locked,len(frame))
        write_json(folder/'metrics'/f'lcc_{split}_metrics.json',mm)
        write_json(folder/'metrics'/f'lcc_{split}_reference_metrics.json',reference_metrics(y,z,len(frame)))
        pred.to_csv(folder/'predictions'/f'lcc_{split}_predictions.csv',index=False)
        scored_predictions.append(pred)
    pooled=pd.concat(scored_predictions,ignore_index=True)
    if not pooled[['path','label','status','usable_for_pad','bbox_origin','lcc_split']].equals(
        lcc_frames['combined'][['path','label','status','usable_for_pad','bbox_origin','lcc_split']]):
        raise RuntimeError('Combined prediction candidates differ from 00d manifest')
    usable=pooled.usable_for_pad.astype(bool)
    mm=metrics(pooled.loc[usable,'label'],pooled.loc[usable,'pad_logit_score'],locked,len(pooled))
    write_json(folder/'metrics'/'lcc_combined_metrics.json',mm)
    write_json(folder/'metrics'/'lcc_combined_reference_metrics.json',reference_metrics(pooled.loc[usable,'label'],pooled.loc[usable,['logit_0','logit_1']].to_numpy(),len(pooled)))
    pooled.to_csv(folder/'predictions'/'lcc_combined_predictions.csv',index=False)

def save_final_source_evaluation(folder,keys,y,z,locked):
    mm=metrics(y,pad_score(z),locked,len(test))
    write_json(folder/'metrics'/'test_metrics.json',mm)
    write_json(folder/'metrics'/'test_reference_metrics.json',reference_metrics(y,z,len(test)))
    prediction_frame(test,keys,y,z,locked,'sample_key').to_csv(folder/'predictions'/'test_predictions.csv',index=False)

def run_one(name,spec):
    folder=out/'runs'/name;folder.mkdir(parents=True,exist_ok=True);(folder/'predictions').mkdir(exist_ok=True);(folder/'metrics').mkdir(exist_ok=True)
    cfg=run_config(name,spec);cfg_path=folder/'config.json'
    if cfg_path.is_file() and read_json(cfg_path)!=cfg:raise RuntimeError(name+' existing config differs')
    write_json(cfg_path,cfg)
    (folder/'manifests').mkdir(exist_ok=True)
    for filename in MANIFEST_SOURCES:shutil.copyfile(out/'manifests'/filename,folder/'manifests'/filename)
    best_path=folder/'best.pth';last_path=folder/'last_state.pth';done_path=folder/'completion.json'
    if done_path.is_file():
        needed=[folder/'metrics'/(k+'_metrics.json') for k in ('val','test','lcc_training','lcc_development','lcc_evaluation','lcc_combined')]
        if not all(p.is_file() for p in needed) or not best_path.is_file() or not (folder/'evaluation_freeze.json').is_file() or not all((folder/'metrics'/(s+'_reference_metrics.json')).is_file() for s in ('test','lcc_training','lcc_development','lcc_evaluation','lcc_combined')):
            raise RuntimeError(name+' incomplete completion outputs')
        print(name,'completed; skipping')
        return
    model,audit=init_model({'init':'pretrained','copied':True})
    if audit['initial_state_sha256']!=INITIAL_STATE_SHA:raise RuntimeError('Initial state differs')
    write_json(folder/'initialization_audit.json',audit)
    model=model.to(device)
    optimizer=torch.optim.SGD((p for p in model.parameters() if p.requires_grad),lr=.005,momentum=.9,weight_decay=5e-4)
    scheduler=torch.optim.lr_scheduler.MultiStepLR(optimizer,milestones=MILESTONES,gamma=GAMMA)
    scaler=torch.cuda.amp.GradScaler(enabled=use_amp)
    gain_rng=torch.Generator(device=device).manual_seed(GAIN_SEED)
    best_checkpoint=None
    history=[];diagnostics=[];best_acer=float('inf');best_auc=-float('inf');best_epoch=0;no_improve=0;start=1
    if last_path.is_file():
        if not RESUME:raise RuntimeError(name+' has a saved state; enable RESUME or use a new output root')
        state=torch.load(last_path,map_location='cpu',weights_only=False)
        if state.get('run_id')!=name or state.get('config')!=cfg:raise RuntimeError(name+' resume run/config differs')
        if state.get('initial_state_sha256')!=INITIAL_STATE_SHA:raise RuntimeError('Resume initial state differs')
        best_checkpoint=state['best_checkpoint']
        if state['best_epoch']:
            if best_checkpoint['run_id']!=name or best_checkpoint['epoch']!=state['best_epoch'] or best_checkpoint['config']!=cfg:raise RuntimeError('Resume best payload differs')
            save_torch(best_path,best_checkpoint)
        model.load_state_dict(state['model']);optimizer.load_state_dict(state['optimizer'])
        scheduler.load_state_dict(state['scheduler']);scaler.load_state_dict(state['scaler'])
        history=state['history'];diagnostics=state['diagnostics'];best_acer=state['best_acer']
        best_auc=state['best_auc'];best_epoch=state['best_epoch'];no_improve=state['no_improve']
        start=state['epoch']+1
        if len(history)!=state['epoch']:raise RuntimeError(name+' resume history length differs')
        restore_rng(state['rng'],gain_rng)
        print(name,'resume at epoch',start)
    val_dl=loader(CelebaData(val))
    masks=None  # CE-only: no FFT or worst-view selection
    if start<=MAX_EPOCHS and not (history and history[-1]['stop_reached']):
        for epoch in range(start,MAX_EPOCHS+1):
            expected_lr=.005 if epoch<=4 else (.001 if epoch<=8 else .0002)
            if not math.isclose(optimizer.param_groups[0]['lr'],expected_lr,rel_tol=1e-9):raise RuntimeError('Scheduler LR differs')
            warmup=epoch<=spec['warmup_epochs']
            active=not warmup
            model.train();totals=Counter();band_count=Counter();seen=0;harmful_count_total=0;harmful_ce_sum_total=0.;epoch_started=time.monotonic()
            train_ds=CelebaData(train,training=True,copied=True)
            train_dl=loader(train_ds,shuffle=True,epoch=epoch)
            print(f'[{name}] epoch {epoch}/{MAX_EPOCHS} starting, warmup={warmup}',flush=True)
            for step,(x,_,binary,spoof,lighting,attrs,_) in enumerate(train_dl,1):
                x=x.to(device,non_blocking=True);binary=binary.to(device);optimizer.zero_grad(set_to_none=True)
                loss,scalars,bands,harmful_ce_sum=training_terms(model,x,binary,spoof,lighting,attrs,
                    spec,masks,gain_rng,active)
                scaler.scale(loss).backward();scaler.step(optimizer);scaler.update()
                count=len(x);seen+=count
                for key,value in scalars.items():totals[key]+=value*count
                band_count.update(bands)
                harmful_count_total+=scalars['harmful_count'];harmful_ce_sum_total+=harmful_ce_sum
                if step==1 or step%LOG_EVERY_BATCHES==0 or step==len(train_dl):
                    print(f'[{name}] epoch {epoch} batch {step}/{len(train_dl)}, loss={totals["train_total_loss"]/seen:.4f}, elapsed={time.monotonic()-epoch_started:.1f}s',flush=True)
            keys,y,z=infer(model,val_dl)
            if keys!=val.sample_key.astype(str).tolist():raise RuntimeError('Val order differs')
            scores=pad_score(z);threshold=threshold_from_val(y,scores)
            vm=metrics(y,scores,threshold,len(test))
            improved=active and (vm['acer']<best_acer-METRIC_TIE_EPS or
                (abs(vm['acer']-best_acer)<=METRIC_TIE_EPS and vm['auc']>best_auc+METRIC_TIE_EPS))
            if active:
                if improved:
                    best_acer=vm['acer'];best_auc=vm['auc'];best_epoch=epoch;no_improve=0
                    best_checkpoint={'run_id':name,'epoch':epoch,'config':cfg,
                        'val_acer':best_acer,'val_auc':best_auc,
                        'state_dict':{k:v.detach().cpu().clone() for k,v in model.state_dict().items()}}
                    save_torch(best_path,best_checkpoint)
                no_improve=advance_patience(no_improve,improved,epoch,active)
            row={'epoch':epoch,'phase':'warmup' if warmup else 'active','lr':optimizer.param_groups[0]['lr'],
                 'eligible_for_final_checkpoint':active,'val_acer':vm['acer'],'val_auc':vm['auc'],
                 'val_eer':vm['eer'],'val_threshold':threshold,'best_epoch':best_epoch,
                 'no_improve_count':no_improve,'clean_ce_weight':1.0 if warmup else spec['clean_ce_weight'],
                 'spectral_ce_weight':0.0 if warmup else spec['spectral_ce_weight'],
                 'method':'CLEAN_WARMUP' if warmup else spec['method'],
                 **{k:v/seen for k,v in totals.items()},
                 **{f'{label}_count':band_count[i] for i,label in enumerate(('low','mid','high'))},
                 **{f'{label}_fraction':band_count[i]/seen for i,label in enumerate(('low','mid','high'))}}
            row['harmful_count']=harmful_count_total
            if spec['method']=='HARMFUL':
                row['harmful_ce_batch_mean']=row['harmful_ce']
                row['harmful_ce']=harmful_ce_sum_total/harmful_count_total if harmful_count_total else 0.
            if active and spec['method']!='CLEAN':diagnostics.append(dict(row))
            stop=epoch==MAX_EPOCHS or patience_stop_reached(epoch,no_improve)
            row['stop_reached']=stop;history.append(row)
            scheduler.step()
            state={'run_id':name,'config':cfg,'epoch':epoch,
                'model':{k:v.detach().cpu().clone() for k,v in model.state_dict().items()},
                'optimizer':optimizer.state_dict(),'scheduler':scheduler.state_dict(),
                'scaler':scaler.state_dict(),'best_epoch':best_epoch,'best_acer':best_acer,'best_auc':best_auc,
                'no_improve':no_improve,'initial_state_sha256':INITIAL_STATE_SHA,'rng':snapshot_rng(gain_rng),'best_checkpoint':best_checkpoint,
                'history':history,'diagnostics':diagnostics}
            save_torch(last_path,state)
            pd.DataFrame(history).to_csv(folder/'training_history.csv',index=False)
            if spec['method']!='CLEAN':pd.DataFrame(diagnostics).to_csv(folder/'spectral_diagnostics.csv',index=False)
            print(name,'epoch',epoch,'Full Test-as-Val ACER',vm['acer'],'best',best_epoch,'patience',no_improve,flush=True)
            if stop:break
    if not best_path.is_file() or best_epoch<=spec['warmup_epochs']:
        raise RuntimeError(name+' has no eligible best checkpoint')
    best=torch.load(best_path,map_location='cpu',weights_only=True)
    if best['run_id']!=name or best['config']!=cfg or best['epoch']!=best_epoch:
        raise RuntimeError(name+' best checkpoint identity differs')
    model.load_state_dict(best['state_dict']);model.eval()
    keys,y,z=infer(model,val_dl)
    if keys!=val.sample_key.astype(str).tolist():raise RuntimeError('Frozen Val order differs')
    locked=threshold_from_val(y,pad_score(z))
    vm=metrics(y,pad_score(z),locked,len(test))
    if abs(vm['acer']-best['val_acer'])>1e-6 or abs(vm['auc']-best['val_auc'])>1e-6:
        raise RuntimeError('Best checkpoint does not reproduce Val selection metrics')
    write_json(folder/'metrics'/'val_metrics.json',vm)
    save_final_source_evaluation(folder,keys,y,z,locked)
    freeze={'run_id':name,'best_epoch':best_epoch,'locked_threshold':locked,'selection_set':'Full official Test-as-Val','checkpoint_sha256':sha(best_path),'source_metrics':vm,'val_metrics':vm,'manifest_sha256':MANIFEST_HASHES,
      'train_crop_factor':1.5,'val_crop_factor':1.5,'test_crop_factor':1.5,'lcc_crop_factor':1.5}
    freeze_path=folder/'evaluation_freeze.json'
    if freeze_path.is_file() and read_json(freeze_path)!=freeze:raise RuntimeError('Evaluation freeze differs')
    write_json(freeze_path,freeze)
    evaluate_lcc(model,folder,locked)
    write_json(done_path,{'run_id':name,'best_epoch':best_epoch,'locked_threshold':locked,
                          'initial_state_sha256':INITIAL_STATE_SHA})
    del model
    torch.cuda.empty_cache()

def assert_fairness_contract(configs,initial_hashes):
    if set(configs)!=set(RUNS) or set(initial_hashes)!=set(RUNS):raise RuntimeError('Baseline run identity mismatch')
    for name,cfg in configs.items():
        if cfg['manifest_sha256']!=MANIFEST_HASHES or cfg['initial_state_sha256']!=initial_hashes[name]:raise RuntimeError('Manifest/initial state changed')
        if cfg['loss']!={'CE_clean':1.,'CE_worst':0.,'L_aux':0.} or cfg['spectral'] is not None:raise RuntimeError('CE-only objective changed')
        if any(cfg[k]!=1.5 for k in ('train_crop_factor','val_crop_factor','test_crop_factor','lcc_crop_factor')):raise RuntimeError('Crop mismatch')
    return True


def advance_patience(patience_counter,improved,epoch,eligible):
    # Checkpoint eligibility and improvement are determined before this rule.
    if improved or epoch<PATIENCE_START_EPOCH:return 0
    if not eligible:return patience_counter
    return patience_counter+1

def patience_stop_reached(epoch,patience_counter):
    return epoch>=PATIENCE_START_EPOCH and patience_counter>=EARLY_STOP_PATIENCE

def phase_patience_sanity_checks():
    for spec in RUNS.values():
        counter=0;stopped=None
        for epoch in range(1,MAX_EPOCHS+1):
            eligible=epoch>spec['warmup_epochs']
            counter=advance_patience(counter,False,epoch,eligible)
            if epoch<9:assert counter==0
            if patience_stop_reached(epoch,counter):stopped=epoch;break
        assert stopped==11
    counter=advance_patience(2,True,9,True)
    assert counter==0
    for epoch in (10,11,12):counter=advance_patience(counter,False,epoch,True)
    assert counter==3 and patience_stop_reached(12,counter)
    assert advance_patience(0,True,5,True)==0
    assert not patience_stop_reached(8,3)
    # Resuming committed epoch8 vs uninterrupted final-phase counts gives identical results.
    first=advance_patience(0,False,9,True);resumed=advance_patience(first,False,10,True)
    assert resumed==2 and advance_patience(resumed,False,11,True)==3
    return {'patience_start_epoch':9,'early_stop_patience':3,'earliest_possible_stop_epoch':11,
            'all_methods_identical':True,'improvement_resets_counter':True,'epoch_boundary_counter_replay':True,
            'best_selection_not_delayed':True}


def reference_metrics(y3,logits,candidate_n):
    y=(np.asarray(y3,dtype=int)!=0).astype(int)  # Reference 0=real, 1=attack.
    z=torch.as_tensor(np.asarray(logits));p=F.softmax(z,dim=-1)[:,1].cpu().numpy();pred=z.argmax(dim=1).cpu().numpy()
    real=y==0;attack=y==1
    if not real.any() or not attack.any():raise ValueError('Reference metrics need both classes')
    fpr,tpr,_=roc_curve(y,p,pos_label=1);idx=int(np.nanargmin(np.abs((1-tpr)-fpr)))
    apcer=float((pred[real]==1).mean());bpcer=float((pred[attack]==0).mean())
    return {'auc':float(roc_auc_score(y,p)),'eer':float(min(fpr[idx],1-tpr[idx])),
      'apcer':apcer,'bpcer':bpcer,'acer':.5*(apcer+bpcer),'global_argmax_accuracy':float((pred==y).mean()),
      'candidate_n':int(candidate_n),'scored_n':len(y),'coverage':len(y)/candidate_n,
      'convention':'Reference variable names: APCER=real->attack; BPCER=attack->real; argmax logits; ROC attack probability'}

GPU: Tesla T4 Full Train: 484561 Full Test-as-Val usable/candidate: 66379 67170 LCC: {'training': 8299, 'development': 2948, 'evaluation': 7580, 'combined': 18827}

## CE-only objective and training controls

Auxiliary modules retain historical initialization/state-dict compatibility, but are frozen and never forwarded. One clean forward per training batch. No warmup; checkpoint eligibility from epoch1.

In [4]:
# Lightweight objective/gradient checks before training. No dataset/model training.
assert_fairness_contract({name:run_config(name,spec) for name,spec in RUNS.items()},INITIAL_HASHES)
write_json(out/'phase_patience_checks.json',phase_patience_sanity_checks())
def check_ce_only_objective():
    class TinyPAD(nn.Module):
        def __init__(self):
            super().__init__();self.head=nn.Linear(3,2);self.calls=0
        def forward(self,x,aux=False):
            assert not aux,'Auxiliary forward must not be requested'
            self.calls+=1;return self.head(x)
    global use_amp
    old=use_amp;use_amp=False
    try:
        model=TinyPAD();x=torch.tensor([[.1,.2,.3],[.6,.4,.2]]);y=torch.tensor([0,1])
        expected=F.cross_entropy(model(x),y);expected_grad=torch.autograd.grad(expected,model.head.weight)[0]
        model.calls=0
        loss,diagnostics,_,_=training_terms(model,x,y,None,None,None,RUNS['CE_CLEAN_FULL_crop15'],None,None,True)
        actual_grad=torch.autograd.grad(loss,model.head.weight)[0]
        assert model.calls==1 and torch.allclose(actual_grad,expected_grad)
        assert diagnostics['aux_loss']==diagnostics['spectral_ce']==0.
    finally:use_amp=old
    return {'single_clean_forward':True,'gradient_equals_binary_ce':True,'auxiliary_loss':0.,'spectral_loss':0.}
write_json(out/'ce_only_checks.json',check_ce_only_objective())
print('CE-only objective and phase-aware patience checks passed',flush=True)

CE-only objective and phase-aware patience checks passed

/tmp/ipykernel_23/1895080082.py:312: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

## CASIA evaluation

This function embeds notebook20 preprocessing, coverage, aggregation and train-only calibration. It uses the new best checkpoint and isolates target manifests from source training state.

In [5]:
def evaluate_casia(model,folder,name,locked,best_epoch):
    OUTPUT_ROOT=folder/'casia';OUTPUT_ROOT.mkdir(parents=True,exist_ok=True)
    CASIA=Path(CASIA_ROOT);detector_path=Path(SCRFD_MODEL_PATH)
    SELECTED_RUNS=[name];SEED=TRAIN_SEED
    LABELS={name:'CE-clean only (full-scale)'}
    casia_info={'run_id':name,'scale':'full-scale','best_epoch':best_epoch,'threshold':locked,
                'amp':use_amp,'loss':'CE_clean only','crop_factor':1.5}
    provenance=[casia_info]
    # Full train/test-color manifests, validated explicit filename labels; no frame subsampling.
    EXPECTED_CODES={'1':(0,'real','low'),'2':(0,'real','normal'),'HR_1':(0,'real','high'),
     '3':(1,'warped','low'),'4':(1,'warped','normal'),'HR_2':(1,'warped','high'),
     '5':(1,'cut','low'),'6':(1,'cut','normal'),'HR_3':(1,'cut','high'),
     '7':(1,'replay','low'),'8':(1,'replay','normal'),'HR_4':(1,'replay','high')}
    FILENAME_RE=re.compile(r'^(?P<subject>\d+)_(?P<code>HR_[1-4]|[1-8])\.avi_(?P<frame>\d+)_(?P<label>real|fake)\.jpg$',re.I)
    def read_split(folder):
        output=[]
        for path in sorted(folder.iterdir()):
            if path.name.startswith('.'):continue
            match=FILENAME_RE.fullmatch(path.name)
            if not path.is_file() or not match:raise ValueError('Unexpected CASIA filename: '+str(path))
            g=match.groupdict();code=g['code'].upper();label,attack,quality=EXPECTED_CODES[code]
            if g['label'].lower()!=('real' if label==0 else 'fake'):raise ValueError('Filename label/code conflict: '+str(path))
            output.append({'subject_id':int(g['subject']),'video_code':code,'video_id':f'{int(g["subject"])}_{code}.avi',
                           'frame_index':int(g['frame']),'image_path':str(path),'binary_label':label,
                           'attack_type':attack,'quality':quality})
        frame=pd.DataFrame(output)
        if frame.empty or frame.duplicated(['video_id','frame_index']).any():raise ValueError('Empty/duplicate manifest: '+str(folder))
        return frame.sort_values(['subject_id','video_id','frame_index']).reset_index(drop=True)
    # ID collision checks use explicit labels, never PAD scores or detection results.
    train_names=read_split(CASIA/'train_img/train_img/color').assign(split='train')
    test_names=read_split(CASIA/'test_img/test_img/color').assign(split='test')
    frame_manifest=pd.concat([train_names,test_names],ignore_index=True)
    for vid,group in frame_manifest.groupby('video_id'):
        if len(group[['subject_id','video_code','binary_label','attack_type','quality']].drop_duplicates())!=1:
            raise ValueError('Inconsistent video labels across splits: '+vid)
    def combined_unique(frame):
        # Stable train then test ordering; test takes precedence independently of detection success.
        ordered=pd.concat([frame.loc[frame.split=='train'],frame.loc[frame.split=='test']],ignore_index=True)
        result=ordered.drop_duplicates(['video_id','frame_index'],keep='last').copy()
        result['source_split']=result['split']
        result['split']='combined'
        return result.sort_values(['subject_id','video_id','frame_index']).reset_index(drop=True)
    combined_manifest=combined_unique(frame_manifest)
    POOLS=['train','test','combined']
    pool_manifests={'train':train_names,'test':test_names,'combined':combined_manifest}
    def video_manifest(frame):
        return frame.groupby(['split','video_id'],sort=True).agg(subject_id=('subject_id','first'),
          video_code=('video_code','first'),binary_label=('binary_label','first'),
          attack_type=('attack_type','first'),quality=('quality','first'),candidate_frames=('frame_index','size')).reset_index()
    videos=pd.concat([video_manifest(pool_manifests[split]) for split in POOLS],ignore_index=True)
    for split,frame in pool_manifests.items():
        if set(frame.binary_label)!={0,1}:raise ValueError('Real and Attack required in '+split)
        frame.to_csv(OUTPUT_ROOT/f'casia_{split}_frame_manifest.csv',index=False)
    frame_manifest.to_csv(OUTPUT_ROOT/'casia_frame_manifest.csv',index=False)
    videos.to_csv(OUTPUT_ROOT/'casia_video_manifest.csv',index=False)
    overlap={'subjects':sorted(set(test_names.subject_id)&set(train_names.subject_id)),
             'video_ids':len(set(test_names.video_id)&set(train_names.video_id)),
             'frame_ids':len(set(zip(test_names.video_id,test_names.frame_index))&set(zip(train_names.video_id,train_names.frame_index)))}
    populations={split:{'candidate_frames':len(pool_manifests[split]),
                        'candidate_videos':int((videos.split==split).sum())} for split in POOLS}
    protocol={'dataset':'CASIA-FASD Kaggle extracted-image train + test evaluation (minhnh2107/casiafasd)',
     'official_subject_disjoint_protocol_verified':False,'splits':['train_img/train_img/color','test_img/test_img/color'],
     'train_test_copy_overlap':overlap,'frame_sampling':'none; all available train and test color JPEGs',
     'raw_train_test_frames':len(frame_manifest),'populations':populations,
     'combined_policy':'unique (video_id,frame_index); prefer test copy before detection; no duplicate weighting','selected_runs':SELECTED_RUNS,
     'detector':'SCRFD-500M','detector_path':str(detector_path),'detector_sizes':DETECTOR_SIZES,
     'detector_confidence':DETECTOR_CONFIDENCE,'face_selection':'largest positive finite bbox; confidence tie-break',
     'crop_factor':CROP_SCALE,'input_size':INPUT_SIZE,'color_order':'BGR','input_range':'[0,1]',
     'score':'logit(real)-logit(attack)','primary_unit':'reconstructed video; mean valid-frame score',
     'min_valid_frames':MIN_VALID_FRAMES,'secondary_unit':'all successfully localized frames in the specified pool',
     'threshold_policy':'source-frozen baseline plus CASIA train-calibrated frame/video thresholds' if CALIBRATE_CASIA_THRESHOLD else 'source-frozen only',
     'eer_policy':'descriptive ROC EER only; its target threshold is never used for predictions',
     'target_training':False,'target_adaptation':False,'target_threshold_calibration':CALIBRATE_CASIA_THRESHOLD,
     'threshold_fit_split':'train only' if CALIBRATE_CASIA_THRESHOLD else None,
     'threshold_objective':'minimum pooled binary ACER/HTER; ties closest to source threshold',
     'full_scale_source_selection':'CelebA Test-as-Val, as in experiment18',
     'inference_precision':'per-run original AMP setting; logits converted to float32 before subtraction',
     'seed':SEED,'batch_size':BATCH_SIZE,'torch_version':torch.__version__,'ort_version':ort.__version__}
    write_json(OUTPUT_ROOT/'evaluation_protocol.json',protocol)
    print('Candidate populations:',populations,flush=True)
    print('Train/test image-copy overlap:',overlap,flush=True)
    display(videos.groupby(['split','binary_label','attack_type','quality']).size().rename('videos').reset_index())

    # Localize once and cache crops in RAM. Every selected model receives identical tensors.
    # Repeat this cell only to rebuild detection; no target bbox/GT fallback is used.
    detector=model_zoo.get_model(str(detector_path),providers=['CUDAExecutionProvider','CPUExecutionProvider'])
    if detector is None:raise RuntimeError('Could not load SCRFD-500M')
    detector.prepare(ctx_id=0,input_size=DETECTOR_SIZES[0],det_thresh=DETECTOR_CONFIDENCE)
    active=detector.session.get_providers()
    # CPU provider may handle shape operations; CUDA must actually be active.
    if 'CUDAExecutionProvider' not in active:raise RuntimeError('SCRFD CUDA failed to load; active providers: '+str(active))
    print('SCRFD active providers:',active,flush=True)
    def detect_boxes(image,size):
        try:return detector.detect(image,input_size=size,max_num=0,metric='default')[0]
        except TypeError:
            previous=detector.input_size;detector.input_size=size
            try:return detector.detect(image,max_num=0,metric='default')[0]
            finally:detector.input_size=previous
    patches=[];records=[];started=time.monotonic()
    print('[Detection] Starting shared full train/test localization',flush=True)
    for i,row in enumerate(frame_manifest.to_dict('records')):
        rec=dict(row,decoded=False,detected=False,crop_index=-1,bbox_xyxy='',confidence=None,detector_size=None,failure_reason='')
        image=cv2.imread(row['image_path'],cv2.IMREAD_COLOR)
        if image is None:rec['failure_reason']='decode_failed'
        else:
            rec['decoded']=True
            try:
                for size in DETECTOR_SIZES:
                    boxes=detect_boxes(image,size)
                    if boxes is None:continue
                    boxes=[b for b in boxes if len(b)>=5 and np.isfinite(b[:5]).all() and b[2]>b[0] and b[3]>b[1] and b[4]>=DETECTOR_CONFIDENCE]
                    if not boxes:continue
                    box=max(boxes,key=lambda b:((float(b[2])-float(b[0]))*(float(b[3])-float(b[1])),float(b[4])))
                    patch=mini_crop_bgr(image,box[:4])
                    rec.update(detected=True,crop_index=len(patches),bbox_xyxy=json.dumps([float(v) for v in box[:4]]),
                               confidence=float(box[4]),detector_size=size[0])
                    patches.append(patch);break
                if not rec['detected']:rec['failure_reason']='scrfd_no_face'
            except Exception as exc:rec['failure_reason']=f'{type(exc).__name__}: {exc}'
        records.append(rec)
        if i==0 or (i+1)%DETECTION_LOG_EVERY==0 or i+1==len(frame_manifest):
            print(f'[Detection] {i+1}/{len(frame_manifest)} frames; valid={len(patches)}; elapsed={time.monotonic()-started:.1f}s',flush=True)
        if (i+1)%DETECTION_LOG_EVERY==0:pd.DataFrame(records).to_csv(OUTPUT_ROOT/'casia_frame_detection.partial.csv',index=False)
    detection=pd.DataFrame(records);detection.to_csv(OUTPUT_ROOT/'casia_frame_detection.csv',index=False)
    if not patches:raise RuntimeError('No valid face crops; inspect casia_frame_detection.csv')
    CROPS=np.stack(patches);del patches
    valid=detection.loc[detection.detected].copy().reset_index(drop=True)
    assert valid.crop_index.tolist()==list(range(len(CROPS)))
    np.save(OUTPUT_ROOT/'shared_crops_bgr_uint8.npy',CROPS)
    # Pooled rows are fixed by the pre-detection manifest policy, including failed test copies.
    pool_detection={'train':detection.loc[detection.split=='train'].copy(),
                    'test':detection.loc[detection.split=='test'].copy(),
                    'combined':combined_unique(detection)}
    combined_rows=pool_detection['combined']
    assert combined_rows.image_path.tolist()==combined_manifest.image_path.tolist()
    combined_rows.to_csv(OUTPUT_ROOT/'casia_combined_frame_detection.csv',index=False)
    coverages=[]
    for split in POOLS:
        frame=pool_detection[split]
        cov=frame.groupby(['split','video_id'],sort=True).agg(decoded_frames=('decoded','sum'),valid_frames=('detected','sum')).reset_index()
        cov=videos.loc[videos.split==split].merge(cov,on=['split','video_id'],validate='one_to_one')
        cov['scorable']=cov.valid_frames>=MIN_VALID_FRAMES
        cov['detection_coverage']=cov.valid_frames/cov.candidate_frames
        coverages.append(cov)
    coverage=pd.concat(coverages,ignore_index=True)
    coverage.to_csv(OUTPUT_ROOT/'casia_video_coverage.csv',index=False)
    valid.groupby(['split','binary_label','attack_type','quality']).size().rename('valid_frames').reset_index().to_csv(OUTPUT_ROOT/'valid_frames_by_group.csv',index=False)
    protocol['detector_active_providers']=active
    write_json(OUTPUT_ROOT/'evaluation_protocol.json',protocol)
    print(f'[Detection complete] {len(valid)}/{len(frame_manifest)} raw train/test frames',flush=True)
    display(coverage.groupby('split').agg(candidate_videos=('video_id','size'),scorable_videos=('scorable','sum'),candidate_frames=('candidate_frames','sum'),valid_frames=('valid_frames','sum')).reset_index())
    display(detection.failure_reason.value_counts())
    del detector;gc.collect();torch.cuda.empty_cache()

    # Frozen checkpoint inference, one model at a time. Progress printed immediately and per batch.
    def safe_metrics(labels,scores,threshold,candidate_n):
        if len(labels)==0 or set(np.asarray(labels)==0)!={False,True}:
            y=np.asarray(labels);pred=np.asarray(scores)>=threshold;real=y==0;attack=y!=0
            return dict(auc=None,eer=None,tpr_at_fpr_1pct=None,
                        apcer=float(pred[attack].mean()) if attack.any() else None,
                        bpcer=float((~pred[real]).mean()) if real.any() else None,acer=None,hter=None,
                        binary_accuracy=float((pred==real).mean()) if len(y) else None,
                        locked_source_threshold=float(threshold),candidate_n=int(candidate_n),
                        scored_n=len(labels),detector_coverage=len(labels)/candidate_n if candidate_n else 0)
        return metrics(labels,scores,threshold,candidate_n)
    summary=[];all_frame_predictions=[];all_video_predictions=[];subgroup_rows=[]
    for run_id in SELECTED_RUNS:
        info=casia_info;model=model.to(device);threshold=info['threshold']
        run_output=OUTPUT_ROOT;run_output.mkdir(parents=True,exist_ok=True)
        started=time.monotonic();chunks=[];num_batches=math.ceil(len(CROPS)/BATCH_SIZE)
        print(f'\n[Inference] {run_id}: {len(CROPS)} shared crops, {num_batches} batches; threshold={threshold}',flush=True)
        with torch.inference_mode():
            for batch_no,start in enumerate(range(0,len(CROPS),BATCH_SIZE),1):
                arr=np.ascontiguousarray(CROPS[start:start+BATCH_SIZE].transpose(0,3,1,2))
                x=torch.from_numpy(arr).to(device=device,dtype=torch.float32).div_(255.)
                with torch.autocast(device_type='cuda',dtype=torch.float16,enabled=info['amp']):z=model(x)
                z=z.float().cpu().numpy()
                if z.shape!=(len(arr),2) or not np.isfinite(z).all():raise ValueError('Nonfinite / nonbinary model logits: '+run_id)
                chunks.append(z)
                if batch_no==1 or batch_no%LOG_EVERY_BATCHES==0 or batch_no==num_batches:
                    print(f'[Inference] {run_id} batch {batch_no}/{num_batches}; elapsed={time.monotonic()-started:.1f}s',flush=True)
        logits=np.concatenate(chunks)
        fp=valid[['split','subject_id','video_id','video_code','frame_index','image_path','binary_label','attack_type','quality']].copy()
        fp['run_id']=run_id;fp['logit_real']=logits[:,0];fp['logit_attack']=logits[:,1]
        fp['pad_score']=logits[:,0]-logits[:,1];fp['threshold']=threshold
        fp['predicted_real']=fp.pad_score>=threshold
        fp.to_csv(run_output/'frame_predictions.csv',index=False)
        all_frame_predictions.append(fp)
        write_json(run_output/'config.json',info|{'training':False,'pools':POOLS})
        for split in POOLS:
            # Reindex predictions to candidate rows chosen BEFORE detection. No fallback to a train
            # duplicate when its preferred test copy failed; this prevents outcome-based selection.
            candidates=pool_detection[split]
            chosen=candidates.loc[candidates.detected].copy()
            columns=['image_path','logit_real','logit_attack','pad_score','threshold','predicted_real']
            sf=chosen.merge(fp[columns],on='image_path',how='left',validate='one_to_one')
            if sf.pad_score.isna().any():raise ValueError('Missing predictions in '+split)
            means=sf.groupby('video_id',sort=True).agg(video_score=('pad_score','mean')).reset_index()
            cv=coverage.loc[coverage.split==split].copy()
            vp=cv.merge(means,on='video_id',how='left',validate='one_to_one')
            vp['run_id']=run_id;vp['threshold']=threshold
            vp['predicted_real']=pd.Series(pd.NA,index=vp.index,dtype='boolean')
            vp.loc[vp.scorable,'predicted_real']=(vp.loc[vp.scorable,'video_score']>=threshold).to_numpy()
            scored=vp.loc[vp.scorable]
            video_metrics=safe_metrics(scored.binary_label.to_numpy(),scored.video_score.to_numpy(),threshold,len(cv))
            frame_metrics=safe_metrics(sf.binary_label.to_numpy(),sf.pad_score.to_numpy(),threshold,len(candidates))
            split_output=run_output/split;split_output.mkdir(exist_ok=True)
            sf.to_csv(split_output/'frame_predictions.csv',index=False);vp.to_csv(split_output/'video_predictions.csv',index=False)
            write_json(split_output/'video_metrics.json',video_metrics);write_json(split_output/'frame_metrics.json',frame_metrics)
            summary.append(info|{'split':split}|video_metrics|{'frame_'+k:v for k,v in frame_metrics.items()})
            all_video_predictions.append(vp)
            for group_col in ['attack_type','quality']:
                for group,df in scored.groupby(group_col):
                    subgroup_rows.append({'run_id':run_id,'split':split,'group_by':group_col,'group':group,
                      **safe_metrics(df.binary_label.to_numpy(),df.video_score.to_numpy(),threshold,int((cv[group_col]==group).sum()))})
            print(f'[Result] {run_id} / {split}: video AUC={video_metrics["auc"]}, HTER={video_metrics["hter"]}, frame AUC={frame_metrics["auc"]}',flush=True)
        # Save summaries after every completed run so interruption preserves completed results.
        pd.DataFrame(summary).to_csv(OUTPUT_ROOT/'comparison_summary.csv',index=False)
        write_json(OUTPUT_ROOT/'comparison_summary.json',summary)
        write_json(run_output/'completion.json',{'run_id':run_id,'status':'completed','elapsed_seconds':time.monotonic()-started})
        print(f'[Done] {run_id}: train / test / combined saved',flush=True)
        del model,logits,chunks,x,z;gc.collect();torch.cuda.empty_cache()
    frame_predictions=pd.concat(all_frame_predictions,ignore_index=True)
    video_predictions=pd.concat(all_video_predictions,ignore_index=True)
    # All model comparisons are paired on exactly the same ordered localized frames/videos.
    keys=[df.image_path.tolist() for df in all_frame_predictions]
    assert all(k==keys[0] for k in keys)
    frame_predictions.to_csv(OUTPUT_ROOT/'all_frame_predictions.csv',index=False)
    video_predictions.to_csv(OUTPUT_ROOT/'all_video_predictions.csv',index=False)
    pd.DataFrame(subgroup_rows).to_csv(OUTPUT_ROOT/'video_subgroup_metrics.csv',index=False)
    comparison=pd.DataFrame(summary)
    display(comparison[['run_id','split','best_epoch','locked_source_threshold','auc','eer','apcer','bpcer','acer','hter','binary_accuracy','tpr_at_fpr_1pct','scored_n','candidate_n','frame_auc','frame_acer']])

    def optimize_casia_threshold(labels, scores, source_threshold):
        y = np.asarray(labels, dtype=int)
        s = np.asarray(scores, dtype=float)
        if y.ndim != 1 or s.ndim != 1 or len(y) != len(s):
            raise ValueError('Labels and scores must be matching one-dimensional arrays')
        if not np.isfinite(s).all() or not np.isfinite(source_threshold) or not set(y).issubset({0, 1}):
            raise ValueError('Invalid CASIA scores, labels or source threshold')
        if not len(y) or set(y) != {0, 1}:
            return None, pd.DataFrame()
        # Every distinct >= decision is considered, including accepting nobody.
        thresholds = np.unique(np.r_[s, np.nextafter(s.max(), np.inf), float(source_threshold)])
        real_scores = np.sort(s[y == 0])
        attack_scores = np.sort(s[y == 1])
        bpcer = np.searchsorted(real_scores, thresholds, side='left') / len(real_scores)
        apcer = 1 - np.searchsorted(attack_scores, thresholds, side='left') / len(attack_scores)
        hter = (apcer + bpcer) / 2
        candidates = np.flatnonzero(np.isclose(hter, hter.min(), rtol=0, atol=1e-12))
        best = min(candidates, key=lambda i: (abs(thresholds[i] - source_threshold), thresholds[i]))
        curve = pd.DataFrame({'threshold': thresholds, 'apcer': apcer, 'bpcer': bpcer,
                              'acer': hter, 'hter': hter})
        return float(thresholds[best]), curve

    # Reuse predictions; never repeat model inference or fit on test/combined.
    calibrated_rows = []
    if CALIBRATE_CASIA_THRESHOLD:
        for run_id in SELECTED_RUNS:
            run_output = OUTPUT_ROOT
            source_threshold = float(next(r for r in summary if r['run_id'] == run_id)['locked_source_threshold'])
            for unit, score_column in [('frame', 'pad_score'), ('video', 'video_score')]:
                train = pd.read_csv(run_output / 'train' / f'{unit}_predictions.csv')
                if unit == 'video':
                    train = train.loc[train.scorable]
                threshold, curve = optimize_casia_threshold(train.binary_label.to_numpy(), train[score_column].to_numpy(), source_threshold)
                calibration = {'run_id': run_id, 'unit': unit, 'fit_split': 'train',
                               'fit_n': len(train), 'source_threshold': source_threshold,
                               'casia_calibrated_threshold': threshold,
                               'objective': 'minimum pooled binary ACER/HTER',
                               'tie_break': 'closest to source threshold',
                               'train_test_copy_overlap': overlap,
                               'status': 'calibrated' if threshold is not None else 'undefined: both train classes required'}
                write_json(run_output / f'{unit}_casia_calibration.json', calibration)
                if threshold is not None:
                    curve.to_csv(run_output / f'{unit}_casia_train_threshold_curve.csv', index=False)
                for split in POOLS:
                    split_output = run_output / split
                    predictions = pd.read_csv(split_output / f'{unit}_predictions.csv')
                    eligible = predictions if unit == 'frame' else predictions.loc[predictions.scorable]
                    candidate_n = populations[split]['candidate_frames' if unit == 'frame' else 'candidate_videos']
                    baseline = safe_metrics(eligible.binary_label.to_numpy(), eligible[score_column].to_numpy(), source_threshold, candidate_n)
                    row = calibration | {'split': split, 'source_acer': baseline['acer'], 'source_hter': baseline['hter'],
                          'evaluation_policy': 'CASIA train threshold transferred unchanged; no test/combined fitting'}
                    if threshold is not None:
                        tuned = safe_metrics(eligible.binary_label.to_numpy(), eligible[score_column].to_numpy(), threshold, candidate_n)
                        tuned.pop('locked_source_threshold')
                        row.update(tuned)
                        row['acer_reduction'] = baseline['acer'] - tuned['acer'] if tuned['acer'] is not None else None
                        row['hter_reduction'] = row['acer_reduction']
                        predictions['source_threshold'] = source_threshold
                        predictions['threshold'] = threshold
                        predictions['threshold_fit_split'] = 'train'
                        predictions['predicted_real'] = pd.Series(pd.NA, index=predictions.index, dtype='boolean')
                        mask = predictions[score_column].notna()
                        if unit == 'video': mask &= predictions.scorable
                        predictions.loc[mask, 'predicted_real'] = (predictions.loc[mask, score_column] >= threshold).to_numpy()
                        predictions.to_csv(split_output / f'{unit}_predictions_casia_calibrated.csv', index=False)
                    else:
                        row.update({'acer': None, 'hter': None, 'apcer': None, 'bpcer': None, 'acer_reduction': None, 'hter_reduction': None})
                    write_json(split_output / f'{unit}_metrics_casia_calibrated.json', row)
                    calibrated_rows.append(row)
        calibrated_comparison = pd.DataFrame(calibrated_rows)
        calibrated_comparison.to_csv(OUTPUT_ROOT / 'casia_calibrated_threshold_summary.csv', index=False)
        write_json(OUTPUT_ROOT / 'casia_calibrated_threshold_summary.json', calibrated_rows)
        print('CASIA train-calibrated thresholds transferred unchanged to test/combined:', flush=True)
        display(calibrated_comparison[['run_id', 'split', 'unit', 'source_threshold', 'casia_calibrated_threshold',
                                     'source_acer', 'acer', 'source_hter', 'hter', 'apcer', 'bpcer']])
    else:
        print('CASIA calibration disabled; source-frozen results only.', flush=True)

    # Report, ROC figures, and downloadable ZIP. Source-frozen baseline and optional train-calibrated operating points.
    for scale in ['100K','full-scale']:
        ids=[info['run_id'] for info in provenance if info['scale']==scale]
        if not ids:continue
        for split in POOLS:
            fig,ax=plt.subplots(figsize=(7,6))
            for run_id in ids:
                df=video_predictions.loc[(video_predictions.run_id==run_id)&(video_predictions.split==split)&video_predictions.scorable]
                if set(df.binary_label)!={0,1}:continue
                fpr,tpr,_=roc_curve((df.binary_label==0).astype(int),df.video_score)
                ax.plot(fpr,tpr,label=LABELS[run_id])
            ax.plot([0,1],[0,1],'k--',alpha=.5)
            ax.set(xlabel='Attack acceptance rate (FPR)',ylabel='Real acceptance rate (TPR)',title=f'CASIA Kaggle image copy — {scale} / {split}, video ROC')
            handles,_=ax.get_legend_handles_labels()
            if handles:ax.legend()
            fig.tight_layout();fig.savefig(OUTPUT_ROOT/f'roc_video_{scale}_{split}.png',dpi=200);plt.close(fig)
    lines=['# CASIA-FASD Kaggle train/test image-copy evaluation','',
     'No CASIA weight training, adaptation or checkpoint selection. Optional thresholds are fitted only on train, then transferred unchanged to test and combined.', '',
     'All available train and test color JPEGs were attempted; detection/crop failures remain in coverage CSVs. No GT/full-image bbox fallback.',
     'The six checkpoints share the same ordered SCRFD detections, crop1.5 and 80×80 BGR tensors. Spectral views and auxiliary heads are training-only.', '',
     '## Dataset and metric units','',
     f'Raw train/test candidate frames: {len(frame_manifest)}; valid raw frames: {len(valid)}. Populations: {populations}.',
     'Train and test are evaluated separately. Combined is the unique union of reconstructed frame IDs, preferring test copies before detection; it does not count overlapping frame IDs twice.',
     'Combined merges unique frames of the same reconstructed video and averages their valid-frame scores. The two split-wise video rows are not averaged or counted twice.',
     f'Primary metrics: mean valid-frame binary-logit score per reconstructed video; at least {MIN_VALID_FRAMES} valid frames. Secondary metrics: all valid frames.',
     'The frozen source threshold is transferred unchanged to both units; video aggregation may change score distributions. Optional frame/video thresholds are calibrated separately on train.',
     'AUC/EER/TPR@FPR1% describe the ROC. Baseline APCER/BPCER/ACER/HTER/accuracy use the frozen source threshold. EER does not set the prediction threshold.',
     'Metrics are fractions (multiply by 100 for percentages); ACER = HTER = (APCER+BPCER)/2 for the pooled binary attack class.',
     'AUC/EER/ACER/HTER need both classes; single-class subsets still report their applicable APCER or BPCER and accuracy. Undefined metrics remain null.', '',
     '## Limitations','',
     'These are extracted-image Kaggle train and test splits, not a verified official subject-disjoint CASIA benchmark. No original full-video evaluation is claimed.',
     'Filename real/fake labels are cross-checked against video-code mapping from the prior CASIA exploration. No label is guessed from a split folder.',
     f'Train/test image-copy overlap audit: {overlap}. Models were trained on CelebA, not on the CASIA train images.',
     'Face selection is heuristic: largest positive finite SCRFD box, confidence tie-break. Raw bbox records and failures are exported.',
     '100K source selection/calibration: Val15K. Full-scale source selection/calibration: official CelebA Test-as-Val (reused source selection set). Scale groups remain separate.',
     'No statistical significance or best-model selection on CASIA is claimed.', '',
     '## Source-frozen baseline: selected runs and metrics','']
    columns=['run_id','split','auc','eer','apcer','bpcer','acer','hter','binary_accuracy','scored_n','candidate_n','frame_auc','frame_acer']
    lines += ['| '+' | '.join(columns)+' |','| '+' | '.join(['---']*len(columns))+' |']
    for row in summary:
        values=[str(row[c]) if row[c] is not None else 'undefined' for c in columns]
        lines.append('| '+' | '.join(values)+' |')
    lines += ['', 'Source provenance and thresholds: `model_provenance.json`; effective settings: `evaluation_protocol.json`.',
              'Frame/video predictions and metrics: `<train|test|combined>/`.',
              'Use comparison_summary.csv/json to merge independent RUN_FILTER notebooks. Check evaluation protocol and coverage match before merging.','']
    if CALIBRATE_CASIA_THRESHOLD:
        lines += ['', '## CASIA train-calibrated thresholds', '',
                  'Separate frame/video thresholds minimize ACER = HTER on train scores only; ties prefer the source threshold. Real is accepted iff score >= threshold.',
                  'Exactly the same fitted threshold is applied to train, test and combined. Test/combined labels are never used to choose it; no extra inference is performed.',
                  'Train metrics are fitted-set diagnostics; combined includes calibration data. Train/test identity overlap means this Kaggle test is not confirmed independent validation.',
                  'AUC/EER are unchanged. Lower test/combined ACER or HTER is not guaranteed. These thresholds require held-out webcam validation before deployment.', '']
        calibrated_columns = ['run_id', 'split', 'unit', 'source_threshold', 'casia_calibrated_threshold',
                              'source_acer', 'acer', 'source_hter', 'hter', 'apcer', 'bpcer']
        lines += ['| ' + ' | '.join(calibrated_columns) + ' |', '| ' + ' | '.join(['---'] * len(calibrated_columns)) + ' |']
        for row in calibrated_rows:
            lines.append('| ' + ' | '.join(str(row.get(c)) if row.get(c) is not None else 'undefined' for c in calibrated_columns) + ' |')
        lines += ['', 'Exports: `casia_calibrated_threshold_summary.csv/json`; per-run frame/video calibration JSON and train threshold curves; per-split `*_metrics_casia_calibrated.json` and `*_predictions_casia_calibrated.csv`.',
                  'Original source-frozen summaries, predictions and metrics are retained. Runtime configs are not overwritten.', '']
    else:
        lines += ['', 'CASIA threshold calibration disabled; source-frozen results only.', '']
    (OUTPUT_ROOT/'casia_train_test_evaluation_report.md').write_text('\n'.join(lines))
    archive_path=OUTPUT_ROOT.with_suffix('.zip')
    with zipfile.ZipFile(archive_path,'w',compression=zipfile.ZIP_DEFLATED) as archive:
        for path in sorted(OUTPUT_ROOT.rglob('*')):
            if path.is_file() and path.name!='shared_crops_bgr_uint8.npy' and not path.name.endswith('.partial.csv'):
                archive.write(path,arcname=path.relative_to(OUTPUT_ROOT))
    print('Saved report and ZIP:',archive_path,flush=True)
    print('Shared crop cache is excluded from the ZIP; raw detection/crop metadata is included.')
    display(FileLink(str(archive_path)))

    return summary,calibrated_rows

In [6]:
SCORE_SPLITS=('test','lcc_training','lcc_development','lcc_evaluation','lcc_combined')
EVALUATION_PROTOCOL={'objective':{'CE_clean':1.,'CE_worst':0.,'L_aux':0.},
 'train':'full eligible official CelebA Train','selection':'full official CelebA Test-as-Val; reused, not independent Test',
 'max_epochs':12,'milestones':[4,8],'patience_start_epoch':9,'early_stop_patience':3,
 'lcc':'full training/development/evaluation/combined; source threshold, no target fitting',
 'casia':'all extracted train/test color frames + deduplicated combined; notebook20 preprocessing',
 'casia_calibration':'train only, separate frame/video thresholds' if CALIBRATE_CASIA_THRESHOLD else 'disabled',
 'seed':TRAIN_SEED,'crop_factor':1.5,'comparison':'CE-only vs historical C (CE_clean + L_aux) and P3/R7; descriptive one-seed'}
write_json(out/'evaluation_protocol.json',EVALUATION_PROTOCOL)
def export_summary():
    rows=[]
    for name in RUNS:
        folder=out/'runs'/name
        if not (folder/'completion.json').exists():continue
        epoch=read_json(folder/'completion.json')['best_epoch']
        for split in SCORE_SPLITS:
            rows.append({'run_id':name,'dataset':split,'unit':'frame','selected_epoch':epoch,
                         'threshold_policy':'source-calibrated',**read_json(folder/'metrics'/f'{split}_metrics.json')})
        casia=folder/'casia'
        if (casia/'comparison_summary.json').exists():
            for row in read_json(casia/'comparison_summary.json'):
                rows.append({'run_id':name,'dataset':'casia_'+row['split'],'unit':'video','selected_epoch':epoch,
                             'threshold_policy':'source-calibrated',**{k:v for k,v in row.items() if not k.startswith('frame_')}})
                rows.append({'run_id':name,'dataset':'casia_'+row['split'],'unit':'frame','selected_epoch':epoch,
                             'threshold_policy':'source-calibrated',**{k[6:]:v for k,v in row.items() if k.startswith('frame_')}})
        if (casia/'casia_calibrated_threshold_summary.json').exists() and CALIBRATE_CASIA_THRESHOLD:
            for row in read_json(casia/'casia_calibrated_threshold_summary.json'):
                rows.append(row|{'dataset':'casia_'+row['split'],'selected_epoch':epoch,'threshold_policy':'CASIA train-calibrated'})
    pd.DataFrame(rows).to_csv(out/'comparison_summary.csv',index=False)
    write_json(out/'comparison_summary.json',rows)
    lines=['# CE-clean-only full-scale baseline','',
           'Loss = CE_clean only (weight1). No spectral selection, CE_worst, auxiliary forward or L_aux.',
           'Historical C_FULL used CE_clean + L_aux. Auxiliary modules are frozen compatibility placeholders; not optimized.',
           f'Matched notebook18: full eligible Train, crop1.5 BGR80, pretrained trunk/seed{TRAIN_SEED}, SGD .005/.9/5e-4, batch256 AMP, max12 epochs, milestones[4,8], gamma.2, phase-aware patience9/3. Checkpoints eligible from epoch1.',
           'CelebA full Test-as-Val is reused for selection and calibration, as in notebook18: not independent held-out Test evidence.',
           'LCC uses the source-frozen threshold. CASIA source and optional train-only calibrated thresholds are separate; video and frame units are separate.',
           'CASIA train and combined calibrated metrics include fitting data; Kaggle train/test copy overlap limits independence. No webcam validation or significance claim.','',
           '| Run | Dataset | Unit | Threshold policy | AUC | EER | APCER | BPCER | ACER | HTER | Scored | Candidates |',
           '|---|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|']
    columns=['run_id','dataset','unit','threshold_policy','auc','eer','apcer','bpcer','acer','hter','scored_n','candidate_n']
    for row in rows:lines.append('| '+' | '.join(str(row.get(k)) if row.get(k) is not None else 'undefined' for k in columns)+' |')
    lines+=['','Metrics are fractions. ACER=HTER=(APCER+BPCER)/2; Real iff logit(real)-logit(attack) >= threshold.',
            'Source and LCC predictions/metrics: runs/<run_id>/predictions and metrics. CASIA predictions, threshold curves, coverage and report: runs/<run_id>/casia.',
            'One new model, one seed. No new-model results exist until training/evaluation completes.','']
    (out/'ce_clean_fullscale_report.md').write_text('\n'.join(lines))
    if rows:display(pd.DataFrame(rows)[columns])
    return rows

def export_overall_zip():
    archive_path=out.with_suffix('.zip')
    with zipfile.ZipFile(archive_path,'w',compression=zipfile.ZIP_DEFLATED,allowZip64=True) as archive:
        for path in sorted(out.rglob('*')):
            if path.is_file() and path.name!='shared_crops_bgr_uint8.npy' and not path.name.endswith('.partial.csv'):
                archive.write(path,path.relative_to(out))
    print('Saved results ZIP:',archive_path,flush=True)
    display(FileLink(str(archive_path)))

def export_run_zip(name):
    folder=out/'runs'/name
    archive_path=out/f'{name}_s{TRAIN_SEED}.zip'
    with zipfile.ZipFile(archive_path,'w',compression=zipfile.ZIP_DEFLATED,allowZip64=True) as archive:
        for path in sorted(folder.rglob('*')):
            if path.is_file() and path.name!='shared_crops_bgr_uint8.npy' and not path.name.endswith('.partial.csv'):
                archive.write(path,path.relative_to(folder))
    print('Saved run ZIP:',archive_path,flush=True)
    display(FileLink(str(archive_path)))

## Train and evaluate

Progress prints from the first batch. RESUME continues epoch-boundary training; completed source/LCC evaluation is retained while CASIA runs separately. The ZIP excludes the shared CASIA crop array.

In [7]:
selected=select_runs(RUN_FILTER)
print('[Runner] Selected CE-only baseline:',selected,flush=True)
for name in selected:
    run_one(name,RUNS[name])
    export_summary()  # Save source/LCC results before CASIA detection/evaluation.
    folder=out/'runs'/name
    casia_done=folder/'casia_completion.json'
    if not casia_done.exists():
        best=torch.load(folder/'best.pth',map_location='cpu',weights_only=True)
        model,_=init_model({'init':'pretrained','copied':True})
        model.load_state_dict(best['state_dict'],strict=True);model=model.to(device).eval()
        locked=read_json(folder/'evaluation_freeze.json')['locked_threshold']
        print('[CASIA] Reloaded best checkpoint:',name,'epoch',best['epoch'],flush=True)
        evaluate_casia(model,folder,name,locked,best['epoch'])
        write_json(casia_done,{'run_id':name,'best_epoch':best['epoch'],'source_threshold':locked,
                              'train_threshold_calibration':CALIBRATE_CASIA_THRESHOLD,'status':'complete'})
        del model;gc.collect();torch.cuda.empty_cache()
    else:
        expected=read_json(casia_done)
        if expected['train_threshold_calibration']!=CALIBRATE_CASIA_THRESHOLD:raise RuntimeError('CASIA completion settings changed')
        casia=folder/'casia'
        needed=[casia/'comparison_summary.json',casia/'casia_train_test_evaluation_report.md']
        if CALIBRATE_CASIA_THRESHOLD:needed.append(casia/'casia_calibrated_threshold_summary.json')
        if not all(p.exists() for p in needed):raise RuntimeError('Incomplete CASIA outputs; remove only casia_completion.json to rerun CASIA')
        print('[CASIA] Already completed; skipping',flush=True)
    export_summary();export_overall_zip();export_run_zip(name)
print('Finished CE-only baseline:',selected,flush=True)

[Runner] Selected CE-only baseline: ['CE_CLEAN_FULL_crop15']
[CE_CLEAN_FULL_crop15] epoch 1/12 starting, warmup=False

/tmp/ipykernel_23/1895080082.py:403: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  scaler=torch.cuda.amp.GradScaler(enabled=use_amp)
/tmp/ipykernel_23/1895080082.py:312: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

[CE_CLEAN_FULL_crop15] epoch 1 batch 1/1893, loss=0.6240, elapsed=15.3s
[CE_CLEAN_FULL_crop15] epoch 1 batch 25/1893, loss=0.2980, elapsed=41.3s
[CE_CLEAN_FULL_crop15] epoch 1 batch 50/1893, loss=0.2182, elapsed=72.4s
[CE_CLEAN_FULL_crop15] epoch 1 batch 75/1893, loss=0.1838, elapsed=99.6s
[CE_CLEAN_FULL_crop15] epoch 1 batch 100/1893, loss=0.1654, elapsed=125.4s
[CE_CLEAN_FULL_crop15] epoch 1 batch 125/1893, loss=0.1558, elapsed=154.2s
[CE_CLEAN_FULL_crop15] epoch 1 batch 150/1893, loss=0.1468, elapsed=179.7s
[CE_CLEAN_FULL_crop15] epoch 1 batch 175/1893, loss=0.1402, elapsed=204.4s
[CE_CLEAN_FULL_crop15] epoch 1 batch 200/1893, loss=0.1346, elapsed=229.7s
[CE_CLEAN_FULL_crop15] epoch 1 batch 225/1893, loss=0.1301, elapsed=256.6s
[CE_CLEAN_FULL_crop15] epoch 1 batch 250/1893, loss=0.1268, elapsed=280.9s
[CE_CLEAN_FULL_crop15] epoch 1 batch 275/1893, loss=0.1231, elapsed=305.1s
[CE_CLEAN_FULL_crop15] epoch 1 batch 300/1893, loss=0.1182, elapsed=330.3s
[CE_CLEAN_FULL_crop15] epoch 1 batch 325/1893, loss=0.1148, elapsed=363.4s
[CE_CLEAN_FULL_crop15] epoch 1 batch 350/1893, loss=0.1124, elapsed=388.4s
[CE_CLEAN_FULL_crop15] epoch 1 batch 375/1893, loss=0.1106, elapsed=412.4s
[CE_CLEAN_FULL_crop15] epoch 1 batch 400/1893, loss=0.1087, elapsed=435.8s
[CE_CLEAN_FULL_crop15] epoch 1 batch 425/1893, loss=0.1070, elapsed=464.0s
[CE_CLEAN_FULL_crop15] epoch 1 batch 450/1893, loss=0.1050, elapsed=487.6s
[CE_CLEAN_FULL_crop15] epoch 1 batch 475/1893, loss=0.1036, elapsed=510.7s
[CE_CLEAN_FULL_crop15] epoch 1 batch 500/1893, loss=0.1020, elapsed=534.8s
[CE_CLEAN_FULL_crop15] epoch 1 batch 525/1893, loss=0.1004, elapsed=561.9s
[CE_CLEAN_FULL_crop15] epoch 1 batch 550/1893, loss=0.0997, elapsed=585.5s
[CE_CLEAN_FULL_crop15] epoch 1 batch 575/1893, loss=0.0984, elapsed=608.4s
[CE_CLEAN_FULL_crop15] epoch 1 batch 600/1893, loss=0.0971, elapsed=631.9s
[CE_CLEAN_FULL_crop15] epoch 1 batch 625/1893, loss=0.0959, elapsed=659.6s
[CE_CLEAN_FULL_crop15] epoch 1 batch 650/1893, loss=0.0952, elapsed=684.3s
[CE_CLEAN_FULL_crop15] epoch 1 batch 675/1893, loss=0.0942, elapsed=708.0s
[CE_CLEAN_FULL_crop15] epoch 1 batch 700/1893, loss=0.0930, elapsed=732.1s
[CE_CLEAN_FULL_crop15] epoch 1 batch 725/1893, loss=0.0920, elapsed=758.4s
[CE_CLEAN_FULL_crop15] epoch 1 batch 750/1893, loss=0.0912, elapsed=781.7s
[CE_CLEAN_FULL_crop15] epoch 1 batch 775/1893, loss=0.0903, elapsed=805.3s
[CE_CLEAN_FULL_crop15] epoch 1 batch 800/1893, loss=0.0895, elapsed=829.3s
[CE_CLEAN_FULL_crop15] epoch 1 batch 825/1893, loss=0.0887, elapsed=857.4s
[CE_CLEAN_FULL_crop15] epoch 1 batch 850/1893, loss=0.0880, elapsed=880.5s
[CE_CLEAN_FULL_crop15] epoch 1 batch 875/1893, loss=0.0872, elapsed=903.7s
[CE_CLEAN_FULL_crop15] epoch 1 batch 900/1893, loss=0.0865, elapsed=927.3s
[CE_CLEAN_FULL_crop15] epoch 1 batch 925/1893, loss=0.0859, elapsed=954.5s
[CE_CLEAN_FULL_crop15] epoch 1 batch 950/1893, loss=0.0853, elapsed=978.6s
[CE_CLEAN_FULL_crop15] epoch 1 batch 975/1893, loss=0.0845, elapsed=1001.9s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1000/1893, loss=0.0841, elapsed=1024.8s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1025/1893, loss=0.0834, elapsed=1052.1s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1050/1893, loss=0.0830, elapsed=1075.1s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1075/1893, loss=0.0826, elapsed=1098.7s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1100/1893, loss=0.0820, elapsed=1122.7s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1125/1893, loss=0.0815, elapsed=1149.8s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1150/1893, loss=0.0809, elapsed=1173.6s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1175/1893, loss=0.0805, elapsed=1199.1s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1200/1893, loss=0.0801, elapsed=1223.4s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1225/1893, loss=0.0797, elapsed=1251.1s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1250/1893, loss=0.0792, elapsed=1276.6s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1275/1893, loss=0.0789, elapsed=1301.2s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1300/1893, loss=0.0784, elapsed=1324.9s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1325/1893, loss=0.0781, elapsed=1352.1s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1350/1893, loss=0.0778, elapsed=1374.9s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1375/1893, loss=0.0772, elapsed=1398.5s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1400/1893, loss=0.0768, elapsed=1421.8s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1425/1893, loss=0.0763, elapsed=1449.6s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1450/1893, loss=0.0760, elapsed=1474.6s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1475/1893, loss=0.0758, elapsed=1498.0s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1500/1893, loss=0.0755, elapsed=1522.6s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1525/1893, loss=0.0752, elapsed=1550.1s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1550/1893, loss=0.0749, elapsed=1575.0s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1575/1893, loss=0.0745, elapsed=1598.9s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1600/1893, loss=0.0742, elapsed=1622.6s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1625/1893, loss=0.0739, elapsed=1650.4s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1650/1893, loss=0.0736, elapsed=1674.7s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1675/1893, loss=0.0734, elapsed=1699.6s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1700/1893, loss=0.0730, elapsed=1724.3s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1725/1893, loss=0.0728, elapsed=1755.8s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1750/1893, loss=0.0725, elapsed=1780.7s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1775/1893, loss=0.0722, elapsed=1804.5s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1800/1893, loss=0.0719, elapsed=1828.5s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1825/1893, loss=0.0716, elapsed=1857.1s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1850/1893, loss=0.0714, elapsed=1881.4s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1875/1893, loss=0.0713, elapsed=1905.1s
[CE_CLEAN_FULL_crop15] epoch 1 batch 1893/1893, loss=0.0712, elapsed=1929.4s
[Inference] Starting 66379 scored images
[Inference] batch 1/260, elapsed=9.1s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 25/260, elapsed=50.6s
[Inference] batch 50/260, elapsed=88.8s
[Inference] batch 75/260, elapsed=131.4s
[Inference] batch 100/260, elapsed=173.1s
[Inference] batch 125/260, elapsed=219.5s
[Inference] batch 150/260, elapsed=263.7s
[Inference] batch 175/260, elapsed=304.9s
[Inference] batch 200/260, elapsed=345.1s
[Inference] batch 225/260, elapsed=386.9s
[Inference] batch 250/260, elapsed=432.3s
[Inference] batch 260/260, elapsed=447.3s
CE_CLEAN_FULL_crop15 epoch 1 Full Test-as-Val ACER 0.0888329331272496 best 1 patience 0
[CE_CLEAN_FULL_crop15] epoch 2/12 starting, warmup=False
[CE_CLEAN_FULL_crop15] epoch 2 batch 1/1893, loss=0.0615, elapsed=3.2s

/tmp/ipykernel_23/1895080082.py:312: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

[CE_CLEAN_FULL_crop15] epoch 2 batch 25/1893, loss=0.0507, elapsed=21.1s
[CE_CLEAN_FULL_crop15] epoch 2 batch 50/1893, loss=0.0531, elapsed=39.6s
[CE_CLEAN_FULL_crop15] epoch 2 batch 75/1893, loss=0.0509, elapsed=57.5s
[CE_CLEAN_FULL_crop15] epoch 2 batch 100/1893, loss=0.0509, elapsed=74.9s
[CE_CLEAN_FULL_crop15] epoch 2 batch 125/1893, loss=0.0505, elapsed=91.8s
[CE_CLEAN_FULL_crop15] epoch 2 batch 150/1893, loss=0.0505, elapsed=110.4s
[CE_CLEAN_FULL_crop15] epoch 2 batch 175/1893, loss=0.0490, elapsed=127.5s
[CE_CLEAN_FULL_crop15] epoch 2 batch 200/1893, loss=0.0497, elapsed=144.8s
[CE_CLEAN_FULL_crop15] epoch 2 batch 225/1893, loss=0.0504, elapsed=163.3s
[CE_CLEAN_FULL_crop15] epoch 2 batch 250/1893, loss=0.0509, elapsed=181.1s
[CE_CLEAN_FULL_crop15] epoch 2 batch 275/1893, loss=0.0504, elapsed=199.2s
[CE_CLEAN_FULL_crop15] epoch 2 batch 300/1893, loss=0.0503, elapsed=217.0s
[CE_CLEAN_FULL_crop15] epoch 2 batch 325/1893, loss=0.0501, elapsed=236.1s
[CE_CLEAN_FULL_crop15] epoch 2 batch 350/1893, loss=0.0500, elapsed=254.8s
[CE_CLEAN_FULL_crop15] epoch 2 batch 375/1893, loss=0.0497, elapsed=272.6s
[CE_CLEAN_FULL_crop15] epoch 2 batch 400/1893, loss=0.0498, elapsed=291.0s
[CE_CLEAN_FULL_crop15] epoch 2 batch 425/1893, loss=0.0496, elapsed=311.6s
[CE_CLEAN_FULL_crop15] epoch 2 batch 450/1893, loss=0.0497, elapsed=329.4s
[CE_CLEAN_FULL_crop15] epoch 2 batch 475/1893, loss=0.0498, elapsed=346.6s
[CE_CLEAN_FULL_crop15] epoch 2 batch 500/1893, loss=0.0493, elapsed=364.6s
[CE_CLEAN_FULL_crop15] epoch 2 batch 525/1893, loss=0.0493, elapsed=384.4s
[CE_CLEAN_FULL_crop15] epoch 2 batch 550/1893, loss=0.0490, elapsed=402.3s
[CE_CLEAN_FULL_crop15] epoch 2 batch 575/1893, loss=0.0488, elapsed=420.1s
[CE_CLEAN_FULL_crop15] epoch 2 batch 600/1893, loss=0.0489, elapsed=439.5s
[CE_CLEAN_FULL_crop15] epoch 2 batch 625/1893, loss=0.0488, elapsed=461.2s
[CE_CLEAN_FULL_crop15] epoch 2 batch 650/1893, loss=0.0487, elapsed=481.1s
[CE_CLEAN_FULL_crop15] epoch 2 batch 675/1893, loss=0.0484, elapsed=500.1s
[CE_CLEAN_FULL_crop15] epoch 2 batch 700/1893, loss=0.0483, elapsed=518.3s
[CE_CLEAN_FULL_crop15] epoch 2 batch 725/1893, loss=0.0482, elapsed=539.2s
[CE_CLEAN_FULL_crop15] epoch 2 batch 750/1893, loss=0.0482, elapsed=556.8s
[CE_CLEAN_FULL_crop15] epoch 2 batch 775/1893, loss=0.0480, elapsed=575.1s
[CE_CLEAN_FULL_crop15] epoch 2 batch 800/1893, loss=0.0479, elapsed=593.1s
[CE_CLEAN_FULL_crop15] epoch 2 batch 825/1893, loss=0.0477, elapsed=613.5s
[CE_CLEAN_FULL_crop15] epoch 2 batch 850/1893, loss=0.0478, elapsed=631.2s
[CE_CLEAN_FULL_crop15] epoch 2 batch 875/1893, loss=0.0479, elapsed=648.8s
[CE_CLEAN_FULL_crop15] epoch 2 batch 900/1893, loss=0.0477, elapsed=668.3s
[CE_CLEAN_FULL_crop15] epoch 2 batch 925/1893, loss=0.0476, elapsed=687.4s
[CE_CLEAN_FULL_crop15] epoch 2 batch 950/1893, loss=0.0476, elapsed=704.3s
[CE_CLEAN_FULL_crop15] epoch 2 batch 975/1893, loss=0.0475, elapsed=721.6s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1000/1893, loss=0.0476, elapsed=739.2s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1025/1893, loss=0.0475, elapsed=758.6s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1050/1893, loss=0.0474, elapsed=775.5s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1075/1893, loss=0.0474, elapsed=793.0s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1100/1893, loss=0.0474, elapsed=812.3s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1125/1893, loss=0.0473, elapsed=832.7s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1150/1893, loss=0.0472, elapsed=852.3s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1175/1893, loss=0.0472, elapsed=869.2s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1200/1893, loss=0.0471, elapsed=887.5s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1225/1893, loss=0.0471, elapsed=907.7s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1250/1893, loss=0.0473, elapsed=924.9s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1275/1893, loss=0.0473, elapsed=942.2s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1300/1893, loss=0.0473, elapsed=959.6s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1325/1893, loss=0.0473, elapsed=979.7s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1350/1893, loss=0.0472, elapsed=996.4s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1375/1893, loss=0.0472, elapsed=1014.6s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1400/1893, loss=0.0471, elapsed=1033.4s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1425/1893, loss=0.0470, elapsed=1053.0s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1450/1893, loss=0.0468, elapsed=1069.9s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1475/1893, loss=0.0467, elapsed=1088.4s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1500/1893, loss=0.0468, elapsed=1106.0s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1525/1893, loss=0.0467, elapsed=1124.5s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1550/1893, loss=0.0466, elapsed=1141.4s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1575/1893, loss=0.0465, elapsed=1158.7s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1600/1893, loss=0.0464, elapsed=1176.3s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1625/1893, loss=0.0463, elapsed=1194.9s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1650/1893, loss=0.0462, elapsed=1212.0s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1675/1893, loss=0.0462, elapsed=1229.1s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1700/1893, loss=0.0461, elapsed=1247.0s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1725/1893, loss=0.0460, elapsed=1265.2s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1750/1893, loss=0.0459, elapsed=1284.6s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1775/1893, loss=0.0459, elapsed=1302.9s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1800/1893, loss=0.0459, elapsed=1321.5s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1825/1893, loss=0.0459, elapsed=1340.3s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1850/1893, loss=0.0458, elapsed=1362.1s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1875/1893, loss=0.0458, elapsed=1382.1s
[CE_CLEAN_FULL_crop15] epoch 2 batch 1893/1893, loss=0.0457, elapsed=1394.5s
[Inference] Starting 66379 scored images
[Inference] batch 1/260, elapsed=6.0s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 25/260, elapsed=37.7s
[Inference] batch 50/260, elapsed=66.6s
[Inference] batch 75/260, elapsed=99.2s
[Inference] batch 100/260, elapsed=130.3s
[Inference] batch 125/260, elapsed=163.7s
[Inference] batch 150/260, elapsed=197.0s
[Inference] batch 175/260, elapsed=228.1s
[Inference] batch 200/260, elapsed=259.0s
[Inference] batch 225/260, elapsed=290.3s
[Inference] batch 250/260, elapsed=326.7s
[Inference] batch 260/260, elapsed=336.4s
CE_CLEAN_FULL_crop15 epoch 2 Full Test-as-Val ACER 0.0872504610411315 best 2 patience 0
[CE_CLEAN_FULL_crop15] epoch 3/12 starting, warmup=False
[CE_CLEAN_FULL_crop15] epoch 3 batch 1/1893, loss=0.0537, elapsed=3.9s

/tmp/ipykernel_23/1895080082.py:312: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

[CE_CLEAN_FULL_crop15] epoch 3 batch 25/1893, loss=0.0408, elapsed=21.1s
[CE_CLEAN_FULL_crop15] epoch 3 batch 50/1893, loss=0.0397, elapsed=39.1s
[CE_CLEAN_FULL_crop15] epoch 3 batch 75/1893, loss=0.0376, elapsed=56.7s
[CE_CLEAN_FULL_crop15] epoch 3 batch 100/1893, loss=0.0366, elapsed=75.8s
[CE_CLEAN_FULL_crop15] epoch 3 batch 125/1893, loss=0.0375, elapsed=96.0s
[CE_CLEAN_FULL_crop15] epoch 3 batch 150/1893, loss=0.0384, elapsed=114.9s
[CE_CLEAN_FULL_crop15] epoch 3 batch 175/1893, loss=0.0389, elapsed=132.3s
[CE_CLEAN_FULL_crop15] epoch 3 batch 200/1893, loss=0.0392, elapsed=150.1s
[CE_CLEAN_FULL_crop15] epoch 3 batch 225/1893, loss=0.0390, elapsed=170.0s
[CE_CLEAN_FULL_crop15] epoch 3 batch 250/1893, loss=0.0391, elapsed=189.6s
[CE_CLEAN_FULL_crop15] epoch 3 batch 275/1893, loss=0.0395, elapsed=208.3s
[CE_CLEAN_FULL_crop15] epoch 3 batch 300/1893, loss=0.0396, elapsed=225.5s
[CE_CLEAN_FULL_crop15] epoch 3 batch 325/1893, loss=0.0398, elapsed=243.8s
[CE_CLEAN_FULL_crop15] epoch 3 batch 350/1893, loss=0.0398, elapsed=264.4s
[CE_CLEAN_FULL_crop15] epoch 3 batch 375/1893, loss=0.0397, elapsed=282.0s
[CE_CLEAN_FULL_crop15] epoch 3 batch 400/1893, loss=0.0399, elapsed=300.0s
[CE_CLEAN_FULL_crop15] epoch 3 batch 425/1893, loss=0.0399, elapsed=318.8s
[CE_CLEAN_FULL_crop15] epoch 3 batch 450/1893, loss=0.0400, elapsed=339.3s
[CE_CLEAN_FULL_crop15] epoch 3 batch 475/1893, loss=0.0402, elapsed=358.0s
[CE_CLEAN_FULL_crop15] epoch 3 batch 500/1893, loss=0.0399, elapsed=377.1s
[CE_CLEAN_FULL_crop15] epoch 3 batch 525/1893, loss=0.0398, elapsed=396.0s
[CE_CLEAN_FULL_crop15] epoch 3 batch 550/1893, loss=0.0396, elapsed=418.0s
[CE_CLEAN_FULL_crop15] epoch 3 batch 575/1893, loss=0.0399, elapsed=437.6s
[CE_CLEAN_FULL_crop15] epoch 3 batch 600/1893, loss=0.0401, elapsed=456.9s
[CE_CLEAN_FULL_crop15] epoch 3 batch 625/1893, loss=0.0402, elapsed=475.9s
[CE_CLEAN_FULL_crop15] epoch 3 batch 650/1893, loss=0.0401, elapsed=497.3s
[CE_CLEAN_FULL_crop15] epoch 3 batch 675/1893, loss=0.0402, elapsed=516.3s
[CE_CLEAN_FULL_crop15] epoch 3 batch 700/1893, loss=0.0401, elapsed=535.5s
[CE_CLEAN_FULL_crop15] epoch 3 batch 725/1893, loss=0.0399, elapsed=553.7s
[CE_CLEAN_FULL_crop15] epoch 3 batch 750/1893, loss=0.0399, elapsed=575.5s
[CE_CLEAN_FULL_crop15] epoch 3 batch 775/1893, loss=0.0396, elapsed=594.0s
[CE_CLEAN_FULL_crop15] epoch 3 batch 800/1893, loss=0.0396, elapsed=613.0s
[CE_CLEAN_FULL_crop15] epoch 3 batch 825/1893, loss=0.0396, elapsed=631.7s
[CE_CLEAN_FULL_crop15] epoch 3 batch 850/1893, loss=0.0395, elapsed=653.4s
[CE_CLEAN_FULL_crop15] epoch 3 batch 875/1893, loss=0.0396, elapsed=671.7s
[CE_CLEAN_FULL_crop15] epoch 3 batch 900/1893, loss=0.0395, elapsed=691.7s
[CE_CLEAN_FULL_crop15] epoch 3 batch 925/1893, loss=0.0394, elapsed=710.4s
[CE_CLEAN_FULL_crop15] epoch 3 batch 950/1893, loss=0.0394, elapsed=732.9s
[CE_CLEAN_FULL_crop15] epoch 3 batch 975/1893, loss=0.0394, elapsed=752.3s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1000/1893, loss=0.0393, elapsed=771.4s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1025/1893, loss=0.0392, elapsed=790.5s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1050/1893, loss=0.0393, elapsed=812.7s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1075/1893, loss=0.0393, elapsed=830.8s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1100/1893, loss=0.0392, elapsed=849.7s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1125/1893, loss=0.0393, elapsed=868.7s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1150/1893, loss=0.0393, elapsed=889.5s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1175/1893, loss=0.0394, elapsed=907.9s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1200/1893, loss=0.0392, elapsed=926.4s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1225/1893, loss=0.0392, elapsed=945.4s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1250/1893, loss=0.0391, elapsed=966.5s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1275/1893, loss=0.0390, elapsed=985.5s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1300/1893, loss=0.0389, elapsed=1006.0s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1325/1893, loss=0.0388, elapsed=1026.2s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1350/1893, loss=0.0389, elapsed=1049.2s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1375/1893, loss=0.0388, elapsed=1072.3s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1400/1893, loss=0.0387, elapsed=1094.8s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1425/1893, loss=0.0388, elapsed=1118.3s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1450/1893, loss=0.0387, elapsed=1145.4s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1475/1893, loss=0.0386, elapsed=1169.1s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1500/1893, loss=0.0387, elapsed=1190.4s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1525/1893, loss=0.0387, elapsed=1211.5s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1550/1893, loss=0.0387, elapsed=1235.5s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1575/1893, loss=0.0388, elapsed=1256.6s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1600/1893, loss=0.0387, elapsed=1278.2s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1625/1893, loss=0.0387, elapsed=1300.9s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1650/1893, loss=0.0387, elapsed=1325.4s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1675/1893, loss=0.0387, elapsed=1347.0s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1700/1893, loss=0.0388, elapsed=1369.3s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1725/1893, loss=0.0388, elapsed=1388.7s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1750/1893, loss=0.0388, elapsed=1410.0s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1775/1893, loss=0.0388, elapsed=1430.2s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1800/1893, loss=0.0388, elapsed=1449.9s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1825/1893, loss=0.0387, elapsed=1470.3s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1850/1893, loss=0.0388, elapsed=1489.5s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1875/1893, loss=0.0387, elapsed=1509.9s
[CE_CLEAN_FULL_crop15] epoch 3 batch 1893/1893, loss=0.0387, elapsed=1523.5s
[Inference] Starting 66379 scored images
[Inference] batch 1/260, elapsed=6.8s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 25/260, elapsed=42.2s
[Inference] batch 50/260, elapsed=75.5s
[Inference] batch 75/260, elapsed=111.6s
[Inference] batch 100/260, elapsed=148.4s
[Inference] batch 125/260, elapsed=187.1s
[Inference] batch 150/260, elapsed=223.9s
[Inference] batch 175/260, elapsed=258.2s
[Inference] batch 200/260, elapsed=295.8s
[Inference] batch 225/260, elapsed=339.1s
[Inference] batch 250/260, elapsed=381.1s
[Inference] batch 260/260, elapsed=394.3s
CE_CLEAN_FULL_crop15 epoch 3 Full Test-as-Val ACER 0.07445289637816199 best 3 patience 0
[CE_CLEAN_FULL_crop15] epoch 4/12 starting, warmup=False
[CE_CLEAN_FULL_crop15] epoch 4 batch 1/1893, loss=0.0263, elapsed=4.6s

/tmp/ipykernel_23/1895080082.py:312: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

[CE_CLEAN_FULL_crop15] epoch 4 batch 25/1893, loss=0.0376, elapsed=26.5s
[CE_CLEAN_FULL_crop15] epoch 4 batch 50/1893, loss=0.0382, elapsed=45.8s
[CE_CLEAN_FULL_crop15] epoch 4 batch 75/1893, loss=0.0362, elapsed=64.7s
[CE_CLEAN_FULL_crop15] epoch 4 batch 100/1893, loss=0.0378, elapsed=83.1s
[CE_CLEAN_FULL_crop15] epoch 4 batch 125/1893, loss=0.0377, elapsed=103.7s
[CE_CLEAN_FULL_crop15] epoch 4 batch 150/1893, loss=0.0373, elapsed=122.3s
[CE_CLEAN_FULL_crop15] epoch 4 batch 175/1893, loss=0.0368, elapsed=141.2s
[CE_CLEAN_FULL_crop15] epoch 4 batch 200/1893, loss=0.0365, elapsed=158.9s
[CE_CLEAN_FULL_crop15] epoch 4 batch 225/1893, loss=0.0362, elapsed=180.0s
[CE_CLEAN_FULL_crop15] epoch 4 batch 250/1893, loss=0.0360, elapsed=198.0s
[CE_CLEAN_FULL_crop15] epoch 4 batch 275/1893, loss=0.0362, elapsed=215.4s
[CE_CLEAN_FULL_crop15] epoch 4 batch 300/1893, loss=0.0359, elapsed=233.5s
[CE_CLEAN_FULL_crop15] epoch 4 batch 325/1893, loss=0.0357, elapsed=254.1s
[CE_CLEAN_FULL_crop15] epoch 4 batch 350/1893, loss=0.0357, elapsed=273.3s
[CE_CLEAN_FULL_crop15] epoch 4 batch 375/1893, loss=0.0356, elapsed=291.6s
[CE_CLEAN_FULL_crop15] epoch 4 batch 400/1893, loss=0.0355, elapsed=309.4s
[CE_CLEAN_FULL_crop15] epoch 4 batch 425/1893, loss=0.0353, elapsed=328.8s
[CE_CLEAN_FULL_crop15] epoch 4 batch 450/1893, loss=0.0356, elapsed=347.7s
[CE_CLEAN_FULL_crop15] epoch 4 batch 475/1893, loss=0.0354, elapsed=366.0s
[CE_CLEAN_FULL_crop15] epoch 4 batch 500/1893, loss=0.0353, elapsed=384.1s
[CE_CLEAN_FULL_crop15] epoch 4 batch 525/1893, loss=0.0352, elapsed=402.3s
[CE_CLEAN_FULL_crop15] epoch 4 batch 550/1893, loss=0.0352, elapsed=421.5s
[CE_CLEAN_FULL_crop15] epoch 4 batch 575/1893, loss=0.0351, elapsed=439.4s
[CE_CLEAN_FULL_crop15] epoch 4 batch 600/1893, loss=0.0351, elapsed=458.2s
[CE_CLEAN_FULL_crop15] epoch 4 batch 625/1893, loss=0.0352, elapsed=476.4s
[CE_CLEAN_FULL_crop15] epoch 4 batch 650/1893, loss=0.0351, elapsed=496.3s
[CE_CLEAN_FULL_crop15] epoch 4 batch 675/1893, loss=0.0349, elapsed=515.4s
[CE_CLEAN_FULL_crop15] epoch 4 batch 700/1893, loss=0.0347, elapsed=534.0s
[CE_CLEAN_FULL_crop15] epoch 4 batch 725/1893, loss=0.0347, elapsed=551.7s
[CE_CLEAN_FULL_crop15] epoch 4 batch 750/1893, loss=0.0349, elapsed=571.8s
[CE_CLEAN_FULL_crop15] epoch 4 batch 775/1893, loss=0.0350, elapsed=589.3s
[CE_CLEAN_FULL_crop15] epoch 4 batch 800/1893, loss=0.0352, elapsed=607.7s
[CE_CLEAN_FULL_crop15] epoch 4 batch 825/1893, loss=0.0352, elapsed=627.6s
[CE_CLEAN_FULL_crop15] epoch 4 batch 850/1893, loss=0.0352, elapsed=648.4s
[CE_CLEAN_FULL_crop15] epoch 4 batch 875/1893, loss=0.0352, elapsed=666.7s
[CE_CLEAN_FULL_crop15] epoch 4 batch 900/1893, loss=0.0352, elapsed=685.0s
[CE_CLEAN_FULL_crop15] epoch 4 batch 925/1893, loss=0.0353, elapsed=705.0s
[CE_CLEAN_FULL_crop15] epoch 4 batch 950/1893, loss=0.0353, elapsed=724.6s
[CE_CLEAN_FULL_crop15] epoch 4 batch 975/1893, loss=0.0354, elapsed=742.2s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1000/1893, loss=0.0356, elapsed=762.2s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1025/1893, loss=0.0355, elapsed=783.4s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1050/1893, loss=0.0354, elapsed=806.2s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1075/1893, loss=0.0355, elapsed=827.5s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1100/1893, loss=0.0356, elapsed=847.0s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1125/1893, loss=0.0356, elapsed=865.1s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1150/1893, loss=0.0357, elapsed=886.8s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1175/1893, loss=0.0358, elapsed=906.0s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1200/1893, loss=0.0358, elapsed=924.4s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1225/1893, loss=0.0358, elapsed=942.7s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1250/1893, loss=0.0358, elapsed=963.6s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1275/1893, loss=0.0357, elapsed=981.7s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1300/1893, loss=0.0355, elapsed=999.0s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1325/1893, loss=0.0355, elapsed=1021.4s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1350/1893, loss=0.0355, elapsed=1042.1s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1375/1893, loss=0.0355, elapsed=1061.4s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1400/1893, loss=0.0354, elapsed=1080.6s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1425/1893, loss=0.0354, elapsed=1099.1s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1450/1893, loss=0.0352, elapsed=1120.0s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1475/1893, loss=0.0352, elapsed=1138.7s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1500/1893, loss=0.0353, elapsed=1156.9s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1525/1893, loss=0.0353, elapsed=1175.9s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1550/1893, loss=0.0353, elapsed=1196.7s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1575/1893, loss=0.0354, elapsed=1214.8s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1600/1893, loss=0.0354, elapsed=1233.2s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1625/1893, loss=0.0355, elapsed=1251.8s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1650/1893, loss=0.0354, elapsed=1273.3s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1675/1893, loss=0.0354, elapsed=1293.3s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1700/1893, loss=0.0353, elapsed=1312.8s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1725/1893, loss=0.0353, elapsed=1331.1s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1750/1893, loss=0.0353, elapsed=1351.7s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1775/1893, loss=0.0353, elapsed=1369.8s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1800/1893, loss=0.0354, elapsed=1388.8s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1825/1893, loss=0.0354, elapsed=1408.0s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1850/1893, loss=0.0354, elapsed=1428.0s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1875/1893, loss=0.0354, elapsed=1445.9s
[CE_CLEAN_FULL_crop15] epoch 4 batch 1893/1893, loss=0.0354, elapsed=1458.8s
[Inference] Starting 66379 scored images
[Inference] batch 1/260, elapsed=6.6s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 25/260, elapsed=39.4s
[Inference] batch 50/260, elapsed=70.2s
[Inference] batch 75/260, elapsed=103.1s
[Inference] batch 100/260, elapsed=136.8s
[Inference] batch 125/260, elapsed=173.1s
[Inference] batch 150/260, elapsed=208.4s
[Inference] batch 175/260, elapsed=242.1s
[Inference] batch 200/260, elapsed=274.6s
[Inference] batch 225/260, elapsed=310.0s
[Inference] batch 250/260, elapsed=344.8s
[Inference] batch 260/260, elapsed=355.4s
CE_CLEAN_FULL_crop15 epoch 4 Full Test-as-Val ACER 0.06050870199848489 best 4 patience 0
[CE_CLEAN_FULL_crop15] epoch 5/12 starting, warmup=False
[CE_CLEAN_FULL_crop15] epoch 5 batch 1/1893, loss=0.0507, elapsed=3.3s

/tmp/ipykernel_23/1895080082.py:312: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

[CE_CLEAN_FULL_crop15] epoch 5 batch 25/1893, loss=0.0266, elapsed=21.9s
[CE_CLEAN_FULL_crop15] epoch 5 batch 50/1893, loss=0.0273, elapsed=39.5s
[CE_CLEAN_FULL_crop15] epoch 5 batch 75/1893, loss=0.0276, elapsed=56.1s
[CE_CLEAN_FULL_crop15] epoch 5 batch 100/1893, loss=0.0277, elapsed=74.1s
[CE_CLEAN_FULL_crop15] epoch 5 batch 125/1893, loss=0.0274, elapsed=93.4s
[CE_CLEAN_FULL_crop15] epoch 5 batch 150/1893, loss=0.0262, elapsed=111.3s
[CE_CLEAN_FULL_crop15] epoch 5 batch 175/1893, loss=0.0271, elapsed=129.0s
[CE_CLEAN_FULL_crop15] epoch 5 batch 200/1893, loss=0.0265, elapsed=145.8s
[CE_CLEAN_FULL_crop15] epoch 5 batch 225/1893, loss=0.0264, elapsed=164.2s
[CE_CLEAN_FULL_crop15] epoch 5 batch 250/1893, loss=0.0266, elapsed=181.2s
[CE_CLEAN_FULL_crop15] epoch 5 batch 275/1893, loss=0.0261, elapsed=201.0s
[CE_CLEAN_FULL_crop15] epoch 5 batch 300/1893, loss=0.0264, elapsed=217.5s
[CE_CLEAN_FULL_crop15] epoch 5 batch 325/1893, loss=0.0260, elapsed=234.7s
[CE_CLEAN_FULL_crop15] epoch 5 batch 350/1893, loss=0.0261, elapsed=251.7s
[CE_CLEAN_FULL_crop15] epoch 5 batch 375/1893, loss=0.0257, elapsed=270.6s
[CE_CLEAN_FULL_crop15] epoch 5 batch 400/1893, loss=0.0255, elapsed=287.6s
[CE_CLEAN_FULL_crop15] epoch 5 batch 425/1893, loss=0.0253, elapsed=307.0s
[CE_CLEAN_FULL_crop15] epoch 5 batch 450/1893, loss=0.0253, elapsed=324.9s
[CE_CLEAN_FULL_crop15] epoch 5 batch 475/1893, loss=0.0252, elapsed=342.7s
[CE_CLEAN_FULL_crop15] epoch 5 batch 500/1893, loss=0.0253, elapsed=360.4s
[CE_CLEAN_FULL_crop15] epoch 5 batch 525/1893, loss=0.0252, elapsed=378.3s
[CE_CLEAN_FULL_crop15] epoch 5 batch 550/1893, loss=0.0251, elapsed=395.3s
[CE_CLEAN_FULL_crop15] epoch 5 batch 575/1893, loss=0.0249, elapsed=414.6s
[CE_CLEAN_FULL_crop15] epoch 5 batch 600/1893, loss=0.0247, elapsed=432.7s
[CE_CLEAN_FULL_crop15] epoch 5 batch 625/1893, loss=0.0247, elapsed=450.1s
[CE_CLEAN_FULL_crop15] epoch 5 batch 650/1893, loss=0.0246, elapsed=467.4s
[CE_CLEAN_FULL_crop15] epoch 5 batch 675/1893, loss=0.0247, elapsed=487.5s
[CE_CLEAN_FULL_crop15] epoch 5 batch 700/1893, loss=0.0247, elapsed=505.2s
[CE_CLEAN_FULL_crop15] epoch 5 batch 725/1893, loss=0.0245, elapsed=523.0s
[CE_CLEAN_FULL_crop15] epoch 5 batch 750/1893, loss=0.0243, elapsed=542.3s
[CE_CLEAN_FULL_crop15] epoch 5 batch 775/1893, loss=0.0243, elapsed=564.1s
[CE_CLEAN_FULL_crop15] epoch 5 batch 800/1893, loss=0.0241, elapsed=581.9s
[CE_CLEAN_FULL_crop15] epoch 5 batch 825/1893, loss=0.0242, elapsed=599.7s
[CE_CLEAN_FULL_crop15] epoch 5 batch 850/1893, loss=0.0241, elapsed=617.4s
[CE_CLEAN_FULL_crop15] epoch 5 batch 875/1893, loss=0.0240, elapsed=637.0s
[CE_CLEAN_FULL_crop15] epoch 5 batch 900/1893, loss=0.0239, elapsed=653.9s
[CE_CLEAN_FULL_crop15] epoch 5 batch 925/1893, loss=0.0237, elapsed=671.7s
[CE_CLEAN_FULL_crop15] epoch 5 batch 950/1893, loss=0.0237, elapsed=690.7s
[CE_CLEAN_FULL_crop15] epoch 5 batch 975/1893, loss=0.0235, elapsed=710.6s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1000/1893, loss=0.0235, elapsed=729.5s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1025/1893, loss=0.0234, elapsed=748.1s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1050/1893, loss=0.0234, elapsed=767.1s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1075/1893, loss=0.0234, elapsed=785.8s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1100/1893, loss=0.0234, elapsed=805.9s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1125/1893, loss=0.0233, elapsed=826.2s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1150/1893, loss=0.0232, elapsed=850.1s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1175/1893, loss=0.0231, elapsed=872.7s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1200/1893, loss=0.0231, elapsed=894.8s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1225/1893, loss=0.0231, elapsed=916.3s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1250/1893, loss=0.0229, elapsed=941.2s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1275/1893, loss=0.0229, elapsed=964.2s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1300/1893, loss=0.0228, elapsed=985.4s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1325/1893, loss=0.0227, elapsed=1007.5s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1350/1893, loss=0.0227, elapsed=1031.6s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1375/1893, loss=0.0227, elapsed=1057.3s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1400/1893, loss=0.0225, elapsed=1079.1s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1425/1893, loss=0.0225, elapsed=1099.9s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1450/1893, loss=0.0225, elapsed=1120.7s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1475/1893, loss=0.0224, elapsed=1143.7s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1500/1893, loss=0.0223, elapsed=1163.6s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1525/1893, loss=0.0223, elapsed=1184.4s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1550/1893, loss=0.0223, elapsed=1206.5s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1575/1893, loss=0.0222, elapsed=1228.6s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1600/1893, loss=0.0223, elapsed=1251.6s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1625/1893, loss=0.0222, elapsed=1272.6s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1650/1893, loss=0.0222, elapsed=1293.1s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1675/1893, loss=0.0222, elapsed=1316.0s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1700/1893, loss=0.0222, elapsed=1338.1s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1725/1893, loss=0.0221, elapsed=1357.5s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1750/1893, loss=0.0221, elapsed=1377.3s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1775/1893, loss=0.0220, elapsed=1398.5s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1800/1893, loss=0.0220, elapsed=1420.7s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1825/1893, loss=0.0220, elapsed=1442.3s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1850/1893, loss=0.0220, elapsed=1462.8s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1875/1893, loss=0.0219, elapsed=1482.9s
[CE_CLEAN_FULL_crop15] epoch 5 batch 1893/1893, loss=0.0219, elapsed=1497.3s
[Inference] Starting 66379 scored images
[Inference] batch 1/260, elapsed=6.8s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 25/260, elapsed=42.3s
[Inference] batch 50/260, elapsed=76.2s
[Inference] batch 75/260, elapsed=110.9s
[Inference] batch 100/260, elapsed=144.9s
[Inference] batch 125/260, elapsed=183.7s
[Inference] batch 150/260, elapsed=218.5s
[Inference] batch 175/260, elapsed=253.1s
[Inference] batch 200/260, elapsed=286.4s
[Inference] batch 225/260, elapsed=326.3s
[Inference] batch 250/260, elapsed=364.0s
[Inference] batch 260/260, elapsed=374.8s
CE_CLEAN_FULL_crop15 epoch 5 Full Test-as-Val ACER 0.048645570595950566 best 5 patience 0
[CE_CLEAN_FULL_crop15] epoch 6/12 starting, warmup=False
[CE_CLEAN_FULL_crop15] epoch 6 batch 1/1893, loss=0.0096, elapsed=3.3s

/tmp/ipykernel_23/1895080082.py:312: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

[CE_CLEAN_FULL_crop15] epoch 6 batch 25/1893, loss=0.0240, elapsed=21.6s
[CE_CLEAN_FULL_crop15] epoch 6 batch 50/1893, loss=0.0208, elapsed=39.6s
[CE_CLEAN_FULL_crop15] epoch 6 batch 75/1893, loss=0.0195, elapsed=57.8s
[CE_CLEAN_FULL_crop15] epoch 6 batch 100/1893, loss=0.0180, elapsed=75.5s
[CE_CLEAN_FULL_crop15] epoch 6 batch 125/1893, loss=0.0178, elapsed=95.8s
[CE_CLEAN_FULL_crop15] epoch 6 batch 150/1893, loss=0.0187, elapsed=112.9s
[CE_CLEAN_FULL_crop15] epoch 6 batch 175/1893, loss=0.0189, elapsed=130.5s
[CE_CLEAN_FULL_crop15] epoch 6 batch 200/1893, loss=0.0187, elapsed=148.1s
[CE_CLEAN_FULL_crop15] epoch 6 batch 225/1893, loss=0.0184, elapsed=168.6s
[CE_CLEAN_FULL_crop15] epoch 6 batch 250/1893, loss=0.0184, elapsed=186.9s
[CE_CLEAN_FULL_crop15] epoch 6 batch 275/1893, loss=0.0182, elapsed=203.7s
[CE_CLEAN_FULL_crop15] epoch 6 batch 300/1893, loss=0.0180, elapsed=222.1s
[CE_CLEAN_FULL_crop15] epoch 6 batch 325/1893, loss=0.0180, elapsed=240.2s
[CE_CLEAN_FULL_crop15] epoch 6 batch 350/1893, loss=0.0182, elapsed=258.3s
[CE_CLEAN_FULL_crop15] epoch 6 batch 375/1893, loss=0.0181, elapsed=276.6s
[CE_CLEAN_FULL_crop15] epoch 6 batch 400/1893, loss=0.0180, elapsed=294.3s
[CE_CLEAN_FULL_crop15] epoch 6 batch 425/1893, loss=0.0182, elapsed=312.2s
[CE_CLEAN_FULL_crop15] epoch 6 batch 450/1893, loss=0.0184, elapsed=330.2s
[CE_CLEAN_FULL_crop15] epoch 6 batch 475/1893, loss=0.0186, elapsed=350.0s
[CE_CLEAN_FULL_crop15] epoch 6 batch 500/1893, loss=0.0187, elapsed=368.8s
[CE_CLEAN_FULL_crop15] epoch 6 batch 525/1893, loss=0.0186, elapsed=385.8s
[CE_CLEAN_FULL_crop15] epoch 6 batch 550/1893, loss=0.0187, elapsed=404.1s
[CE_CLEAN_FULL_crop15] epoch 6 batch 575/1893, loss=0.0188, elapsed=422.6s
[CE_CLEAN_FULL_crop15] epoch 6 batch 600/1893, loss=0.0188, elapsed=441.3s
[CE_CLEAN_FULL_crop15] epoch 6 batch 625/1893, loss=0.0187, elapsed=458.8s
[CE_CLEAN_FULL_crop15] epoch 6 batch 650/1893, loss=0.0188, elapsed=477.0s
[CE_CLEAN_FULL_crop15] epoch 6 batch 675/1893, loss=0.0188, elapsed=495.2s
[CE_CLEAN_FULL_crop15] epoch 6 batch 700/1893, loss=0.0188, elapsed=514.9s
[CE_CLEAN_FULL_crop15] epoch 6 batch 725/1893, loss=0.0190, elapsed=533.9s
[CE_CLEAN_FULL_crop15] epoch 6 batch 750/1893, loss=0.0190, elapsed=551.7s
[CE_CLEAN_FULL_crop15] epoch 6 batch 775/1893, loss=0.0190, elapsed=569.4s
[CE_CLEAN_FULL_crop15] epoch 6 batch 800/1893, loss=0.0189, elapsed=589.7s
[CE_CLEAN_FULL_crop15] epoch 6 batch 825/1893, loss=0.0189, elapsed=607.5s
[CE_CLEAN_FULL_crop15] epoch 6 batch 850/1893, loss=0.0189, elapsed=626.0s
[CE_CLEAN_FULL_crop15] epoch 6 batch 875/1893, loss=0.0189, elapsed=643.7s
[CE_CLEAN_FULL_crop15] epoch 6 batch 900/1893, loss=0.0189, elapsed=664.4s
[CE_CLEAN_FULL_crop15] epoch 6 batch 925/1893, loss=0.0189, elapsed=683.4s
[CE_CLEAN_FULL_crop15] epoch 6 batch 950/1893, loss=0.0189, elapsed=702.4s
[CE_CLEAN_FULL_crop15] epoch 6 batch 975/1893, loss=0.0188, elapsed=722.4s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1000/1893, loss=0.0189, elapsed=744.0s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1025/1893, loss=0.0189, elapsed=762.5s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1050/1893, loss=0.0189, elapsed=780.8s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1075/1893, loss=0.0189, elapsed=800.8s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1100/1893, loss=0.0191, elapsed=823.1s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1125/1893, loss=0.0190, elapsed=842.2s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1150/1893, loss=0.0191, elapsed=863.6s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1175/1893, loss=0.0191, elapsed=883.0s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1200/1893, loss=0.0191, elapsed=905.3s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1225/1893, loss=0.0190, elapsed=925.6s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1250/1893, loss=0.0190, elapsed=945.0s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1275/1893, loss=0.0190, elapsed=964.2s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1300/1893, loss=0.0190, elapsed=985.6s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1325/1893, loss=0.0191, elapsed=1005.6s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1350/1893, loss=0.0190, elapsed=1026.8s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1375/1893, loss=0.0190, elapsed=1047.3s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1400/1893, loss=0.0190, elapsed=1067.1s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1425/1893, loss=0.0191, elapsed=1086.9s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1450/1893, loss=0.0191, elapsed=1108.7s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1475/1893, loss=0.0191, elapsed=1129.1s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1500/1893, loss=0.0190, elapsed=1148.0s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1525/1893, loss=0.0189, elapsed=1170.7s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1550/1893, loss=0.0189, elapsed=1191.3s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1575/1893, loss=0.0189, elapsed=1210.3s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1600/1893, loss=0.0189, elapsed=1230.6s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1625/1893, loss=0.0189, elapsed=1249.7s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1650/1893, loss=0.0188, elapsed=1270.6s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1675/1893, loss=0.0188, elapsed=1289.9s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1700/1893, loss=0.0188, elapsed=1308.8s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1725/1893, loss=0.0188, elapsed=1328.0s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1750/1893, loss=0.0188, elapsed=1348.9s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1775/1893, loss=0.0188, elapsed=1368.2s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1800/1893, loss=0.0188, elapsed=1388.6s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1825/1893, loss=0.0189, elapsed=1408.7s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1850/1893, loss=0.0189, elapsed=1429.7s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1875/1893, loss=0.0189, elapsed=1447.7s
[CE_CLEAN_FULL_crop15] epoch 6 batch 1893/1893, loss=0.0189, elapsed=1460.1s
[Inference] Starting 66379 scored images
[Inference] batch 1/260, elapsed=6.2s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 25/260, elapsed=38.6s
[Inference] batch 50/260, elapsed=69.2s
[Inference] batch 75/260, elapsed=102.6s
[Inference] batch 100/260, elapsed=135.8s
[Inference] batch 125/260, elapsed=171.6s
[Inference] batch 150/260, elapsed=208.5s
[Inference] batch 175/260, elapsed=241.6s
[Inference] batch 200/260, elapsed=273.5s
[Inference] batch 225/260, elapsed=306.6s
[Inference] batch 250/260, elapsed=344.7s
[Inference] batch 260/260, elapsed=355.1s
CE_CLEAN_FULL_crop15 epoch 6 Full Test-as-Val ACER 0.054119168033696534 best 5 patience 0
[CE_CLEAN_FULL_crop15] epoch 7/12 starting, warmup=False
[CE_CLEAN_FULL_crop15] epoch 7 batch 1/1893, loss=0.0058, elapsed=3.5s

/tmp/ipykernel_23/1895080082.py:312: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

[CE_CLEAN_FULL_crop15] epoch 7 batch 25/1893, loss=0.0164, elapsed=21.9s
[CE_CLEAN_FULL_crop15] epoch 7 batch 50/1893, loss=0.0185, elapsed=39.9s
[CE_CLEAN_FULL_crop15] epoch 7 batch 75/1893, loss=0.0167, elapsed=57.0s
[CE_CLEAN_FULL_crop15] epoch 7 batch 100/1893, loss=0.0170, elapsed=74.5s
[CE_CLEAN_FULL_crop15] epoch 7 batch 125/1893, loss=0.0182, elapsed=94.4s
[CE_CLEAN_FULL_crop15] epoch 7 batch 150/1893, loss=0.0175, elapsed=113.1s
[CE_CLEAN_FULL_crop15] epoch 7 batch 175/1893, loss=0.0184, elapsed=130.2s
[CE_CLEAN_FULL_crop15] epoch 7 batch 200/1893, loss=0.0187, elapsed=147.0s
[CE_CLEAN_FULL_crop15] epoch 7 batch 225/1893, loss=0.0184, elapsed=166.3s
[CE_CLEAN_FULL_crop15] epoch 7 batch 250/1893, loss=0.0185, elapsed=183.9s
[CE_CLEAN_FULL_crop15] epoch 7 batch 275/1893, loss=0.0183, elapsed=201.4s
[CE_CLEAN_FULL_crop15] epoch 7 batch 300/1893, loss=0.0183, elapsed=218.4s
[CE_CLEAN_FULL_crop15] epoch 7 batch 325/1893, loss=0.0181, elapsed=237.1s
[CE_CLEAN_FULL_crop15] epoch 7 batch 350/1893, loss=0.0179, elapsed=256.3s
[CE_CLEAN_FULL_crop15] epoch 7 batch 375/1893, loss=0.0180, elapsed=273.4s
[CE_CLEAN_FULL_crop15] epoch 7 batch 400/1893, loss=0.0180, elapsed=291.4s
[CE_CLEAN_FULL_crop15] epoch 7 batch 425/1893, loss=0.0178, elapsed=310.1s
[CE_CLEAN_FULL_crop15] epoch 7 batch 450/1893, loss=0.0180, elapsed=328.0s
[CE_CLEAN_FULL_crop15] epoch 7 batch 475/1893, loss=0.0179, elapsed=344.2s
[CE_CLEAN_FULL_crop15] epoch 7 batch 500/1893, loss=0.0179, elapsed=362.1s
[CE_CLEAN_FULL_crop15] epoch 7 batch 525/1893, loss=0.0180, elapsed=382.9s
[CE_CLEAN_FULL_crop15] epoch 7 batch 550/1893, loss=0.0179, elapsed=400.7s
[CE_CLEAN_FULL_crop15] epoch 7 batch 575/1893, loss=0.0180, elapsed=418.6s
[CE_CLEAN_FULL_crop15] epoch 7 batch 600/1893, loss=0.0180, elapsed=437.1s
[CE_CLEAN_FULL_crop15] epoch 7 batch 625/1893, loss=0.0181, elapsed=457.7s
[CE_CLEAN_FULL_crop15] epoch 7 batch 650/1893, loss=0.0180, elapsed=475.3s
[CE_CLEAN_FULL_crop15] epoch 7 batch 675/1893, loss=0.0179, elapsed=493.9s
[CE_CLEAN_FULL_crop15] epoch 7 batch 700/1893, loss=0.0179, elapsed=511.5s
[CE_CLEAN_FULL_crop15] epoch 7 batch 725/1893, loss=0.0178, elapsed=533.4s
[CE_CLEAN_FULL_crop15] epoch 7 batch 750/1893, loss=0.0177, elapsed=551.1s
[CE_CLEAN_FULL_crop15] epoch 7 batch 775/1893, loss=0.0177, elapsed=569.2s
[CE_CLEAN_FULL_crop15] epoch 7 batch 800/1893, loss=0.0176, elapsed=586.9s
[CE_CLEAN_FULL_crop15] epoch 7 batch 825/1893, loss=0.0177, elapsed=607.2s
[CE_CLEAN_FULL_crop15] epoch 7 batch 850/1893, loss=0.0177, elapsed=624.6s
[CE_CLEAN_FULL_crop15] epoch 7 batch 875/1893, loss=0.0177, elapsed=642.3s
[CE_CLEAN_FULL_crop15] epoch 7 batch 900/1893, loss=0.0176, elapsed=660.5s
[CE_CLEAN_FULL_crop15] epoch 7 batch 925/1893, loss=0.0176, elapsed=679.9s
[CE_CLEAN_FULL_crop15] epoch 7 batch 950/1893, loss=0.0176, elapsed=697.4s
[CE_CLEAN_FULL_crop15] epoch 7 batch 975/1893, loss=0.0176, elapsed=715.4s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1000/1893, loss=0.0176, elapsed=735.1s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1025/1893, loss=0.0175, elapsed=756.3s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1050/1893, loss=0.0175, elapsed=774.7s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1075/1893, loss=0.0174, elapsed=794.8s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1100/1893, loss=0.0174, elapsed=814.9s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1125/1893, loss=0.0174, elapsed=836.8s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1150/1893, loss=0.0174, elapsed=855.2s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1175/1893, loss=0.0173, elapsed=872.6s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1200/1893, loss=0.0173, elapsed=890.2s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1225/1893, loss=0.0173, elapsed=912.1s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1250/1893, loss=0.0173, elapsed=931.7s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1275/1893, loss=0.0172, elapsed=949.6s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1300/1893, loss=0.0172, elapsed=967.3s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1325/1893, loss=0.0171, elapsed=987.8s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1350/1893, loss=0.0172, elapsed=1005.2s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1375/1893, loss=0.0171, elapsed=1022.6s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1400/1893, loss=0.0170, elapsed=1040.3s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1425/1893, loss=0.0171, elapsed=1060.3s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1450/1893, loss=0.0171, elapsed=1078.3s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1475/1893, loss=0.0171, elapsed=1096.3s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1500/1893, loss=0.0171, elapsed=1114.0s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1525/1893, loss=0.0172, elapsed=1134.4s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1550/1893, loss=0.0172, elapsed=1152.2s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1575/1893, loss=0.0172, elapsed=1169.4s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1600/1893, loss=0.0172, elapsed=1186.9s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1625/1893, loss=0.0172, elapsed=1206.9s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1650/1893, loss=0.0173, elapsed=1226.0s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1675/1893, loss=0.0173, elapsed=1244.7s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1700/1893, loss=0.0173, elapsed=1262.3s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1725/1893, loss=0.0173, elapsed=1282.2s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1750/1893, loss=0.0173, elapsed=1299.8s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1775/1893, loss=0.0173, elapsed=1317.2s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1800/1893, loss=0.0172, elapsed=1335.7s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1825/1893, loss=0.0172, elapsed=1358.0s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1850/1893, loss=0.0173, elapsed=1378.0s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1875/1893, loss=0.0172, elapsed=1395.9s
[CE_CLEAN_FULL_crop15] epoch 7 batch 1893/1893, loss=0.0172, elapsed=1409.8s
[Inference] Starting 66379 scored images
[Inference] batch 1/260, elapsed=6.1s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 25/260, elapsed=36.0s
[Inference] batch 50/260, elapsed=66.0s
[Inference] batch 75/260, elapsed=101.1s
[Inference] batch 100/260, elapsed=134.1s
[Inference] batch 125/260, elapsed=168.9s
[Inference] batch 150/260, elapsed=203.8s
[Inference] batch 175/260, elapsed=235.8s
[Inference] batch 200/260, elapsed=266.7s
[Inference] batch 225/260, elapsed=298.0s
[Inference] batch 250/260, elapsed=334.5s
[Inference] batch 260/260, elapsed=344.7s
CE_CLEAN_FULL_crop15 epoch 7 Full Test-as-Val ACER 0.04815962021267353 best 7 patience 0
[CE_CLEAN_FULL_crop15] epoch 8/12 starting, warmup=False
[CE_CLEAN_FULL_crop15] epoch 8 batch 1/1893, loss=0.0412, elapsed=3.3s

/tmp/ipykernel_23/1895080082.py:312: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

[CE_CLEAN_FULL_crop15] epoch 8 batch 25/1893, loss=0.0213, elapsed=20.0s
[CE_CLEAN_FULL_crop15] epoch 8 batch 50/1893, loss=0.0202, elapsed=39.1s
[CE_CLEAN_FULL_crop15] epoch 8 batch 75/1893, loss=0.0198, elapsed=56.0s
[CE_CLEAN_FULL_crop15] epoch 8 batch 100/1893, loss=0.0186, elapsed=73.4s
[CE_CLEAN_FULL_crop15] epoch 8 batch 125/1893, loss=0.0187, elapsed=92.9s
[CE_CLEAN_FULL_crop15] epoch 8 batch 150/1893, loss=0.0182, elapsed=109.7s
[CE_CLEAN_FULL_crop15] epoch 8 batch 175/1893, loss=0.0181, elapsed=126.2s
[CE_CLEAN_FULL_crop15] epoch 8 batch 200/1893, loss=0.0178, elapsed=143.2s
[CE_CLEAN_FULL_crop15] epoch 8 batch 225/1893, loss=0.0174, elapsed=162.9s
[CE_CLEAN_FULL_crop15] epoch 8 batch 250/1893, loss=0.0172, elapsed=180.1s
[CE_CLEAN_FULL_crop15] epoch 8 batch 275/1893, loss=0.0171, elapsed=197.1s
[CE_CLEAN_FULL_crop15] epoch 8 batch 300/1893, loss=0.0170, elapsed=215.3s
[CE_CLEAN_FULL_crop15] epoch 8 batch 325/1893, loss=0.0170, elapsed=236.6s
[CE_CLEAN_FULL_crop15] epoch 8 batch 350/1893, loss=0.0172, elapsed=253.5s
[CE_CLEAN_FULL_crop15] epoch 8 batch 375/1893, loss=0.0169, elapsed=272.7s
[CE_CLEAN_FULL_crop15] epoch 8 batch 400/1893, loss=0.0169, elapsed=292.8s
[CE_CLEAN_FULL_crop15] epoch 8 batch 425/1893, loss=0.0169, elapsed=314.3s
[CE_CLEAN_FULL_crop15] epoch 8 batch 450/1893, loss=0.0166, elapsed=334.3s
[CE_CLEAN_FULL_crop15] epoch 8 batch 475/1893, loss=0.0166, elapsed=352.9s
[CE_CLEAN_FULL_crop15] epoch 8 batch 500/1893, loss=0.0165, elapsed=371.2s
[CE_CLEAN_FULL_crop15] epoch 8 batch 525/1893, loss=0.0164, elapsed=393.3s
[CE_CLEAN_FULL_crop15] epoch 8 batch 550/1893, loss=0.0164, elapsed=412.9s
[CE_CLEAN_FULL_crop15] epoch 8 batch 575/1893, loss=0.0165, elapsed=432.0s
[CE_CLEAN_FULL_crop15] epoch 8 batch 600/1893, loss=0.0166, elapsed=451.5s
[CE_CLEAN_FULL_crop15] epoch 8 batch 625/1893, loss=0.0167, elapsed=474.1s
[CE_CLEAN_FULL_crop15] epoch 8 batch 650/1893, loss=0.0167, elapsed=493.0s
[CE_CLEAN_FULL_crop15] epoch 8 batch 675/1893, loss=0.0167, elapsed=511.7s
[CE_CLEAN_FULL_crop15] epoch 8 batch 700/1893, loss=0.0168, elapsed=529.3s
[CE_CLEAN_FULL_crop15] epoch 8 batch 725/1893, loss=0.0168, elapsed=551.2s
[CE_CLEAN_FULL_crop15] epoch 8 batch 750/1893, loss=0.0168, elapsed=569.2s
[CE_CLEAN_FULL_crop15] epoch 8 batch 775/1893, loss=0.0167, elapsed=587.2s
[CE_CLEAN_FULL_crop15] epoch 8 batch 800/1893, loss=0.0168, elapsed=606.9s
[CE_CLEAN_FULL_crop15] epoch 8 batch 825/1893, loss=0.0169, elapsed=626.3s
[CE_CLEAN_FULL_crop15] epoch 8 batch 850/1893, loss=0.0170, elapsed=644.1s
[CE_CLEAN_FULL_crop15] epoch 8 batch 875/1893, loss=0.0169, elapsed=661.5s
[CE_CLEAN_FULL_crop15] epoch 8 batch 900/1893, loss=0.0170, elapsed=678.5s
[CE_CLEAN_FULL_crop15] epoch 8 batch 925/1893, loss=0.0170, elapsed=697.7s
[CE_CLEAN_FULL_crop15] epoch 8 batch 950/1893, loss=0.0170, elapsed=715.3s
[CE_CLEAN_FULL_crop15] epoch 8 batch 975/1893, loss=0.0169, elapsed=732.9s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1000/1893, loss=0.0168, elapsed=750.0s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1025/1893, loss=0.0168, elapsed=769.9s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1050/1893, loss=0.0167, elapsed=787.0s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1075/1893, loss=0.0168, elapsed=804.9s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1100/1893, loss=0.0168, elapsed=823.3s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1125/1893, loss=0.0168, elapsed=844.6s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1150/1893, loss=0.0167, elapsed=862.2s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1175/1893, loss=0.0167, elapsed=879.4s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1200/1893, loss=0.0166, elapsed=898.7s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1225/1893, loss=0.0167, elapsed=916.7s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1250/1893, loss=0.0167, elapsed=935.2s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1275/1893, loss=0.0166, elapsed=953.2s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1300/1893, loss=0.0166, elapsed=972.0s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1325/1893, loss=0.0165, elapsed=992.1s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1350/1893, loss=0.0166, elapsed=1011.2s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1375/1893, loss=0.0166, elapsed=1030.1s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1400/1893, loss=0.0166, elapsed=1047.9s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1425/1893, loss=0.0166, elapsed=1066.9s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1450/1893, loss=0.0166, elapsed=1084.6s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1475/1893, loss=0.0166, elapsed=1101.1s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1500/1893, loss=0.0166, elapsed=1119.0s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1525/1893, loss=0.0166, elapsed=1139.6s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1550/1893, loss=0.0166, elapsed=1158.2s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1575/1893, loss=0.0167, elapsed=1176.6s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1600/1893, loss=0.0166, elapsed=1195.6s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1625/1893, loss=0.0168, elapsed=1217.9s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1650/1893, loss=0.0167, elapsed=1238.9s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1675/1893, loss=0.0168, elapsed=1258.0s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1700/1893, loss=0.0167, elapsed=1276.7s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1725/1893, loss=0.0168, elapsed=1295.9s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1750/1893, loss=0.0167, elapsed=1314.5s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1775/1893, loss=0.0168, elapsed=1332.8s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1800/1893, loss=0.0168, elapsed=1350.6s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1825/1893, loss=0.0168, elapsed=1371.1s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1850/1893, loss=0.0168, elapsed=1388.9s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1875/1893, loss=0.0168, elapsed=1407.6s
[CE_CLEAN_FULL_crop15] epoch 8 batch 1893/1893, loss=0.0168, elapsed=1420.5s
[Inference] Starting 66379 scored images
[Inference] batch 1/260, elapsed=6.2s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 25/260, elapsed=40.2s
[Inference] batch 50/260, elapsed=71.7s
[Inference] batch 75/260, elapsed=105.9s
[Inference] batch 100/260, elapsed=138.5s
[Inference] batch 125/260, elapsed=174.3s
[Inference] batch 150/260, elapsed=209.7s
[Inference] batch 175/260, elapsed=245.0s
[Inference] batch 200/260, elapsed=280.9s
[Inference] batch 225/260, elapsed=319.3s
[Inference] batch 250/260, elapsed=358.9s
[Inference] batch 260/260, elapsed=371.1s
CE_CLEAN_FULL_crop15 epoch 8 Full Test-as-Val ACER 0.045666691732308126 best 8 patience 0
[CE_CLEAN_FULL_crop15] epoch 9/12 starting, warmup=False
[CE_CLEAN_FULL_crop15] epoch 9 batch 1/1893, loss=0.0135, elapsed=4.4s

/tmp/ipykernel_23/1895080082.py:312: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

[CE_CLEAN_FULL_crop15] epoch 9 batch 25/1893, loss=0.0177, elapsed=26.0s
[CE_CLEAN_FULL_crop15] epoch 9 batch 50/1893, loss=0.0149, elapsed=46.0s
[CE_CLEAN_FULL_crop15] epoch 9 batch 75/1893, loss=0.0161, elapsed=66.3s
[CE_CLEAN_FULL_crop15] epoch 9 batch 100/1893, loss=0.0166, elapsed=86.5s
[CE_CLEAN_FULL_crop15] epoch 9 batch 125/1893, loss=0.0163, elapsed=111.4s
[CE_CLEAN_FULL_crop15] epoch 9 batch 150/1893, loss=0.0159, elapsed=131.2s
[CE_CLEAN_FULL_crop15] epoch 9 batch 175/1893, loss=0.0157, elapsed=151.2s
[CE_CLEAN_FULL_crop15] epoch 9 batch 200/1893, loss=0.0151, elapsed=169.7s
[CE_CLEAN_FULL_crop15] epoch 9 batch 225/1893, loss=0.0150, elapsed=189.8s
[CE_CLEAN_FULL_crop15] epoch 9 batch 250/1893, loss=0.0150, elapsed=207.8s
[CE_CLEAN_FULL_crop15] epoch 9 batch 275/1893, loss=0.0151, elapsed=226.7s
[CE_CLEAN_FULL_crop15] epoch 9 batch 300/1893, loss=0.0150, elapsed=246.8s
[CE_CLEAN_FULL_crop15] epoch 9 batch 325/1893, loss=0.0151, elapsed=270.6s
[CE_CLEAN_FULL_crop15] epoch 9 batch 350/1893, loss=0.0153, elapsed=291.8s
[CE_CLEAN_FULL_crop15] epoch 9 batch 375/1893, loss=0.0154, elapsed=312.2s
[CE_CLEAN_FULL_crop15] epoch 9 batch 400/1893, loss=0.0152, elapsed=331.4s
[CE_CLEAN_FULL_crop15] epoch 9 batch 425/1893, loss=0.0151, elapsed=351.5s
[CE_CLEAN_FULL_crop15] epoch 9 batch 450/1893, loss=0.0149, elapsed=369.7s
[CE_CLEAN_FULL_crop15] epoch 9 batch 475/1893, loss=0.0150, elapsed=388.4s
[CE_CLEAN_FULL_crop15] epoch 9 batch 500/1893, loss=0.0150, elapsed=407.5s
[CE_CLEAN_FULL_crop15] epoch 9 batch 525/1893, loss=0.0149, elapsed=427.0s
[CE_CLEAN_FULL_crop15] epoch 9 batch 550/1893, loss=0.0150, elapsed=445.6s
[CE_CLEAN_FULL_crop15] epoch 9 batch 575/1893, loss=0.0152, elapsed=465.5s
[CE_CLEAN_FULL_crop15] epoch 9 batch 600/1893, loss=0.0152, elapsed=483.3s
[CE_CLEAN_FULL_crop15] epoch 9 batch 625/1893, loss=0.0151, elapsed=500.8s
[CE_CLEAN_FULL_crop15] epoch 9 batch 650/1893, loss=0.0149, elapsed=519.5s
[CE_CLEAN_FULL_crop15] epoch 9 batch 675/1893, loss=0.0149, elapsed=539.5s
[CE_CLEAN_FULL_crop15] epoch 9 batch 700/1893, loss=0.0150, elapsed=557.5s
[CE_CLEAN_FULL_crop15] epoch 9 batch 725/1893, loss=0.0149, elapsed=575.7s
[CE_CLEAN_FULL_crop15] epoch 9 batch 750/1893, loss=0.0148, elapsed=594.8s
[CE_CLEAN_FULL_crop15] epoch 9 batch 775/1893, loss=0.0147, elapsed=616.0s
[CE_CLEAN_FULL_crop15] epoch 9 batch 800/1893, loss=0.0147, elapsed=633.8s
[CE_CLEAN_FULL_crop15] epoch 9 batch 825/1893, loss=0.0148, elapsed=651.5s
[CE_CLEAN_FULL_crop15] epoch 9 batch 850/1893, loss=0.0149, elapsed=670.2s
[CE_CLEAN_FULL_crop15] epoch 9 batch 875/1893, loss=0.0148, elapsed=691.7s
[CE_CLEAN_FULL_crop15] epoch 9 batch 900/1893, loss=0.0148, elapsed=710.3s
[CE_CLEAN_FULL_crop15] epoch 9 batch 925/1893, loss=0.0148, elapsed=730.0s
[CE_CLEAN_FULL_crop15] epoch 9 batch 950/1893, loss=0.0148, elapsed=748.7s
[CE_CLEAN_FULL_crop15] epoch 9 batch 975/1893, loss=0.0147, elapsed=769.5s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1000/1893, loss=0.0146, elapsed=788.1s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1025/1893, loss=0.0147, elapsed=805.6s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1050/1893, loss=0.0147, elapsed=822.7s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1075/1893, loss=0.0146, elapsed=844.0s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1100/1893, loss=0.0146, elapsed=861.8s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1125/1893, loss=0.0145, elapsed=880.7s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1150/1893, loss=0.0145, elapsed=898.6s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1175/1893, loss=0.0146, elapsed=919.8s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1200/1893, loss=0.0147, elapsed=938.5s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1225/1893, loss=0.0146, elapsed=956.9s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1250/1893, loss=0.0146, elapsed=974.5s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1275/1893, loss=0.0146, elapsed=994.5s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1300/1893, loss=0.0146, elapsed=1013.3s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1325/1893, loss=0.0145, elapsed=1031.6s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1350/1893, loss=0.0144, elapsed=1051.7s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1375/1893, loss=0.0144, elapsed=1072.4s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1400/1893, loss=0.0144, elapsed=1090.0s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1425/1893, loss=0.0144, elapsed=1107.4s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1450/1893, loss=0.0144, elapsed=1125.3s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1475/1893, loss=0.0144, elapsed=1146.0s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1500/1893, loss=0.0144, elapsed=1163.9s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1525/1893, loss=0.0143, elapsed=1181.7s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1550/1893, loss=0.0143, elapsed=1200.2s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1575/1893, loss=0.0143, elapsed=1221.4s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1600/1893, loss=0.0142, elapsed=1239.7s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1625/1893, loss=0.0142, elapsed=1257.7s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1650/1893, loss=0.0143, elapsed=1276.1s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1675/1893, loss=0.0142, elapsed=1297.3s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1700/1893, loss=0.0142, elapsed=1315.5s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1725/1893, loss=0.0142, elapsed=1333.5s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1750/1893, loss=0.0142, elapsed=1353.1s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1775/1893, loss=0.0142, elapsed=1371.3s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1800/1893, loss=0.0142, elapsed=1389.3s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1825/1893, loss=0.0142, elapsed=1411.3s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1850/1893, loss=0.0142, elapsed=1430.8s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1875/1893, loss=0.0142, elapsed=1449.2s
[CE_CLEAN_FULL_crop15] epoch 9 batch 1893/1893, loss=0.0141, elapsed=1461.2s
[Inference] Starting 66379 scored images
[Inference] batch 1/260, elapsed=5.9s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 25/260, elapsed=36.9s
[Inference] batch 50/260, elapsed=68.2s
[Inference] batch 75/260, elapsed=103.1s
[Inference] batch 100/260, elapsed=139.4s
[Inference] batch 125/260, elapsed=174.8s
[Inference] batch 150/260, elapsed=208.4s
[Inference] batch 175/260, elapsed=239.4s
[Inference] batch 200/260, elapsed=269.6s
[Inference] batch 225/260, elapsed=302.1s
[Inference] batch 250/260, elapsed=337.5s
[Inference] batch 260/260, elapsed=347.8s
CE_CLEAN_FULL_crop15 epoch 9 Full Test-as-Val ACER 0.04800142419598059 best 8 patience 1
[CE_CLEAN_FULL_crop15] epoch 10/12 starting, warmup=False
[CE_CLEAN_FULL_crop15] epoch 10 batch 1/1893, loss=0.0188, elapsed=3.5s

/tmp/ipykernel_23/1895080082.py:312: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

[CE_CLEAN_FULL_crop15] epoch 10 batch 25/1893, loss=0.0117, elapsed=22.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 50/1893, loss=0.0113, elapsed=41.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 75/1893, loss=0.0128, elapsed=58.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 100/1893, loss=0.0123, elapsed=74.9s
[CE_CLEAN_FULL_crop15] epoch 10 batch 125/1893, loss=0.0127, elapsed=95.2s
[CE_CLEAN_FULL_crop15] epoch 10 batch 150/1893, loss=0.0134, elapsed=112.6s
[CE_CLEAN_FULL_crop15] epoch 10 batch 175/1893, loss=0.0133, elapsed=131.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 200/1893, loss=0.0134, elapsed=148.3s
[CE_CLEAN_FULL_crop15] epoch 10 batch 225/1893, loss=0.0132, elapsed=168.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 250/1893, loss=0.0133, elapsed=186.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 275/1893, loss=0.0133, elapsed=203.8s
[CE_CLEAN_FULL_crop15] epoch 10 batch 300/1893, loss=0.0131, elapsed=221.5s
[CE_CLEAN_FULL_crop15] epoch 10 batch 325/1893, loss=0.0131, elapsed=240.9s
[CE_CLEAN_FULL_crop15] epoch 10 batch 350/1893, loss=0.0130, elapsed=258.7s
[CE_CLEAN_FULL_crop15] epoch 10 batch 375/1893, loss=0.0130, elapsed=276.4s
[CE_CLEAN_FULL_crop15] epoch 10 batch 400/1893, loss=0.0130, elapsed=293.8s
[CE_CLEAN_FULL_crop15] epoch 10 batch 425/1893, loss=0.0130, elapsed=314.2s
[CE_CLEAN_FULL_crop15] epoch 10 batch 450/1893, loss=0.0130, elapsed=332.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 475/1893, loss=0.0129, elapsed=351.6s
[CE_CLEAN_FULL_crop15] epoch 10 batch 500/1893, loss=0.0131, elapsed=370.6s
[CE_CLEAN_FULL_crop15] epoch 10 batch 525/1893, loss=0.0132, elapsed=389.3s
[CE_CLEAN_FULL_crop15] epoch 10 batch 550/1893, loss=0.0131, elapsed=406.2s
[CE_CLEAN_FULL_crop15] epoch 10 batch 575/1893, loss=0.0131, elapsed=426.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 600/1893, loss=0.0132, elapsed=443.7s
[CE_CLEAN_FULL_crop15] epoch 10 batch 625/1893, loss=0.0132, elapsed=463.0s
[CE_CLEAN_FULL_crop15] epoch 10 batch 650/1893, loss=0.0132, elapsed=480.4s
[CE_CLEAN_FULL_crop15] epoch 10 batch 675/1893, loss=0.0132, elapsed=500.4s
[CE_CLEAN_FULL_crop15] epoch 10 batch 700/1893, loss=0.0131, elapsed=520.3s
[CE_CLEAN_FULL_crop15] epoch 10 batch 725/1893, loss=0.0131, elapsed=539.2s
[CE_CLEAN_FULL_crop15] epoch 10 batch 750/1893, loss=0.0133, elapsed=557.5s
[CE_CLEAN_FULL_crop15] epoch 10 batch 775/1893, loss=0.0133, elapsed=578.4s
[CE_CLEAN_FULL_crop15] epoch 10 batch 800/1893, loss=0.0133, elapsed=598.4s
[CE_CLEAN_FULL_crop15] epoch 10 batch 825/1893, loss=0.0133, elapsed=616.6s
[CE_CLEAN_FULL_crop15] epoch 10 batch 850/1893, loss=0.0133, elapsed=636.4s
[CE_CLEAN_FULL_crop15] epoch 10 batch 875/1893, loss=0.0133, elapsed=657.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 900/1893, loss=0.0133, elapsed=675.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 925/1893, loss=0.0133, elapsed=695.4s
[CE_CLEAN_FULL_crop15] epoch 10 batch 950/1893, loss=0.0134, elapsed=715.0s
[CE_CLEAN_FULL_crop15] epoch 10 batch 975/1893, loss=0.0134, elapsed=734.4s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1000/1893, loss=0.0134, elapsed=751.9s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1025/1893, loss=0.0134, elapsed=771.7s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1050/1893, loss=0.0134, elapsed=789.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1075/1893, loss=0.0135, elapsed=807.0s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1100/1893, loss=0.0136, elapsed=826.4s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1125/1893, loss=0.0136, elapsed=848.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1150/1893, loss=0.0136, elapsed=865.6s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1175/1893, loss=0.0136, elapsed=885.3s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1200/1893, loss=0.0136, elapsed=903.5s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1225/1893, loss=0.0136, elapsed=922.7s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1250/1893, loss=0.0136, elapsed=942.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1275/1893, loss=0.0136, elapsed=963.8s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1300/1893, loss=0.0135, elapsed=982.3s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1325/1893, loss=0.0135, elapsed=1001.6s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1350/1893, loss=0.0135, elapsed=1020.0s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1375/1893, loss=0.0135, elapsed=1041.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1400/1893, loss=0.0135, elapsed=1059.0s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1425/1893, loss=0.0135, elapsed=1077.0s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1450/1893, loss=0.0135, elapsed=1095.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1475/1893, loss=0.0135, elapsed=1115.6s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1500/1893, loss=0.0135, elapsed=1132.7s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1525/1893, loss=0.0135, elapsed=1151.4s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1550/1893, loss=0.0135, elapsed=1169.5s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1575/1893, loss=0.0135, elapsed=1189.8s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1600/1893, loss=0.0135, elapsed=1208.6s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1625/1893, loss=0.0135, elapsed=1229.0s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1650/1893, loss=0.0135, elapsed=1249.9s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1675/1893, loss=0.0134, elapsed=1273.8s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1700/1893, loss=0.0135, elapsed=1294.3s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1725/1893, loss=0.0134, elapsed=1314.2s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1750/1893, loss=0.0135, elapsed=1334.7s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1775/1893, loss=0.0134, elapsed=1358.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1800/1893, loss=0.0134, elapsed=1378.1s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1825/1893, loss=0.0134, elapsed=1398.3s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1850/1893, loss=0.0135, elapsed=1417.6s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1875/1893, loss=0.0135, elapsed=1438.4s
[CE_CLEAN_FULL_crop15] epoch 10 batch 1893/1893, loss=0.0135, elapsed=1451.0s
[Inference] Starting 66379 scored images
[Inference] batch 1/260, elapsed=6.2s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 25/260, elapsed=40.8s
[Inference] batch 50/260, elapsed=71.1s
[Inference] batch 75/260, elapsed=103.9s
[Inference] batch 100/260, elapsed=139.3s
[Inference] batch 125/260, elapsed=174.8s
[Inference] batch 150/260, elapsed=209.2s
[Inference] batch 175/260, elapsed=241.6s
[Inference] batch 200/260, elapsed=274.2s
[Inference] batch 225/260, elapsed=307.3s
[Inference] batch 250/260, elapsed=344.6s
[Inference] batch 260/260, elapsed=355.6s
CE_CLEAN_FULL_crop15 epoch 10 Full Test-as-Val ACER 0.04529020006148225 best 10 patience 0
[CE_CLEAN_FULL_crop15] epoch 11/12 starting, warmup=False
[CE_CLEAN_FULL_crop15] epoch 11 batch 1/1893, loss=0.0257, elapsed=3.6s

/tmp/ipykernel_23/1895080082.py:312: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

[CE_CLEAN_FULL_crop15] epoch 11 batch 25/1893, loss=0.0115, elapsed=22.5s
[CE_CLEAN_FULL_crop15] epoch 11 batch 50/1893, loss=0.0129, elapsed=40.7s
[CE_CLEAN_FULL_crop15] epoch 11 batch 75/1893, loss=0.0132, elapsed=59.2s
[CE_CLEAN_FULL_crop15] epoch 11 batch 100/1893, loss=0.0127, elapsed=77.2s
[CE_CLEAN_FULL_crop15] epoch 11 batch 125/1893, loss=0.0127, elapsed=95.4s
[CE_CLEAN_FULL_crop15] epoch 11 batch 150/1893, loss=0.0130, elapsed=114.7s
[CE_CLEAN_FULL_crop15] epoch 11 batch 175/1893, loss=0.0129, elapsed=134.7s
[CE_CLEAN_FULL_crop15] epoch 11 batch 200/1893, loss=0.0126, elapsed=153.2s
[CE_CLEAN_FULL_crop15] epoch 11 batch 225/1893, loss=0.0128, elapsed=170.6s
[CE_CLEAN_FULL_crop15] epoch 11 batch 250/1893, loss=0.0129, elapsed=188.2s
[CE_CLEAN_FULL_crop15] epoch 11 batch 275/1893, loss=0.0130, elapsed=206.5s
[CE_CLEAN_FULL_crop15] epoch 11 batch 300/1893, loss=0.0132, elapsed=227.0s
[CE_CLEAN_FULL_crop15] epoch 11 batch 325/1893, loss=0.0133, elapsed=244.9s
[CE_CLEAN_FULL_crop15] epoch 11 batch 350/1893, loss=0.0130, elapsed=262.9s
[CE_CLEAN_FULL_crop15] epoch 11 batch 375/1893, loss=0.0131, elapsed=283.5s
[CE_CLEAN_FULL_crop15] epoch 11 batch 400/1893, loss=0.0132, elapsed=302.9s
[CE_CLEAN_FULL_crop15] epoch 11 batch 425/1893, loss=0.0132, elapsed=320.4s
[CE_CLEAN_FULL_crop15] epoch 11 batch 450/1893, loss=0.0131, elapsed=338.3s
[CE_CLEAN_FULL_crop15] epoch 11 batch 475/1893, loss=0.0131, elapsed=357.4s
[CE_CLEAN_FULL_crop15] epoch 11 batch 500/1893, loss=0.0131, elapsed=376.8s
[CE_CLEAN_FULL_crop15] epoch 11 batch 525/1893, loss=0.0132, elapsed=394.3s
[CE_CLEAN_FULL_crop15] epoch 11 batch 550/1893, loss=0.0132, elapsed=413.5s
[CE_CLEAN_FULL_crop15] epoch 11 batch 575/1893, loss=0.0133, elapsed=432.9s
[CE_CLEAN_FULL_crop15] epoch 11 batch 600/1893, loss=0.0132, elapsed=451.9s
[CE_CLEAN_FULL_crop15] epoch 11 batch 625/1893, loss=0.0131, elapsed=470.1s
[CE_CLEAN_FULL_crop15] epoch 11 batch 650/1893, loss=0.0131, elapsed=488.2s
[CE_CLEAN_FULL_crop15] epoch 11 batch 675/1893, loss=0.0131, elapsed=508.6s
[CE_CLEAN_FULL_crop15] epoch 11 batch 700/1893, loss=0.0131, elapsed=527.0s
[CE_CLEAN_FULL_crop15] epoch 11 batch 725/1893, loss=0.0131, elapsed=544.7s
[CE_CLEAN_FULL_crop15] epoch 11 batch 750/1893, loss=0.0130, elapsed=563.1s
[CE_CLEAN_FULL_crop15] epoch 11 batch 775/1893, loss=0.0131, elapsed=583.0s
[CE_CLEAN_FULL_crop15] epoch 11 batch 800/1893, loss=0.0130, elapsed=601.0s
[CE_CLEAN_FULL_crop15] epoch 11 batch 825/1893, loss=0.0130, elapsed=619.4s
[CE_CLEAN_FULL_crop15] epoch 11 batch 850/1893, loss=0.0130, elapsed=638.8s
[CE_CLEAN_FULL_crop15] epoch 11 batch 875/1893, loss=0.0130, elapsed=661.9s
[CE_CLEAN_FULL_crop15] epoch 11 batch 900/1893, loss=0.0130, elapsed=679.4s
[CE_CLEAN_FULL_crop15] epoch 11 batch 925/1893, loss=0.0130, elapsed=697.5s
[CE_CLEAN_FULL_crop15] epoch 11 batch 950/1893, loss=0.0130, elapsed=716.5s
[CE_CLEAN_FULL_crop15] epoch 11 batch 975/1893, loss=0.0131, elapsed=736.0s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1000/1893, loss=0.0130, elapsed=754.7s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1025/1893, loss=0.0132, elapsed=774.8s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1050/1893, loss=0.0132, elapsed=796.4s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1075/1893, loss=0.0131, elapsed=817.3s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1100/1893, loss=0.0131, elapsed=835.6s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1125/1893, loss=0.0132, elapsed=852.8s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1150/1893, loss=0.0131, elapsed=872.0s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1175/1893, loss=0.0131, elapsed=890.6s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1200/1893, loss=0.0131, elapsed=909.2s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1225/1893, loss=0.0132, elapsed=927.1s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1250/1893, loss=0.0132, elapsed=946.7s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1275/1893, loss=0.0131, elapsed=965.0s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1300/1893, loss=0.0131, elapsed=983.0s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1325/1893, loss=0.0131, elapsed=1000.8s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1350/1893, loss=0.0130, elapsed=1019.9s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1375/1893, loss=0.0130, elapsed=1039.4s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1400/1893, loss=0.0130, elapsed=1058.0s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1425/1893, loss=0.0130, elapsed=1076.7s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1450/1893, loss=0.0129, elapsed=1097.8s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1475/1893, loss=0.0129, elapsed=1116.8s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1500/1893, loss=0.0129, elapsed=1134.3s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1525/1893, loss=0.0130, elapsed=1152.7s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1550/1893, loss=0.0130, elapsed=1173.9s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1575/1893, loss=0.0129, elapsed=1191.9s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1600/1893, loss=0.0130, elapsed=1209.6s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1625/1893, loss=0.0130, elapsed=1228.5s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1650/1893, loss=0.0130, elapsed=1248.9s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1675/1893, loss=0.0130, elapsed=1266.8s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1700/1893, loss=0.0129, elapsed=1285.7s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1725/1893, loss=0.0130, elapsed=1305.0s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1750/1893, loss=0.0130, elapsed=1324.9s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1775/1893, loss=0.0130, elapsed=1343.8s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1800/1893, loss=0.0130, elapsed=1365.6s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1825/1893, loss=0.0130, elapsed=1388.6s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1850/1893, loss=0.0130, elapsed=1408.8s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1875/1893, loss=0.0130, elapsed=1428.6s
[CE_CLEAN_FULL_crop15] epoch 11 batch 1893/1893, loss=0.0130, elapsed=1442.4s
[Inference] Starting 66379 scored images
[Inference] batch 1/260, elapsed=5.9s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 25/260, elapsed=36.7s
[Inference] batch 50/260, elapsed=66.1s
[Inference] batch 75/260, elapsed=99.2s
[Inference] batch 100/260, elapsed=131.1s
[Inference] batch 125/260, elapsed=166.9s
[Inference] batch 150/260, elapsed=202.4s
[Inference] batch 175/260, elapsed=234.9s
[Inference] batch 200/260, elapsed=266.0s
[Inference] batch 225/260, elapsed=299.2s
[Inference] batch 250/260, elapsed=334.8s
[Inference] batch 260/260, elapsed=345.1s
CE_CLEAN_FULL_crop15 epoch 11 Full Test-as-Val ACER 0.04406433488666715 best 11 patience 0
[CE_CLEAN_FULL_crop15] epoch 12/12 starting, warmup=False
[CE_CLEAN_FULL_crop15] epoch 12 batch 1/1893, loss=0.0267, elapsed=4.0s

/tmp/ipykernel_23/1895080082.py:312: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):

[CE_CLEAN_FULL_crop15] epoch 12 batch 25/1893, loss=0.0107, elapsed=20.8s
[CE_CLEAN_FULL_crop15] epoch 12 batch 50/1893, loss=0.0107, elapsed=39.0s
[CE_CLEAN_FULL_crop15] epoch 12 batch 75/1893, loss=0.0114, elapsed=56.6s
[CE_CLEAN_FULL_crop15] epoch 12 batch 100/1893, loss=0.0114, elapsed=75.0s
[CE_CLEAN_FULL_crop15] epoch 12 batch 125/1893, loss=0.0117, elapsed=94.9s
[CE_CLEAN_FULL_crop15] epoch 12 batch 150/1893, loss=0.0122, elapsed=114.7s
[CE_CLEAN_FULL_crop15] epoch 12 batch 175/1893, loss=0.0127, elapsed=132.0s
[CE_CLEAN_FULL_crop15] epoch 12 batch 200/1893, loss=0.0125, elapsed=149.3s
[CE_CLEAN_FULL_crop15] epoch 12 batch 225/1893, loss=0.0125, elapsed=168.7s
[CE_CLEAN_FULL_crop15] epoch 12 batch 250/1893, loss=0.0122, elapsed=187.4s
[CE_CLEAN_FULL_crop15] epoch 12 batch 275/1893, loss=0.0118, elapsed=204.9s
[CE_CLEAN_FULL_crop15] epoch 12 batch 300/1893, loss=0.0118, elapsed=222.4s
[CE_CLEAN_FULL_crop15] epoch 12 batch 325/1893, loss=0.0120, elapsed=240.8s
[CE_CLEAN_FULL_crop15] epoch 12 batch 350/1893, loss=0.0123, elapsed=259.0s
[CE_CLEAN_FULL_crop15] epoch 12 batch 375/1893, loss=0.0124, elapsed=276.1s
[CE_CLEAN_FULL_crop15] epoch 12 batch 400/1893, loss=0.0123, elapsed=293.8s
[CE_CLEAN_FULL_crop15] epoch 12 batch 425/1893, loss=0.0124, elapsed=314.5s
[CE_CLEAN_FULL_crop15] epoch 12 batch 450/1893, loss=0.0124, elapsed=332.0s
[CE_CLEAN_FULL_crop15] epoch 12 batch 475/1893, loss=0.0125, elapsed=349.4s
[CE_CLEAN_FULL_crop15] epoch 12 batch 500/1893, loss=0.0125, elapsed=366.8s
[CE_CLEAN_FULL_crop15] epoch 12 batch 525/1893, loss=0.0124, elapsed=386.7s
[CE_CLEAN_FULL_crop15] epoch 12 batch 550/1893, loss=0.0123, elapsed=403.9s
[CE_CLEAN_FULL_crop15] epoch 12 batch 575/1893, loss=0.0123, elapsed=420.8s
[CE_CLEAN_FULL_crop15] epoch 12 batch 600/1893, loss=0.0124, elapsed=438.1s
[CE_CLEAN_FULL_crop15] epoch 12 batch 625/1893, loss=0.0123, elapsed=458.3s
[CE_CLEAN_FULL_crop15] epoch 12 batch 650/1893, loss=0.0123, elapsed=475.7s
[CE_CLEAN_FULL_crop15] epoch 12 batch 675/1893, loss=0.0124, elapsed=493.0s
[CE_CLEAN_FULL_crop15] epoch 12 batch 700/1893, loss=0.0124, elapsed=510.7s
[CE_CLEAN_FULL_crop15] epoch 12 batch 725/1893, loss=0.0122, elapsed=530.3s
[CE_CLEAN_FULL_crop15] epoch 12 batch 750/1893, loss=0.0122, elapsed=548.7s
[CE_CLEAN_FULL_crop15] epoch 12 batch 775/1893, loss=0.0122, elapsed=567.3s
[CE_CLEAN_FULL_crop15] epoch 12 batch 800/1893, loss=0.0123, elapsed=585.2s
[CE_CLEAN_FULL_crop15] epoch 12 batch 825/1893, loss=0.0122, elapsed=605.1s
[CE_CLEAN_FULL_crop15] epoch 12 batch 850/1893, loss=0.0123, elapsed=622.9s
[CE_CLEAN_FULL_crop15] epoch 12 batch 875/1893, loss=0.0124, elapsed=643.8s
[CE_CLEAN_FULL_crop15] epoch 12 batch 900/1893, loss=0.0124, elapsed=663.0s
[CE_CLEAN_FULL_crop15] epoch 12 batch 925/1893, loss=0.0124, elapsed=683.8s
[CE_CLEAN_FULL_crop15] epoch 12 batch 950/1893, loss=0.0125, elapsed=704.3s
[CE_CLEAN_FULL_crop15] epoch 12 batch 975/1893, loss=0.0125, elapsed=726.1s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1000/1893, loss=0.0125, elapsed=745.6s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1025/1893, loss=0.0125, elapsed=764.9s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1050/1893, loss=0.0125, elapsed=783.7s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1075/1893, loss=0.0125, elapsed=805.0s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1100/1893, loss=0.0124, elapsed=823.7s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1125/1893, loss=0.0125, elapsed=842.3s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1150/1893, loss=0.0125, elapsed=861.8s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1175/1893, loss=0.0125, elapsed=881.3s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1200/1893, loss=0.0125, elapsed=898.5s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1225/1893, loss=0.0125, elapsed=917.7s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1250/1893, loss=0.0125, elapsed=937.0s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1275/1893, loss=0.0125, elapsed=961.4s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1300/1893, loss=0.0124, elapsed=980.8s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1325/1893, loss=0.0124, elapsed=999.0s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1350/1893, loss=0.0124, elapsed=1016.4s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1375/1893, loss=0.0124, elapsed=1036.1s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1400/1893, loss=0.0125, elapsed=1053.8s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1425/1893, loss=0.0124, elapsed=1074.3s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1450/1893, loss=0.0124, elapsed=1093.7s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1475/1893, loss=0.0124, elapsed=1115.2s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1500/1893, loss=0.0125, elapsed=1132.7s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1525/1893, loss=0.0124, elapsed=1150.4s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1550/1893, loss=0.0125, elapsed=1168.6s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1575/1893, loss=0.0125, elapsed=1188.2s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1600/1893, loss=0.0125, elapsed=1206.0s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1625/1893, loss=0.0125, elapsed=1224.1s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1650/1893, loss=0.0125, elapsed=1242.5s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1675/1893, loss=0.0125, elapsed=1263.2s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1700/1893, loss=0.0125, elapsed=1281.1s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1725/1893, loss=0.0125, elapsed=1298.8s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1750/1893, loss=0.0125, elapsed=1317.1s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1775/1893, loss=0.0125, elapsed=1337.2s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1800/1893, loss=0.0126, elapsed=1355.2s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1825/1893, loss=0.0125, elapsed=1373.1s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1850/1893, loss=0.0126, elapsed=1391.1s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1875/1893, loss=0.0125, elapsed=1411.6s
[CE_CLEAN_FULL_crop15] epoch 12 batch 1893/1893, loss=0.0125, elapsed=1423.6s
[Inference] Starting 66379 scored images
[Inference] batch 1/260, elapsed=6.0s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 25/260, elapsed=36.6s
[Inference] batch 50/260, elapsed=66.3s
[Inference] batch 75/260, elapsed=98.9s
[Inference] batch 100/260, elapsed=131.4s
[Inference] batch 125/260, elapsed=166.2s
[Inference] batch 150/260, elapsed=203.5s
[Inference] batch 175/260, elapsed=241.0s
[Inference] batch 200/260, elapsed=279.5s
[Inference] batch 225/260, elapsed=317.7s
[Inference] batch 250/260, elapsed=355.8s
[Inference] batch 260/260, elapsed=367.0s
CE_CLEAN_FULL_crop15 epoch 12 Full Test-as-Val ACER 0.04684910600727319 best 11 patience 1
[Inference] Starting 66379 scored images
[Inference] batch 1/260, elapsed=6.8s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 25/260, elapsed=40.1s
[Inference] batch 50/260, elapsed=71.0s
[Inference] batch 75/260, elapsed=103.7s
[Inference] batch 100/260, elapsed=135.5s
[Inference] batch 125/260, elapsed=169.6s
[Inference] batch 150/260, elapsed=204.3s
[Inference] batch 175/260, elapsed=234.3s
[Inference] batch 200/260, elapsed=265.1s
[Inference] batch 225/260, elapsed=296.5s
[Inference] batch 250/260, elapsed=332.3s
[Inference] batch 260/260, elapsed=342.2s
[Inference] Starting 8283 scored images
[Inference] batch 1/33, elapsed=6.2s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 25/33, elapsed=47.6s
[Inference] batch 33/33, elapsed=57.1s
[Inference] Starting 2947 scored images
[Inference] batch 1/12, elapsed=6.0s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 12/12, elapsed=22.2s
[Inference] Starting 7564 scored images
[Inference] batch 1/30, elapsed=7.8s

/tmp/ipykernel_23/1895080082.py:301: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=use_amp):z=model(x.to(device,non_blocking=True))

[Inference] batch 25/30, elapsed=46.4s
[Inference] batch 30/30, elapsed=53.2s

,run_id,dataset,unit,threshold_policy,auc,eer,apcer,bpcer,acer,hter,scored_n,candidate_n
0,CE_CLEAN_FULL_crop15,test,frame,source-calibrated,0.992290,0.044373,0.050070,0.038059,0.044064,0.044064,66379,67170
1,CE_CLEAN_FULL_crop15,lcc_training,frame,source-calibrated,0.871429,0.212883,0.056649,0.505728,0.281189,0.281189,8283,8299
2,CE_CLEAN_FULL_crop15,lcc_development,frame,source-calibrated,0.816842,0.259645,0.107002,0.491358,0.299180,0.299180,2947,2948
3,CE_CLEAN_FULL_crop15,lcc_evaluation,frame,source-calibrated,0.816108,0.258567,0.081793,0.506369,0.294081,0.294081,7564,7580
4,CE_CLEAN_FULL_crop15,lcc_combined,frame,source-calibrated,0.844427,0.240079,0.075061,0.502834,0.288947,0.288947,18794,18827

[CASIA] Reloaded best checkpoint: CE_CLEAN_FULL_crop15 epoch 11
Candidate populations: {'train': {'candidate_frames': 1655, 'candidate_videos': 240}, 'test': {'candidate_frames': 2408, 'candidate_videos': 360}, 'combined': {'candidate_frames': 2660, 'candidate_videos': 360}}
Train/test image-copy overlap: {'subjects': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'video_ids': 240, 'frame_ids': 1403}

       split  binary_label attack_type quality  videos
0   combined             0        real    high      30
1   combined             0        real     low      30
2   combined             0        real  normal      30
3   combined             1         cut    high      30
4   combined             1         cut     low      30
5   combined             1         cut  normal      30
6   combined             1      replay    high      30
7   combined             1      replay     low      30
8   combined             1      replay  normal      30
9   combined             1      warped    high      30
10  combined             1      warped     low      30
11  combined             1      warped  normal      30
12      test             0        real    high      30
13      test             0        real     low      30
14      test             0        real  normal      30
15      test             1         cut    high      30
16      test             1         cut     low      30
17      test             1         cut  normal      30
18      test             1      replay    high      30
19      test             1      replay     low      30
20      test             1      replay  normal      30
21      test             1      warped    high      30
22      test             1      warped     low      30
23      test             1      warped  normal      30
24     train             0        real    high      20
25     train             0        real     low      20
26     train             0        real  normal      20
27     train             1         cut    high      20
28     train             1         cut     low      20
29     train             1         cut  normal      20
30     train             1      replay    high      20
31     train             1      replay     low      20
32     train             1      replay  normal      20
33     train             1      warped    high      20
34     train             1      warped     low      20
35     train             1      warped  normal      20

SCRFD active providers: ['CUDAExecutionProvider', 'CPUExecutionProvider']
[Detection] Starting shared full train/test localization
[Detection] 1/4063 frames; valid=1; elapsed=5.3s
[Detection] 100/4063 frames; valid=100; elapsed=7.5s
[Detection] 200/4063 frames; valid=200; elapsed=9.5s
[Detection] 300/4063 frames; valid=300; elapsed=13.6s
[Detection] 400/4063 frames; valid=400; elapsed=15.6s
[Detection] 500/4063 frames; valid=500; elapsed=17.7s
[Detection] 600/4063 frames; valid=600; elapsed=19.8s
[Detection] 700/4063 frames; valid=700; elapsed=21.9s
[Detection] 800/4063 frames; valid=800; elapsed=24.1s
[Detection] 900/4063 frames; valid=900; elapsed=26.3s
[Detection] 1000/4063 frames; valid=1000; elapsed=28.6s
[Detection] 1100/4063 frames; valid=1100; elapsed=31.0s
[Detection] 1200/4063 frames; valid=1200; elapsed=33.3s
[Detection] 1300/4063 frames; valid=1300; elapsed=35.5s
[Detection] 1400/4063 frames; valid=1400; elapsed=38.0s
[Detection] 1500/4063 frames; valid=1500; elapsed=40.2s
[Detection] 1600/4063 frames; valid=1600; elapsed=42.4s
[Detection] 1700/4063 frames; valid=1700; elapsed=44.6s
[Detection] 1800/4063 frames; valid=1800; elapsed=46.8s
[Detection] 1900/4063 frames; valid=1900; elapsed=49.0s
[Detection] 2000/4063 frames; valid=2000; elapsed=51.3s
[Detection] 2100/4063 frames; valid=2100; elapsed=53.5s
[Detection] 2200/4063 frames; valid=2200; elapsed=55.7s
[Detection] 2300/4063 frames; valid=2300; elapsed=57.9s
[Detection] 2400/4063 frames; valid=2400; elapsed=60.1s
[Detection] 2500/4063 frames; valid=2500; elapsed=62.4s
[Detection] 2600/4063 frames; valid=2600; elapsed=64.8s
[Detection] 2700/4063 frames; valid=2700; elapsed=67.1s
[Detection] 2800/4063 frames; valid=2800; elapsed=69.3s
[Detection] 2900/4063 frames; valid=2900; elapsed=71.5s
[Detection] 3000/4063 frames; valid=3000; elapsed=73.7s
[Detection] 3100/4063 frames; valid=3100; elapsed=76.1s
[Detection] 3200/4063 frames; valid=3200; elapsed=78.2s
[Detection] 3300/4063 frames; valid=3300; elapsed=80.5s
[Detection] 3400/4063 frames; valid=3400; elapsed=82.7s
[Detection] 3500/4063 frames; valid=3500; elapsed=84.8s
[Detection] 3600/4063 frames; valid=3600; elapsed=87.1s
[Detection] 3700/4063 frames; valid=3700; elapsed=89.3s
[Detection] 3800/4063 frames; valid=3800; elapsed=91.6s
[Detection] 3900/4063 frames; valid=3900; elapsed=93.9s
[Detection] 4000/4063 frames; valid=4000; elapsed=96.0s
[Detection] 4063/4063 frames; valid=4063; elapsed=97.5s
[Detection complete] 4063/4063 raw train/test frames

      split  candidate_videos  scorable_videos  candidate_frames  valid_frames
0  combined               360              358              2660          2660
1      test               360              352              2408          2408
2     train               240              237              1655          1655

failure_reason
    4063
Name: count, dtype: int64

[Inference] CE_CLEAN_FULL_crop15: 4063 shared crops, 16 batches; threshold=4.8642578125
[Inference] CE_CLEAN_FULL_crop15 batch 1/16; elapsed=0.1s
[Inference] CE_CLEAN_FULL_crop15 batch 16/16; elapsed=2.0s
[Result] CE_CLEAN_FULL_crop15 / train: video AUC=0.8829746714911445, HTER=0.2937535707484289, frame AUC=0.8816807939786786
[Result] CE_CLEAN_FULL_crop15 / test: video AUC=0.8650568181818181, HTER=0.3371212121212121, frame AUC=0.8428537771209492
[Result] CE_CLEAN_FULL_crop15 / combined: video AUC=0.8771973466003317, HTER=0.329726368159204, frame AUC=0.855509710406077
[Done] CE_CLEAN_FULL_crop15: train / test / combined saved

,run_id,split,best_epoch,locked_source_threshold,auc,eer,apcer,bpcer,acer,hter,binary_accuracy,tpr_at_fpr_1pct,scored_n,candidate_n,frame_auc,frame_acer
0,CE_CLEAN_FULL_crop15,train,11,4.864258,0.882975,0.197201,0.011236,0.576271,0.293754,0.293754,0.848101,0.389831,237,240,0.881681,0.291139
1,CE_CLEAN_FULL_crop15,test,11,4.864258,0.865057,0.204545,0.026515,0.647727,0.337121,0.337121,0.818182,0.284091,352,360,0.842854,0.335125
2,CE_CLEAN_FULL_crop15,combined,11,4.864258,0.877197,0.200746,0.026119,0.633333,0.329726,0.329726,0.821229,0.311111,358,360,0.855510,0.313379

CASIA train-calibrated thresholds transferred unchanged to test/combined:

,run_id,split,unit,source_threshold,casia_calibrated_threshold,source_acer,acer,source_hter,hter,apcer,bpcer
0,CE_CLEAN_FULL_crop15,train,frame,4.864258,0.086853,0.291139,0.208663,0.291139,0.208663,0.184652,0.232673
1,CE_CLEAN_FULL_crop15,test,frame,4.864258,0.086853,0.335125,0.237315,0.335125,0.237315,0.170061,0.304569
2,CE_CLEAN_FULL_crop15,combined,frame,4.864258,0.086853,0.313379,0.225582,0.313379,0.225582,0.173716,0.277448
3,CE_CLEAN_FULL_crop15,train,video,4.864258,-1.645801,0.293754,0.194296,0.293754,0.194296,0.219101,0.169492
4,CE_CLEAN_FULL_crop15,test,video,4.864258,-1.645801,0.337121,0.212121,0.337121,0.212121,0.231061,0.193182
5,CE_CLEAN_FULL_crop15,combined,video,4.864258,-1.645801,0.329726,0.204561,0.329726,0.204561,0.231343,0.177778

Saved report and ZIP: /kaggle/working/21_fullscale_CE_clean_baseline_crop15_s105/runs/CE_CLEAN_FULL_crop15/casia.zip
Shared crop cache is excluded from the ZIP; raw detection/crop metadata is included.

/kaggle/working/21_fullscale_CE_clean_baseline_crop15_s105/runs/CE_CLEAN_FULL_crop15/casia.zip

,run_id,dataset,unit,threshold_policy,auc,eer,apcer,bpcer,acer,hter,scored_n,candidate_n
0,CE_CLEAN_FULL_crop15,test,frame,source-calibrated,0.992290,0.044373,0.050070,0.038059,0.044064,0.044064,66379,67170
1,CE_CLEAN_FULL_crop15,lcc_training,frame,source-calibrated,0.871429,0.212883,0.056649,0.505728,0.281189,0.281189,8283,8299
2,CE_CLEAN_FULL_crop15,lcc_development,frame,source-calibrated,0.816842,0.259645,0.107002,0.491358,0.299180,0.299180,2947,2948
3,CE_CLEAN_FULL_crop15,lcc_evaluation,frame,source-calibrated,0.816108,0.258567,0.081793,0.506369,0.294081,0.294081,7564,7580
4,CE_CLEAN_FULL_crop15,lcc_combined,frame,source-calibrated,0.844427,0.240079,0.075061,0.502834,0.288947,0.288947,18794,18827
5,CE_CLEAN_FULL_crop15,casia_train,video,source-calibrated,0.882975,0.197201,0.011236,0.576271,0.293754,0.293754,237,240
6,CE_CLEAN_FULL_crop15,casia_train,frame,source-calibrated,0.881681,0.213150,0.032774,0.549505,0.291139,0.291139,1655,1655
7,CE_CLEAN_FULL_crop15,casia_test,video,source-calibrated,0.865057,0.204545,0.026515,0.647727,0.337121,0.337121,352,360
8,CE_CLEAN_FULL_crop15,casia_test,frame,source-calibrated,0.842854,0.231205,0.037424,0.632826,0.335125,0.335125,2408,2408
9,CE_CLEAN_FULL_crop15,casia_combined,video,source-calibrated,0.877197,0.200746,0.026119,0.633333,0.329726,0.329726,358,360
10,CE_CLEAN_FULL_crop15,casia_combined,frame,source-calibrated,0.855510,0.216315,0.036254,0.590504,0.313379,0.313379,2660,2660
11,CE_CLEAN_FULL_crop15,casia_train,frame,CASIA train-calibrated,0.881681,0.213150,0.184652,0.232673,0.208663,0.208663,1655,1655
12,CE_CLEAN_FULL_crop15,casia_test,frame,CASIA train-calibrated,0.842854,0.231205,0.170061,0.304569,0.237315,0.237315,2408,2408
13,CE_CLEAN_FULL_crop15,casia_combined,frame,CASIA train-calibrated,0.855510,0.216315,0.173716,0.277448,0.225582,0.225582,2660,2660
14,CE_CLEAN_FULL_crop15,casia_train,video,CASIA train-calibrated,0.882975,0.197201,0.219101,0.169492,0.194296,0.194296,237,240
15,CE_CLEAN_FULL_crop15,casia_test,video,CASIA train-calibrated,0.865057,0.204545,0.231061,0.193182,0.212121,0.212121,352,360
16,CE_CLEAN_FULL_crop15,casia_combined,video,CASIA train-calibrated,0.877197,0.200746,0.231343,0.177778,0.204561,0.204561,358,360

Saved results ZIP: /kaggle/working/21_fullscale_CE_clean_baseline_crop15_s105.zip

/kaggle/working/21_fullscale_CE_clean_baseline_crop15_s105.zip

Saved run ZIP: /kaggle/working/21_fullscale_CE_clean_baseline_crop15_s105/CE_CLEAN_FULL_crop15_s105.zip

/kaggle/working/21_fullscale_CE_clean_baseline_crop15_s105/CE_CLEAN_FULL_crop15_s105.zip

Finished CE-only baseline: ['CE_CLEAN_FULL_crop15']